import { createHash,randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { WorldRepository } from '../../persistence/src/repository.js';
import type { AgentFilesystem,TreeSnapshotFile } from '../../sandbox/src/filesystem.js';
import type { AgentRecord,PublishedToolVersion,ToolManifest,ToolVisibility } from '../../shared/src/index.js';

export interface PublishToolRequest{sourceDirectory:string;entrypoint:string;runtime:'node'|'python';name:string;description:string;visibility:ToolVisibility;usage?:string;previousVersionId?:string;}
export interface ToolStoreLimits{maxFiles:number;maxBytes:number;}
export const DEFAULT_TOOL_LIMITS:ToolStoreLimits={maxFiles:100,maxBytes:512*1024};

export class UserlandToolStore{
  readonly storeRoot:string;
  constructor(private readonly dataDir:string,private readonly repo:WorldRepository,private readonly agentFiles:AgentFilesystem,private readonly limits=DEFAULT_TOOL_LIMITS){this.storeRoot=path.resolve(dataDir,'system','tool-store');}
  private hash(files:TreeSnapshotFile[]):string{const digest=createHash('sha256');for(const file of files)digest.update(file.relativePath).update('\0').update(file.content).update('\0');return digest.digest('hex');}
  private async writeSnapshot(sourceHash:string,files:TreeSnapshotFile[],canCommit:()=>boolean):Promise<string>{await fs.mkdir(this.storeRoot,{recursive:true});const finalPath=path.join(this.storeRoot,sourceHash);try{const stat=await fs.lstat(finalPath);if(!stat.isDirectory()||stat.isSymbolicLink())throw new Error('Tool store collision is not a regular directory');await this.verifySnapshot(finalPath,sourceHash);return path.relative(this.dataDir,finalPath);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
    const staged=path.join(this.storeRoot,`.publish-${randomUUID()}`);try{await fs.mkdir(staged,{recursive:false});for(const file of files){const target=path.join(staged,...file.relativePath.split('/'));await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,file.content,{flag:'wx',mode:0o400});}if(!canCommit())throw new Error('Runner ownership lost before tool snapshot commit');await fs.rename(staged,finalPath);await this.makeReadonly(finalPath);return path.relative(this.dataDir,finalPath);}finally{await fs.rm(staged,{recursive:true,force:true}).catch(()=>undefined);}}
  private async makeReadonly(directory:string):Promise<void>{for(const entry of await fs.readdir(directory,{withFileTypes:true})){const target=path.join(directory,entry.name);if(entry.isDirectory()){await this.makeReadonly(target);await fs.chmod(target,0o500).catch(()=>undefined);}else await fs.chmod(target,0o400).catch(()=>undefined);}await fs.chmod(directory,0o500).catch(()=>undefined);}
  private async readStoredFiles(directory:string):Promise<TreeSnapshotFile[]>{const files:TreeSnapshotFile[]=[];const walk=async(current:string):Promise<void>=>{for(const entry of await fs.readdir(current,{withFileTypes:true})){const target=path.join(current,entry.name),stat=await fs.lstat(target);if(stat.isSymbolicLink())throw new Error('Immutable tool snapshot contains a link');if(stat.isDirectory())await walk(target);else if(stat.isFile()){const content=await fs.readFile(target);files.push({relativePath:path.relative(directory,target).replaceAll('\\','/'),content,bytes:content.length});}else throw new Error('Immutable tool snapshot contains a special file');}};await walk(directory);return files.sort((a,b)=>a.relativePath.localeCompare(b.relativePath));}
  async verifySnapshot(directory:string,expectedHash:string):Promise<void>{const resolved=path.resolve(directory);if(resolved!==this.storeRoot&&!resolved.startsWith(this.storeRoot+path.sep))throw new Error('Tool snapshot escaped kernel store');const actual=this.hash(await this.readStoredFiles(resolved));if(actual!==expectedHash)throw new Error('Immutable tool snapshot hash mismatch');}
  async publish(publisher:AgentRecord,tick:number,request:PublishToolRequest,maxChargeBytes=Number.MAX_SAFE_INTEGER,canCommit:()=>boolean=()=>true):Promise<{version:PublishedToolVersion;storePath:string;totalBytes:number}>{const files=await this.agentFiles.snapshotTree(publisher.id,request.sourceDirectory,this.limits),portableEntry=request.entrypoint.replaceAll('\\','/');if(portableEntry.startsWith('/')||portableEntry.split('/').includes('..')||!files.some((file)=>file.relativePath===portableEntry))throw new Error('Tool entrypoint must be a regular file inside the source snapshot');const totalBytes=files.reduce((sum,file)=>sum+file.bytes,0);if(totalBytes>maxChargeBytes)throw new Error('Storage quota exceeded by tool snapshot');const sourceHash=this.hash(files),relativeStorePath=await this.writeSnapshot(sourceHash,files,canCommit),manifest:ToolManifest={name:request.name,description:request.description,usage:request.usage??null,visibility:request.visibility,runtime:request.runtime,entrypoint:portableEntry,inputProtocol:'json-stdin',fileCount:files.length,totalBytes,sourceHash};let previousVersionId:string|null=null;if(request.previousVersionId){const previous=this.repo.getToolVersion(request.previousVersionId);if(!previous||previous.publisherAgentId!==publisher.id||previous.manifest.name!==request.name)throw new Error('Previous tool version does not belong to this publisher and tool name');previousVersionId=previous.id;}if(!canCommit())throw new Error('Runner ownership lost before tool version commit');const version=this.repo.createToolVersion({publisher,tick,visibility:request.visibility,runtime:request.runtime,entrypoint:portableEntry,sourceHash,manifest,previousVersionId,storePath:relativeStorePath});return{version,storePath:path.resolve(this.dataDir,relativeStorePath),totalBytes:manifest.totalBytes};}
  async executablePath(version:PublishedToolVersion):Promise<string>{const relative=this.repo.toolStorePath(version.id);if(!relative)throw new Error('Tool snapshot path is missing');const directory=path.resolve(this.dataDir,relative);if(directory!==this.storeRoot&&!directory.startsWith(this.storeRoot+path.sep))throw new Error('Tool snapshot path escaped kernel store');await this.verifySnapshot(directory,version.sourceHash);const entrypoint=path.resolve(directory,...version.entrypoint.split('/'));if(entrypoint!==directory&&entrypoint.startsWith(directory+path.sep)){const stat=await fs.lstat(entrypoint);if(stat.isFile()&&!stat.isSymbolicLink())return directory;}throw new Error('Published tool entrypoint is invalid');}
}
