import { describe,expect,it,vi } from 'vitest';
import { OpenAICompatibleCognitionProvider,type CognitionInput } from '../packages/cognition/src/index.js';

const input={identity:{id:'a',name:'Mam',bootstrapInstruction:'You exist.'},currentObservation:{tick:1,world:{status:'running' as const,populationCount:1,simulatedTime:'2026-01-01T00:00:00.000Z'},self:{} as never,nearbyOrRelevantEvents:[],privateArtifacts:[],sharedArtifacts:[],workingArtifacts:[],newlyDeliveredMessages:[],recentExecutions:[],accessibleResources:{computeCredits:1,storageBytes:0},kernelCapabilities:[],userlandTools:[],contextDelivery:{newObservationEventIds:[],newMessageIds:[],actionResultIds:[],sharedConsequenceIds:[],continuityEventIds:[],truncations:[]}},relevantMemories:[],availableActions:[]} satisfies CognitionInput;
const response=(body:unknown,status=200)=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const validBody={choices:[{message:{content:JSON.stringify({thoughtSummary:'I will wait.',selectedAction:{type:'WAIT',ticks:2}})}}],usage:{total_tokens:12}};

describe('OpenAI-compatible provider contract',()=>{
  it('accepts a valid structured action and records usage metadata',async()=>{const fetcher=vi.fn(async()=>response(validBody)) as unknown as typeof fetch;const result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher}).think(input);expect(result.selectedAction).toEqual({type:'WAIT',ticks:2});expect(result.reasoningMetadata?.usage).toEqual({total_tokens:12});});
  it('discards model-supplied provider metadata and retains only kernel measurements',async()=>{const fetcher=vi.fn(async()=>response({choices:[{message:{content:JSON.stringify({thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerError:'untrusted infrastructure detail',providerAttempts:999}})}}],usage:{prompt_tokens:3,completion_tokens:1}})) as unknown as typeof fetch;const result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher}).think(input);expect(result.reasoningMetadata).toMatchObject({inputTokens:3,outputTokens:1,providerAttempts:1,providerRequestSucceeded:true});expect(JSON.stringify(result.reasoningMetadata)).not.toContain('untrusted infrastructure detail');});
  it.each([
    ['malformed JSON',response('not json')],
    ['unsupported action',response({choices:[{message:{content:JSON.stringify({thoughtSummary:'x',selectedAction:{type:'SHELL'}})}}]})],
    ['empty output',response({choices:[{message:{content:''}}]})],
    ['invalid arguments',response({choices:[{message:{content:JSON.stringify({thoughtSummary:'x',selectedAction:{type:'WAIT',ticks:999}})}}]})],
    ['provider error',response({error:'bad'},503)],
    ['oversized output',response('x'.repeat(2_000))],
  ])('uses safe WAIT after bounded retries for %s',async(_name,reply)=>{const fetcher=vi.fn(async()=>reply) as unknown as typeof fetch;const result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher,maxRetries:1,maxOutputBytes:1_000}).think(input);expect(result.selectedAction).toEqual({type:'WAIT',ticks:1});expect(result.reasoningMetadata?.providerError).toBeTruthy();expect(fetcher).toHaveBeenCalledTimes(2);});
  it('turns a timeout into safe WAIT after bounded recovery',async()=>{const fetcher=vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))) as unknown as typeof fetch;const result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher,timeoutMs:5,maxRetries:0}).think(input);expect(result.selectedAction.type).toBe('WAIT');expect(result.reasoningMetadata?.providerError).toMatch(/timed out/i);});
  it('classifies transport, timeout, HTTP, parse, and schema failures without changing retryability',async()=>{const cases:Array<{name:string;fetcher:typeof fetch;phase:string;httpStatus?:number}>=[{name:'transport',fetcher:vi.fn(async()=>{throw new Error('socket failed');}) as unknown as typeof fetch,phase:'transport'},{name:'timeout',fetcher:vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))) as unknown as typeof fetch,phase:'timeout'},{name:'HTTP 429',fetcher:vi.fn(async()=>response({error:{code:429,message:'slow down'}},429)) as unknown as typeof fetch,phase:'http',httpStatus:429},{name:'HTTP 500',fetcher:vi.fn(async()=>response({error:{code:'server_error',message:'unavailable'}},500)) as unknown as typeof fetch,phase:'http',httpStatus:500},{name:'response parse',fetcher:vi.fn(async()=>response('not json')) as unknown as typeof fetch,phase:'response_parse',httpStatus:200},{name:'response schema',fetcher:vi.fn(async()=>response({choices:[{message:{content:JSON.stringify({thoughtSummary:'x',selectedAction:{type:'SHELL'}})}}]})) as unknown as typeof fetch,phase:'response_schema',httpStatus:200}];for(const item of cases){const result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher:item.fetcher,timeoutMs:5,maxRetries:0}).think(input);expect(result.reasoningMetadata?.providerFailure,item.name).toMatchObject({phase:item.phase,retryable:true,...(item.httpStatus!==undefined?{httpStatus:item.httpStatus}:{})});expect(result.reasoningMetadata?.providerAttempts,item.name).toBe(1);}});
  it('captures bounded sanitized OpenRouter error details without retrying deterministic failures',async()=>{const secret='sk-secret-never-persist',fetcher=vi.fn(async()=>response({error:{code:402,type:'insufficient_credits',message:`Credit required at https://example.test/?key=${secret}`}},402)) as unknown as typeof fetch,result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher,maxRetries:3}).think(input);expect(fetcher).toHaveBeenCalledOnce();expect(result.reasoningMetadata).toMatchObject({providerError:'Provider HTTP 402',providerAttempts:1,providerFailure:{phase:'http',httpStatus:402,code:'402',type:'insufficient_credits',responseBodyJson:true,retryable:false}});expect(JSON.stringify(result)).not.toContain(secret);expect(JSON.stringify(result)).not.toContain('example.test');});
  it('honors bounded 429 retry metadata and succeeds on the next attempt',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({error:{code:429,type:'rate_limit',message:'slow down'}}),{status:429,headers:{'content-type':'application/json','retry-after':'0'}})).mockResolvedValueOnce(response(validBody)) as unknown as typeof fetch,result=await new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher,maxRetries:2}).think(input);expect(fetcher).toHaveBeenCalledTimes(2);expect(result.reasoningMetadata).toMatchObject({providerRequestSucceeded:true,providerAttempts:2});});
});
