import { createHash,randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import type { CognitionInput,CognitionProvider } from '../packages/cognition/src/index.js';
import { CAPABILITIES,type AgentRecord } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig,type WorldConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup(provider?:CognitionProvider,overrides:Partial<WorldConfig>={}){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-context-'));dirs.push(dir);const engine=new WorldEngine({...defaultConfig(dir),...overrides},provider);await engine.genesis();return engine;}
const wait=()=>({thoughtSummary:'wait',selectedAction:{type:'WAIT' as const,ticks:1}});
function extraAgent(name:string):AgentRecord{return{id:randomUUID(),name,createdAt:new Date().toISOString(),generation:0,parentIds:[],status:'active',cognitionConfig:{provider:'test'},capabilities:[...CAPABILITIES],metadata:{test:true},computeCredits:10_000,storageBytes:0,sleepingUntilTick:0,eligibleFromTick:0};}

describe('durable cognition observation cursors',()=>{
  it('delivers one message once as new context and permits later local-memory recall',async()=>{const inputs:CognitionInput[]=[],provider:CognitionProvider={async think(input){inputs.push(input);return wait();}},engine=await setup(provider),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(mam.id,{type:'SEND_MESSAGE',to:toey.id,content:'one durable hello'});engine.resume();await engine.tick();expect(engine.repo.observationCursor(toey.id).messageRowId).toBeGreaterThan(0);await engine.tick();engine.repo.addMemory(toey.id,'knowledge','one durable hello remembered locally',2,{salience:1});await engine.tick();const seen=inputs.filter((input)=>input.identity.name==='Toey');expect(seen[0]?.currentObservation.newlyDeliveredMessages.map((message)=>message.content)).toEqual(['one durable hello']);expect(seen[1]?.currentObservation.newlyDeliveredMessages).toEqual([]);expect(seen[2]?.relevantMemories.some((memory)=>memory.content.includes('remembered locally'))).toBe(true);expect(engine.repo.messagesFor(toey.id).map((message)=>message.content)).toContain('one durable hello');engine.close();});

  it('does not consume an unseen message or action result on provider failure and survives restart',async()=>{let failToey=true;const firstInputs:CognitionInput[]=[],provider:CognitionProvider={async think(input){firstInputs.push(input);if(input.identity.name==='Toey'&&failToey){failToey=false;return{...wait(),reasoningMetadata:{providerRequestSucceeded:false,providerError:'test failure'}};}return wait();}},engine=await setup(provider),dir=engine.config.dataDir,mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(mam.id,{type:'SEND_MESSAGE',to:toey.id,content:'survive failure'});engine.resume();await engine.tick();expect(firstInputs.find((input)=>input.identity.name==='Toey')?.currentObservation.newlyDeliveredMessages[0]?.content).toBe('survive failure');expect(engine.repo.observationCursor(toey.id).messageRowId).toBe(0);await engine.tick();expect(firstInputs.filter((input)=>input.identity.name==='Toey')[1]?.currentObservation.newlyDeliveredMessages[0]?.content).toBe('survive failure');const ownResult=engine.repo.listEvents(100).find((event)=>event.type==='ACTION_RESULT'&&event.actorId===toey.id)!;engine.close();let failRestartedToey=true;const restartedInputs:CognitionInput[]=[],restarted=new WorldEngine(defaultConfig(dir),{async think(input){restartedInputs.push(input);if(input.identity.name==='Toey'&&failRestartedToey){failRestartedToey=false;return{...wait(),reasoningMetadata:{providerRequestSucceeded:false,providerError:'test failure'}};}return wait();}});restarted.resume();const beforeResultCursor=restarted.repo.observationCursor(toey.id).ownEventId;await restarted.tick();expect(restarted.repo.observationCursor(toey.id).ownEventId).toBe(beforeResultCursor);await restarted.tick();const toeyRestarted=restartedInputs.filter((input)=>input.identity.name==='Toey');expect(toeyRestarted[0]?.currentObservation.nearbyOrRelevantEvents.some((event)=>event.id===ownResult.id&&event.delivery==='NEW_ACTION_RESULT')).toBe(true);expect(toeyRestarted[1]?.currentObservation.nearbyOrRelevantEvents.some((event)=>event.id===ownResult.id&&event.delivery==='NEW_ACTION_RESULT')).toBe(true);restarted.close();});

  it('advances only delivered portions and rejects a stale runner token',async()=>{const engine=await setup(undefined,{cognitionInputBudgetTokens:5_000}),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!,mamBefore=engine.repo.observationCursor(mam.id);for(let index=0;index<8;index++)await engine.perform(mam.id,{type:'SEND_MESSAGE',to:toey.id,content:`message-${index}-`+'x'.repeat(3_500)});const diagnostic=await engine.cognitionContextDiagnostic(toey),before=engine.repo.observationCursor(toey.id);expect(diagnostic.messageIdsDelivered.length).toBeGreaterThan(0);expect(diagnostic.pending.messages).toBeGreaterThan(0);expect(engine.repo.observationCursor(toey.id)).toEqual(before);expect(engine.repo.acquireRunnerLease('old-runner',30_000)).toBe(true);engine.repo.releaseRunnerLease('old-runner');expect(engine.repo.acquireRunnerLease('new-runner',30_000)).toBe(true);expect(engine.repo.advanceObservationCursor(toey.id,{before,messageRowId:diagnostic.cursorAfter.messageRowId,ownEventId:diagnostic.cursorAfter.ownEventId,sharedEventId:diagnostic.cursorAfter.sharedEventId},0,'old-runner')).toBe(false);expect(engine.repo.observationCursor(toey.id)).toEqual(before);expect(engine.repo.observationCursor(mam.id)).toEqual(mamBefore);engine.repo.releaseRunnerLease('new-runner');engine.close();});

  it('excludes Owner-only and private foreign events while exposing shared publication',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;engine.repo.addEvent('COGNITION_PROVIDER_ERROR',0,mam.id,null,{error:'kernel only'});engine.repo.addEvent('TOOL_PUBLISHED',0,mam.id,null,{toolVersionId:'private-version',visibility:'PRIVATE'});const shared=engine.repo.addEvent('TOOL_PUBLISHED',0,mam.id,null,{toolVersionId:'shared-version',visibility:'SHARED'}),serialized=JSON.stringify(await engine.observe(toey));expect(serialized).not.toContain('kernel only');expect(serialized).not.toContain('private-version');expect(serialized).toContain('shared-version');expect((await engine.observe(toey)).contextDelivery.sharedConsequenceIds).toContain(shared.id);engine.close();});
});

describe('bounded multi-inhabitant cognition context',()=>{
  it.each([2,10,50])('stays within budget with %i inhabitants and large histories',async(population)=>{const budget=3_000,engine=await setup(undefined,{cognitionInputBudgetTokens:budget}),mam=engine.repo.getAgent('Mam')!;for(let index=2;index<population;index++)engine.repo.createAgent(extraAgent(`Agent-${index}`));for(let index=0;index<600;index++)engine.repo.addEvent(index%3===0?'RUNNER_STARTED':'TOOL_PUBLISHED',0,index%3===0?null:engine.repo.getAgent('Toey')!.id,null,index%3===0?{detail:'owner-only-'+index}:{toolVersionId:`shared-${index}`,visibility:'SHARED',detail:'z'.repeat(2_000)});for(let index=0;index<30;index++)engine.repo.sendMessage(engine.repo.getAgent('Toey')!.id,'agent',mam.id,0,`burst-${index}-`+'m'.repeat(3_000));for(let index=0;index<40;index++)engine.repo.addMemory(mam.id,'knowledge',`memory-${index}-`+'k'.repeat(2_000),0,{salience:0.5});for(let version=1;version<=60;version++)engine.repo.createToolVersion({publisher:mam,tick:0,visibility:'SHARED',runtime:'python',entrypoint:'main.py',sourceHash:String(version).padStart(64,'0'),manifest:{name:'scale-tool',description:'d'.repeat(500),usage:null,visibility:'SHARED',runtime:'python',entrypoint:'main.py',inputProtocol:'json-stdin',fileCount:1,totalBytes:1,sourceHash:String(version).padStart(64,'0')},previousVersionId:null,storePath:`system/tool-store/${version}`});const diagnostic=await engine.cognitionContextDiagnostic(mam);expect(diagnostic.estimatedTotalInputTokens).toBeLessThanOrEqual(budget);expect(diagnostic.sections.accessibleTools!.count).toBeLessThanOrEqual(8);expect((await engine.observe(mam)).world.populationCount).toBe(population);expect(JSON.stringify(await engine.observe(mam))).not.toContain('owner-only-');engine.close();});
});

describe('bounded recent artifact working context',()=>{
  it('keeps two substantive file projections, evicts the oldest, and refreshes rereads',async()=>{const inputs:CognitionInput[]=[],provider:CognitionProvider={async think(input){inputs.push(input);if(input.identity.name==='Toey')return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:10}};const pathByTick:Record<number,string>={0:'a.py',1:'b.py',2:'c.py',3:'a.py'},pathValue=pathByTick[input.currentObservation.tick];return pathValue?{thoughtSummary:`read ${pathValue}`,selectedAction:{type:'READ_FILE',path:pathValue}}:wait();}},engine=await setup(provider),mam=engine.repo.getAgent('Mam')!;for(const [pathValue,marker] of [['a.py','A'],['b.py','B'],['c.py','C']] as const)await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:pathValue,content:`${marker}_START\n${marker.toLowerCase().repeat(2_000)}\n${marker}_END`});engine.resume();await engine.run(5);const mamInputs=inputs.filter((input)=>input.identity.name==='Mam'),at=(tick:number)=>mamInputs.find((input)=>input.currentObservation.tick===tick)!.currentObservation.workingArtifacts;expect(at(2).map((item)=>item.path)).toEqual(['b.py','a.py']);expect(at(2).every((item)=>item.truncated&&item.content.includes(`${item.path[0]!.toUpperCase()}_START`)&&item.content.includes(`${item.path[0]!.toUpperCase()}_END`))).toBe(true);expect(at(3).map((item)=>item.path)).toEqual(['c.py','b.py']);expect(at(4).map((item)=>item.path)).toEqual(['a.py','c.py']);expect((await engine.cognitionContextDiagnostic(mam)).estimatedTotalInputTokens).toBeLessThanOrEqual(engine.config.cognitionInputBudgetTokens);engine.close();});

  it('never crosses private read history between inhabitants',async()=>{const inputs:CognitionInput[]=[],provider:CognitionProvider={async think(input){inputs.push(input);return input.currentObservation.tick===0?{thoughtSummary:'read own file',selectedAction:{type:'READ_FILE',path:`${input.identity.name.toLowerCase()}.txt`}}:wait();}},engine=await setup(provider),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'mam.txt',content:'MAM_PRIVATE_MARKER'});await engine.perform(toey.id,{type:'CREATE_TEXT_FILE',path:'toey.txt',content:'TOEY_PRIVATE_MARKER'});engine.resume();await engine.run(2);const mamContext=inputs.filter((input)=>input.identity.name==='Mam').at(-1)!.currentObservation.workingArtifacts,toeyContext=inputs.filter((input)=>input.identity.name==='Toey').at(-1)!.currentObservation.workingArtifacts;expect(mamContext.map((item)=>item.path)).toEqual(['mam.txt']);expect(toeyContext.map((item)=>item.path)).toEqual(['toey.txt']);expect(JSON.stringify(mamContext)).not.toContain('TOEY_PRIVATE_MARKER');expect(JSON.stringify(toeyContext)).not.toContain('MAM_PRIVATE_MARKER');engine.close();});

  it('reconstructs the same two reads after restart without advancing a cursor',async()=>{const engine=await setup(),dir=engine.config.dataDir,mam=engine.repo.getAgent('Mam')!;for(const [pathValue,content] of [['a.py','restart A'],['b.py','restart B']] as const){await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:pathValue,content});const result=await engine.perform(mam.id,{type:'READ_FILE',path:pathValue});engine.repo.addEvent('ACTION_RESULT',0,mam.id,null,{actionType:'READ_FILE',actionId:result.actionId,success:true,effects:result.effects});}engine.close();const restarted=new WorldEngine(defaultConfig(dir)),sameMam=restarted.repo.getAgent(mam.id)!,before=restarted.repo.observationCursor(mam.id),first=await restarted.observe(sameMam),afterFirst=restarted.repo.observationCursor(mam.id),second=await restarted.observe(sameMam);expect(first.workingArtifacts.map((item)=>item.path)).toEqual(['b.py','a.py']);expect(second.workingArtifacts).toEqual(first.workingArtifacts);expect(afterFirst).toEqual(before);expect(restarted.repo.observationCursor(mam.id)).toEqual(before);restarted.close();});

  it('drops working material before mandatory new messages and failed action results',async()=>{const engine=await setup(undefined,{cognitionInputBudgetTokens:4_000}),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!,seedRead=(pathValue:string,marker:string)=>{const content=`${marker}\n${marker.repeat(4_000)}`,hash=createHash('sha256').update(content).digest('hex');engine.repo.addEvent('ACTION_RESULT',0,mam.id,null,{actionType:'READ_FILE',actionId:randomUUID(),success:true,effects:[{path:pathValue,space:'PRIVATE',content,bytes:Buffer.byteLength(content),hash}]});};seedRead('a.py','A');seedRead('b.py','B');const cursor=engine.repo.observationCursor(mam.id),throughReads=engine.repo.latestEventId();expect(engine.repo.advanceObservationCursor(mam.id,{before:cursor,messageRowId:cursor.messageRowId,ownEventId:throughReads,sharedEventId:throughReads},0)).toBe(true);const message=engine.repo.sendMessage(toey.id,'agent',mam.id,0,'MANDATORY_MESSAGE_'+'.'.repeat(500)),failed=engine.repo.addEvent('ACTION_RESULT',0,mam.id,null,{actionType:'EXECUTE_PROGRAM',actionId:randomUUID(),success:false,effects:[{stderr:'MANDATORY_FAILURE_'+'.'.repeat(1_000)}],error:'Program exited with 1'}),before=engine.repo.observationCursor(mam.id),prepared=await engine.cognitionContextDiagnostic(mam);expect(prepared.messageIdsDelivered).toContain(message.id);expect(prepared.actionResultIdsDelivered).toContain(failed.id);expect(prepared.workingArtifacts.length).toBeLessThan(2);expect(prepared.estimatedTotalInputTokens).toBeLessThanOrEqual(engine.config.cognitionInputBudgetTokens);expect(engine.repo.observationCursor(mam.id)).toEqual(before);engine.close();});
});
