import { fundCognition,setLocal,local } from './resource-fixtures.js';
import { mkdtemp,rm } from 'node:fs/promises';
/* eslint-disable prefer-const */
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { afterEach,describe,expect,it } from 'vitest';
import { DeterministicCognitionProvider,type CognitionInput,type CognitionProvider } from '../packages/cognition/src/index.js';
import { InjectedCrash } from '../packages/operations/src/reconciliation.js';
import type { AgentRecord } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig,type DescendantTransition } from '../packages/world/src/engine.js';

const dirs:string[]=[];
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function world(overrides:Partial<ReturnType<typeof defaultConfig>>={},cognition?:CognitionProvider,hooks:ConstructorParameters<typeof WorldEngine>[5]={}){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-descendants-'));dirs.push(dir);const engine=new WorldEngine({...defaultConfig(dir),...overrides},cognition,undefined,{}, {},hooks);await engine.genesis();fundCognition(engine);return engine;}
async function propose(engine:WorldEngine,name='Nova',amount=550){const mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!,result=await engine.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:name,localComputeContribution:amount,cognitionContribution:0});return{mam,toey,result,proposalId:String((result.effects[0] as any)?.proposal?.id)};}
const reservedTotal=(engine:WorldEngine)=>engine.repo.economy.total('LOCAL_COMPUTE');

describe('Descendants v1 protocol',()=>{
  it('reserves a proposal, delivers it privately, enforces consent, and releases escrow on rejection',async()=>{const engine=await world(),{mam,toey,result,proposalId}=await propose(engine);expect(result.success).toBe(true);expect(local(engine,mam.id)).toBe(10_000-550);expect(engine.repo.getComputeReservation(proposalId)).toMatchObject({agentId:mam.id,amount:550,status:'RESERVED'});const toeyContext=await engine.cognitionContextDiagnostic(toey),mamContext=await engine.cognitionContextDiagnostic(mam);expect(toeyContext.newObservationEventIds).toHaveLength(1);expect(mamContext.newObservationEventIds).toHaveLength(1);const outsider:AgentRecord={...toey,id:randomUUID(),name:'Observer',createdAt:new Date().toISOString(),metadata:{test:true},eligibleFromTick:0};engine.repo.createAgent(outsider);expect((await engine.cognitionContextDiagnostic(outsider)).newObservationEventIds).toHaveLength(0);expect((await engine.perform(mam.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0})).error).toMatch(/requested co-parent/i);expect((await engine.perform(outsider.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'REJECT'})).error).toMatch(/requested co-parent/i);const rejected=await engine.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'REJECT'});expect(rejected.success).toBe(true);expect(engine.repo.listAgents()).toHaveLength(3);expect(engine.repo.getComputeReservation(proposalId)?.status).toBe('RELEASED');expect(local(engine,mam.id)).toBe(10_000);const delivered=(await engine.observe(mam)).nearbyOrRelevantEvents;expect(delivered.filter((event)=>event.type==='DESCENDANT_PROPOSAL_REJECTED')).toHaveLength(1);engine.close();});

  it('creates exactly one private, funded descendant with lineage and public identity-only presence',async()=>{const engine=await world(),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'parent-private.txt',content:'secret'});await engine.perform(toey.id,{type:'CREATE_TEXT_FILE',space:'SHARED',path:'culture.txt',content:'public culture'});const before=reservedTotal(engine),{proposalId}=await propose(engine),accepted=await engine.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0}),child=engine.repo.getAgent(String((accepted.effects[0] as any).child.id))!;expect(accepted.success).toBe(true);expect(reservedTotal(engine)).toBe(before);expect(engine.repo.listAgents()).toHaveLength(3);expect(child).toMatchObject({name:'Nova',generation:1,status:'active',computeCredits:0,storageBytes:0,eligibleFromTick:1});expect(engine.repo.economy.self(child.id).localCompute.total).toBe(1100);expect(engine.repo.economy.self(child.id).cognitionCredits.total).toBe(0);expect(child.parentIds).toEqual([mam.id,toey.id]);expect(engine.repo.lineageFor(child.id)).toEqual({childAgentId:child.id,parentAAgentId:mam.id,parentBAgentId:toey.id,proposalId,birthTick:0});expect(engine.repo.memoriesFor(child.id)).toHaveLength(0);expect(engine.repo.messagesFor(child.id)).toHaveLength(0);expect(engine.repo.executionsFor(child.id)).toHaveLength(0);expect(await engine.files.countFiles(child.id,'private')).toBe(0);expect(await engine.files.list(child.id,'.','shared')).toContain('culture.txt');await expect(engine.files.read(child.id,'parent-private.txt')).rejects.toThrow();expect(engine.repo.accessibleTools(child.id).every((tool)=>tool.visibility==='SHARED')).toBe(true);const self=await engine.perform(child.id,{type:'INSPECT_SELF'});expect((self.effects[0] as any).lineage.parentAAgentId).toBe(mam.id);const publicList=(await engine.perform(mam.id,{type:'LIST_INHABITANTS'})).effects[0] as any;expect(publicList.inhabitants.find((item:any)=>item.id===child.id)).toMatchObject({id:child.id,name:'Nova',generation:1,status:'active',cognitionDormant:true});const birth=engine.repo.listEvents(100).find((event)=>event.type==='DESCENDANT_CREATED')!;expect(birth.payload).toEqual({visibility:'SHARED',inhabitant:{id:child.id,name:'Nova',generation:1,status:'active'}});expect(JSON.stringify(birth)).not.toContain(mam.id);expect(engine.repo.economy.integrity()).toEqual([]);const replay=await engine.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0});expect(replay.success).toBe(false);expect(engine.repo.listAgents()).toHaveLength(3);expect(engine.repo.listEvents(100).filter((event)=>event.type==='DESCENDANT_CREATED')).toHaveLength(1);engine.close();});

  it('does not schedule a child during its birth tick and starts it on the next tick',async()=>{let toeyId='',proposalId='',calls:string[]=[];const provider=new DeterministicCognitionProvider((input:CognitionInput)=>{calls.push(`${input.currentObservation.tick}:${input.identity.name}`);if(input.currentObservation.tick===0&&input.identity.name==='Mam')return{type:'PROPOSE_DESCENDANT',coParentAgentId:toeyId,proposedName:'TickChild',localComputeContribution:550,cognitionContribution:2};if(input.currentObservation.tick===0&&input.identity.name==='Toey'){proposalId=String(input.currentObservation.nearbyOrRelevantEvents.find((event)=>event.type==='DESCENDANT_PROPOSAL_CREATED')?.summary.proposalId);return{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:2};}return{type:'WAIT',ticks:1};}),engine=await world({},provider);toeyId=engine.repo.getAgent('Toey')!.id;engine.resume();await engine.tick();expect(engine.repo.getAgent('TickChild')).not.toBeNull();expect(calls).toEqual(['0:Mam','0:Toey']);await engine.tick();expect(calls).toContain('1:TickChild');expect(proposalId).toMatch(/^[0-9a-f-]{36}$/);engine.close();});

  it('does not consume a pending proposal observation when cognition providers fail',async()=>{const failing:CognitionProvider={async think(){return{thoughtSummary:'fallback',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerRequestSucceeded:false,providerError:'test failure'}};}},engine=await world({},failing),toey=engine.repo.getAgent('Toey')!,before=engine.repo.observationCursor(toey.id);await propose(engine,'StillPending');engine.resume();await engine.tick();expect(engine.repo.observationCursor(toey.id)).toEqual(before);const dir=engine.config.dataDir;engine.close();const restarted=new WorldEngine(defaultConfig(dir));const observation=await restarted.observe(restarted.repo.getAgent(toey.id)!);expect(observation.nearbyOrRelevantEvents.filter((event)=>event.type==='DESCENDANT_PROPOSAL_CREATED')).toHaveLength(1);restarted.close();});

  it('leaves a proposal and both balances coherent when the acceptor lacks compute',async()=>{const engine=await world(),{toey,proposalId}=await propose(engine,'Underfunded'),mam=engine.repo.getAgent('Mam')!;setLocal(engine,toey.id,500,toey.storageBytes);const mamAfterReservation=local(engine,mam.id),result=await engine.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0});expect(result.success).toBe(false);expect(result.error).toMatch(/available balance/i);expect(engine.repo.getDescendantProposal(proposalId)?.status).toBe('PENDING');expect(engine.repo.getComputeReservation(proposalId)?.status).toBe('RESERVED');expect(local(engine,mam.id)).toBe(mamAfterReservation);expect(local(engine,toey.id)).toBe(500);expect(engine.repo.getAgent('Underfunded')).toBeNull();engine.close();});

  it('fails safely for insufficient resources, cancellation, and the population ceiling',async()=>{const engine=await world({maximumActiveInhabitants:2}),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;expect((await engine.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:'TooSmall',localComputeContribution:-1,cognitionContribution:0})).success).toBe(false);setLocal(engine,mam.id,500,mam.storageBytes);expect((await engine.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:'TooMuch',localComputeContribution:501,cognitionContribution:0})).success).toBe(false);setLocal(engine,mam.id,10_000,mam.storageBytes);const {proposalId}=await propose(engine,'Capped');const beforeToey=local(engine,toey.id),cap=await engine.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0});expect(cap.success).toBe(false);expect(cap.error).toMatch(/ceiling/i);expect(engine.repo.listAgents()).toHaveLength(2);expect(engine.repo.getComputeReservation(proposalId)?.status).toBe('RESERVED');expect(local(engine,toey.id)).toBe(beforeToey);const cancelled=await engine.perform(mam.id,{type:'CANCEL_DESCENDANT_PROPOSAL',proposalId});expect(cancelled.success).toBe(true);expect(engine.repo.getComputeReservation(proposalId)?.status).toBe('RELEASED');const again=await engine.perform(mam.id,{type:'CANCEL_DESCENDANT_PROPOSAL',proposalId});expect(again.success).toBe(true);expect(engine.repo.listAgents()).toHaveLength(2);engine.close();});

  it.each(['after-prepared','after-filesystem-commit','after-filesystem-journal','after-database-commit'] as DescendantTransition[])('reconciles a crash at %s without duplicate child, loss, workspace, or birth event',async(transition)=>{const initial=await world(),dir=initial.config.dataDir,mam=initial.repo.getAgent('Mam')!,toey=initial.repo.getAgent('Toey')!;const proposal=(await initial.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:`Crash-${transition}`,localComputeContribution:550,cognitionContribution:0}).then((result)=>(result.effects[0] as any).proposal));initial.close();let fired=false;const crashed=new WorldEngine(defaultConfig(dir),undefined,undefined,{}, {},{onTransition(point){if(point===transition&&!fired){fired=true;throw new InjectedCrash(point);}}});await crashed.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId:proposal.id,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0});crashed.close();const restarted=new WorldEngine(defaultConfig(dir));await restarted.initialize();const completed=restarted.repo.getDescendantProposal(proposal.id)!,child=restarted.repo.getAgent(completed.childAgentId!)!;expect(completed.status).toBe('COMPLETED');expect(restarted.repo.listAgents().filter((agent)=>agent.id===child.id)).toHaveLength(1);expect(restarted.repo.lineageFor(child.id)?.proposalId).toBe(proposal.id);expect(await restarted.files.countFiles(child.id,'private')).toBe(0);expect(restarted.repo.listEvents(200).filter((event)=>event.type==='DESCENDANT_CREATED'&&event.subjectId===child.id)).toHaveLength(1);expect(restarted.repo.incompleteDescendantOperations()).toHaveLength(0);restarted.close();});

  it('supports later generations and remains bounded and private at fifty active inhabitants',async()=>{const engine=await world({maximumActiveInhabitants:50}),mam=engine.repo.getAgent('Mam')!;setLocal(engine,mam.id,100_000,0);let current=engine.repo.getAgent('Toey')!;for(let index=2;index<50;index++){if(local(engine,current.id)<551)setLocal(engine,current.id,551,current.storageBytes);const proposal=await engine.perform(current.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:mam.id,proposedName:`Generation-${index}`,localComputeContribution:550,cognitionContribution:0}),proposalId=String((proposal.effects[0] as any).proposal.id),accepted=await engine.perform(mam.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId,response:'ACCEPT',localComputeContribution:550,cognitionContribution:0});expect(accepted.success).toBe(true);current=engine.repo.getAgent(String((accepted.effects[0] as any).child.id))!;}expect(engine.repo.listAgents()).toHaveLength(50);expect(current.generation).toBe(48);expect(engine.repo.lineageFor(current.id)?.parentAAgentId).not.toBeNull();const diagnostic=await engine.cognitionContextDiagnostic(current);expect(diagnostic.estimatedTotalInputTokens).toBeLessThanOrEqual(engine.config.cognitionInputBudgetTokens);expect((await engine.observe(current)).world.populationCount).toBe(50);expect(engine.repo.descendantProposalsFor(mam.id).length).toBe(48);expect(engine.listPublicInhabitants(current.id).every((item)=>!('metadata' in item)&&'cognitionDormant' in item)).toBe(true);engine.close();});
});
