import { mkdtemp,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll,describe,expect,it } from 'vitest';
import { DockerExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const daemonAvailable=await DockerExecutionSandbox.available(),identities=daemonAvailable?await Promise.all([DockerExecutionSandbox.verifyRuntimeImage('node'),DockerExecutionSandbox.verifyRuntimeImage('python')]):[],available=daemonAvailable&&identities.every((identity)=>identity.verified),dirs:string[]=[];
afterAll(async()=>{for(const dir of dirs)await rm(dir,{recursive:true,force:true});});
describe.skipIf(!available)('Docker execution integration',()=>{
  it('executes real Node and Python programs with actual output',async()=>{const workspace=await mkdtemp(path.join(tmpdir(),'ai-world-docker-'));dirs.push(workspace);await writeFile(path.join(workspace,'math.js'),'console.log(21 * 2);');await writeFile(path.join(workspace,'math.py'),'print(7 * 6)');const sandbox=new DockerExecutionSandbox();const node=await sandbox.execute({runtime:'node',workspacePath:workspace,entrypoint:'math.js',args:[],stdin:''}),python=await sandbox.execute({runtime:'python',workspacePath:workspace,entrypoint:'math.py',args:[],stdin:''});expect(node).toMatchObject({success:true,exitCode:0,stdout:'42\n'});expect(python).toMatchObject({success:true,exitCode:0,stdout:'42\n'});},20_000);
  it('enforces wall timeout',async()=>{const workspace=await mkdtemp(path.join(tmpdir(),'ai-world-docker-timeout-'));dirs.push(workspace);await writeFile(path.join(workspace,'forever.js'),'setInterval(() => {}, 1000);');const sandbox=new DockerExecutionSandbox({timeoutMs:500,outputBytes:1024,memory:'64m',cpus:'0.25',pids:16,stdinBytes:1024});const result=await sandbox.execute({runtime:'node',workspacePath:workspace,entrypoint:'forever.js',args:[],stdin:''});expect(result.timedOut).toBe(true);expect(result.success).toBe(false);});
  it('blocks outbound network and access to host or another inhabitant paths',async()=>{const workspace=await mkdtemp(path.join(tmpdir(),'ai-world-docker-isolation-'));dirs.push(workspace);await writeFile(path.join(workspace,'isolation.js'),`const fs=require('fs'),net=require('net');const visible=['/world.sqlite','/root/.env','/other-agent'].some(fs.existsSync);const socket=net.connect(80,'1.1.1.1');socket.on('connect',()=>{console.log(JSON.stringify({visible,network:'reached'}));process.exit(2)});socket.on('error',()=>{console.log(JSON.stringify({visible,network:'blocked'}));process.exit(0)});setTimeout(()=>{console.log(JSON.stringify({visible,network:'blocked'}));process.exit(0)},500);`);const result=await new DockerExecutionSandbox().execute({runtime:'node',workspacePath:workspace,entrypoint:'isolation.js',args:[],stdin:''});expect(result.success).toBe(true);expect(JSON.parse(result.stdout.trim())).toEqual({visible:false,network:'blocked'});});
  it('executes an immutable Toey-published tool for Mam through real Docker',async()=>{const dataDir=await mkdtemp(path.join(tmpdir(),'ai-world-docker-tool-'));dirs.push(dataDir);const engine=new WorldEngine(defaultConfig(dataDir));try{await engine.genesis();const toey=engine.repo.getAgent('Toey')!,mam=engine.repo.getAgent('Mam')!;await engine.perform(toey.id,{type:'CREATE_DIRECTORY',path:'tools/abc'});await engine.perform(toey.id,{type:'CREATE_TEXT_FILE',path:'tools/abc/main.js',content:"let raw='';process.stdin.on('data',c=>raw+=c).on('end',()=>console.log(JSON.parse(raw).value*2));"});const published=await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/abc',entrypoint:'main.js',runtime:'node',name:'abc',description:'opaque',visibility:'SHARED'}),version=(published.effects[0] as any).toolVersion,invoked=await engine.perform(mam.id,{type:'INVOKE_TOOL',toolVersionId:version.id,input:{value:21}});if(!invoked.success)throw new Error(`Real tool invocation failed: ${JSON.stringify(invoked)}`);expect((invoked.effects[0] as any).execution.stdout).toBe('42\n');}finally{engine.close();}},20_000);
});
