import { readFile,mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { configuredOwnerGateways,OwnerGatewayDispatcher } from '../packages/messaging/src/index.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { OWNER_ID } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup(sandbox=new FakeExecutionSandbox(()=>({success:true,exitCode:0,stdout:'ok',stderr:'',timedOut:false,durationMs:1,truncated:false}))){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-email-'));dirs.push(dir);const engine=new WorldEngine(defaultConfig(dir),undefined,sandbox);await engine.genesis();return engine;}
const fakeEnv={WORLD_EMAIL_ADDRESS:'world-mailbox@example.test',WORLD_EMAIL_APP_PASSWORD:'fake-app-password-never-send',WORLD_SMTP_HOST:'smtp.example.test',WORLD_SMTP_PORT:'587',WORLD_SMTP_SECURE:'false',OWNER_EMAIL_DESTINATION:'owner-destination@example.test'} satisfies NodeJS.ProcessEnv;

describe('dedicated world email identity',()=>{
  it('authenticates and sends as the world mailbox while keeping the Owner destination independent',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!,sendMail=vi.fn(async()=>({messageId:'fake-mail-id'})),factory=vi.fn(()=>({sendMail})),gateways=configuredOwnerGateways(fakeEnv,factory);await engine.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'unaltered inhabitant text'});expect(await new OwnerGatewayDispatcher(engine.repo,gateways).dispatch()).toEqual({delivered:1,failed:0});expect(factory).toHaveBeenCalledWith({host:'smtp.example.test',port:587,secure:false,auth:{user:'world-mailbox@example.test',pass:'fake-app-password-never-send'}});expect(sendMail).toHaveBeenCalledWith(expect.objectContaining({from:'AutomaticWorld <world-mailbox@example.test>',to:'owner-destination@example.test',text:`World tick: 0\nAgent: Mam\n\nunaltered inhabitant text`}));engine.close();});
  it('never places transport credentials in cognition observations or agent capabilities',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!,factory=vi.fn(()=>({sendMail:vi.fn(async()=>({}))}));configuredOwnerGateways(fakeEnv,factory);const serialized=JSON.stringify(await engine.observe(mam));expect(serialized).not.toContain(fakeEnv.WORLD_EMAIL_APP_PASSWORD);expect(serialized).not.toContain(fakeEnv.WORLD_SMTP_HOST);expect(serialized).not.toContain(fakeEnv.WORLD_EMAIL_ADDRESS);expect(serialized).not.toMatch(/SMTP|EMAIL_APP_PASSWORD/);engine.close();});
  it('never places email credentials in execution requests or container configuration',async()=>{let captured='';const sandbox=new FakeExecutionSandbox((request)=>{captured=JSON.stringify(request);return{success:true,exitCode:0,stdout:'ok',stderr:'',timedOut:false,durationMs:1,truncated:false};}),engine=await setup(sandbox),mam=engine.repo.getAgent('Mam')!;configuredOwnerGateways(fakeEnv,()=>({sendMail:vi.fn(async()=>({}))}));await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'program.js',content:'console.log("ok")'});await engine.perform(mam.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'program.js',args:[],stdin:''});expect(captured).not.toContain(fakeEnv.WORLD_EMAIL_APP_PASSWORD);expect(captured).not.toContain(fakeEnv.WORLD_EMAIL_ADDRESS);expect(captured).not.toContain('smtp.example.test');engine.close();});
  it('never copies kernel email credentials into userland snapshots',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!;configuredOwnerGateways(fakeEnv,()=>({sendMail:vi.fn(async()=>({}))}));await engine.perform(mam.id,{type:'CREATE_DIRECTORY',path:'tool'});await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'tool/main.js',content:'console.log("ordinary source")'});const published=await engine.perform(mam.id,{type:'PUBLISH_TOOL',sourceDirectory:'tool',entrypoint:'main.js',runtime:'node',name:'opaque',description:'ordinary',visibility:'PRIVATE'}),version=(published.effects[0] as any).toolVersion,stored=await readFile(path.join(engine.tools.storeRoot,version.sourceHash,'main.js'),'utf8');expect(stored).toBe('console.log("ordinary source")');expect(stored).not.toContain(fakeEnv.WORLD_EMAIL_APP_PASSWORD);expect(JSON.stringify(version.manifest)).not.toContain(fakeEnv.WORLD_EMAIL_APP_PASSWORD);engine.close();});
  it('does not expose a capability or path for requesting transport secrets',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!;const observation=await engine.observe(mam);expect(observation.kernelCapabilities.some((capability)=>/smtp|email credential|secret/i.test(`${capability.type} ${capability.description}`))).toBe(false);const read=await engine.perform(mam.id,{type:'READ_FILE',path:'../../../.env'});expect(read.success).toBe(false);expect(read.error).toMatch(/traversal/i);engine.close();});
  it('does not persist a transport error that echoes credentials',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!,gateways=configuredOwnerGateways(fakeEnv,()=>({async sendMail(){throw new Error(`authentication failed for ${fakeEnv.WORLD_EMAIL_APP_PASSWORD}`);}}));await engine.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'ordinary message'});expect(await new OwnerGatewayDispatcher(engine.repo,gateways).dispatch()).toEqual({delivered:0,failed:1});const persisted=JSON.stringify({outbox:engine.repo.listOutbox(),events:engine.repo.listEvents(),memories:engine.repo.memoriesFor(mam.id)});expect(persisted).not.toContain(fakeEnv.WORLD_EMAIL_APP_PASSWORD);expect(persisted).toContain('Email delivery failed');engine.close();});
});
