import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { ConsoleOwnerGateway,EmailOwnerGateway,LineOwnerGateway,OwnerGatewayDispatcher } from '../packages/messaging/src/index.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { OWNER_ID } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];async function setup(){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-gateway-'));dirs.push(dir);const e=new WorldEngine(defaultConfig(dir),undefined,new FakeExecutionSandbox(()=>({success:true,exitCode:0,stdout:'',stderr:'',timedOut:false,durationMs:1,truncated:false})));await e.genesis();return e;}afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
describe('durable Owner contact',()=>{
  it('queues, console-delivers, persists, and never redelivers success',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!,writes:string[]=[];const result=await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'deliberate contact'});expect(result.success).toBe(true);expect(e.repo.listOutbox()[0]).toMatchObject({status:'pending',content:'deliberate contact'});const dispatcher=new OwnerGatewayDispatcher(e.repo,[new ConsoleOwnerGateway((text)=>writes.push(text))]);expect(await dispatcher.dispatch()).toEqual({delivered:1,failed:0});expect(await dispatcher.dispatch()).toEqual({delivered:0,failed:0});expect(writes).toHaveLength(1);const dir=e.config.dataDir,outboxId=e.repo.listOutbox()[0]!.id;e.close();const r=new WorldEngine(defaultConfig(dir));expect(r.repo.listOutbox()[0]).toMatchObject({id:outboxId,status:'delivered',attempts:1});r.close();});
  it('uses readable framed email through an injected transport',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'email body'});const sendMail=vi.fn(async()=>({messageId:'mail-1'}));await new OwnerGatewayDispatcher(e.repo,[new EmailOwnerGateway({from:'world@example.test',to:'owner@example.test',transport:{sendMail}})]).dispatch();expect(sendMail).toHaveBeenCalledWith(expect.objectContaining({subject:'AutomaticWorld — Message from Mam',text:expect.stringContaining('email body'),headers:{'X-AutomaticWorld-Message-ID':e.repo.listOutbox()[0]!.id}}));e.close();});
  it('uses the official LINE push shape and stable retry key through mocked fetch',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'line body'});const fetchMock=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{void input;void init;return new Response('',{status:200,headers:{'x-line-request-id':'line-1'}});});await new OwnerGatewayDispatcher(e.repo,[new LineOwnerGateway({channelAccessToken:'secret',ownerDestinationId:'U-owner',fetcher:fetchMock as unknown as typeof fetch})]).dispatch();const init=fetchMock.mock.calls[0]![1]!,headers=init.headers as Record<string,string>;expect(fetchMock.mock.calls[0]![0]).toBe('https://api.line.me/v2/bot/message/push');expect(headers.Authorization).toBe('Bearer secret');expect(headers['X-Line-Retry-Key']).toBe(e.repo.listOutbox()[0]!.id);expect(JSON.parse(String(init.body))).toMatchObject({to:'U-owner',messages:[{type:'text'}]});e.close();});
  it('persists failures and retries once without duplicating a later success',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'retry'});let call=0;const gateway={name:'fake',deliver:async()=>{call++;if(call===1)throw new Error('offline');return{delivered:true};}};const dispatcher=new OwnerGatewayDispatcher(e.repo,[gateway]);expect(await dispatcher.dispatch()).toEqual({delivered:0,failed:1});expect(await dispatcher.dispatch()).toEqual({delivered:1,failed:0});expect(await dispatcher.dispatch()).toEqual({delivered:0,failed:0});expect(call).toBe(2);expect(e.repo.listOutbox()[0]).toMatchObject({status:'delivered',attempts:2});e.close();});
  it('does not redeliver through a gateway that already succeeded when another failed',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'multi'});let goodCalls=0,badCalls=0;const good={name:'good',deliver:async()=>{goodCalls++;return{delivered:true};}},bad={name:'bad',deliver:async()=>{badCalls++;if(badCalls===1)throw new Error('temporary');return{delivered:true};}};const dispatcher=new OwnerGatewayDispatcher(e.repo,[good,bad]);expect(await dispatcher.dispatch()).toEqual({delivered:0,failed:1});expect(await dispatcher.dispatch()).toEqual({delivered:1,failed:0});expect(goodCalls).toBe(1);expect(badCalls).toBe(2);e.close();});
  it('enforces per-agent world-hour anti-spam without losing auditability',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!;for(let i=0;i<3;i++)expect((await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:`m${i}`})).success).toBe(true);expect((await e.perform(mam.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'m3'})).success).toBe(false);expect(e.repo.listEvents()[0]?.type).toBe('ACTION_FAILED');expect(e.repo.listOutbox()).toHaveLength(3);e.close();});
});
