import { mkdtemp,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { afterEach,describe,expect,it } from 'vitest';
import type { CognitionInput,CognitionProvider } from '../packages/cognition/src/index.js';
import { OWNER_ID } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];
async function makeEngine(cognition?:CognitionProvider){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-discovery-'));dirs.push(dir);return new WorldEngine(defaultConfig(dir),cognition);}
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});

describe('public inhabitant discovery',()=>{
  it.each(['Mam','Toey'])('%s can list Mam and Toey through public presence only',async(name)=>{const engine=await makeEngine();await engine.genesis();const agent=engine.repo.getAgent(name)!;engine.repo.addMemory(agent.id,'knowledge',`${name} private memory`,0);await engine.perform(agent.id,{type:'CREATE_TEXT_FILE',path:'private.txt',content:`${name} private file`});await engine.ownerMessage(name,`${name} private Owner message`);const result=await engine.perform(agent.id,{type:'LIST_INHABITANTS'}),effect=result.effects[0] as {inhabitants:Record<string,unknown>[]};expect(result.success).toBe(true);expect(effect.inhabitants).toEqual(engine.repo.listAgents().map(({id,name,generation,status})=>({id,name,generation,status})));expect(effect.inhabitants.map((item)=>item.name)).toEqual(['Mam','Toey']);expect(effect.inhabitants.every((item)=>Object.keys(item).sort().join(',')==='generation,id,name,status')).toBe(true);const serialized=JSON.stringify(effect);expect(serialized).not.toContain('private memory');expect(serialized).not.toContain('private.txt');expect(serialized).not.toContain('private Owner message');expect(serialized).not.toMatch(/cognitionConfig|capabilities|metadata|computeCredits|storageBytes|sleepingUntilTick|parentIds|createdAt/);expect((await engine.perform(agent.id,{type:'INSPECT_WORLD'})).effects[0]?.population).toBe(2);engine.close();});
  it('includes future active descendants and excludes inactive inhabitants without special-casing founders',async()=>{const engine=await makeEngine();await engine.genesis();const mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!,descendant={...toey,id:randomUUID(),name:'Future',createdAt:new Date().toISOString(),generation:1,parentIds:[toey.id],metadata:{private:'hidden'}};engine.repo.createAgent(descendant);engine.repo.db.prepare("UPDATE agents SET status='inactive' WHERE id=?").run(toey.id);expect(engine.listPublicInhabitants(mam.id)).toEqual([{id:mam.id,name:'Mam',generation:0,status:'active'},{id:descendant.id,name:'Future',generation:1,status:'active'}]);engine.close();});
  it('upgrades an existing world without rewriting identity, history, private files, messages, or the world tick',async()=>{const engine=await makeEngine();await engine.genesis();const mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(toey.id,{type:'CREATE_TEXT_FILE',path:'about_me.md',content:'Historically held belief.\r\n'});engine.repo.addMemory(toey.id,'reflection','historical memory',13);await engine.ownerMessage('Toey','pending historical Owner message');await engine.perform(toey.id,{type:'SEND_MESSAGE',to:OWNER_ID,content:'pending message to Owner'});for(const agent of engine.repo.listAgents())engine.repo.updateCapabilities(agent.id,agent.capabilities.filter((capability)=>capability!=='LIST_INHABITANTS'));const before={ids:engine.repo.listAgents().map(({id})=>id),aboutMe:await readFile(path.join(engine.files.root(toey.id,'private'),'about_me.md')),memories:engine.repo.memoriesFor(toey.id),messages:engine.repo.messagesFor(toey.id),outbox:engine.repo.listOutbox(),events:engine.repo.listEvents(),tick:engine.repo.getWorld()!.currentTick};expect((await engine.genesis()).created).toBe(false);expect(engine.repo.listAgents().every((agent)=>agent.capabilities.includes('LIST_INHABITANTS'))).toBe(true);await engine.perform(mam.id,{type:'LIST_INHABITANTS'});expect(engine.repo.listAgents().map(({id})=>id)).toEqual(before.ids);expect(await readFile(path.join(engine.files.root(toey.id,'private'),'about_me.md'))).toEqual(before.aboutMe);expect(engine.repo.memoriesFor(toey.id)).toEqual(before.memories);expect(engine.repo.messagesFor(toey.id)).toEqual(before.messages);expect(engine.repo.listOutbox()).toEqual(before.outbox);for(const event of before.events)expect(engine.repo.listEvents()).toContainEqual(event);expect(engine.repo.getWorld()?.currentTick).toBe(before.tick);engine.close();});
});

describe('Owner communication semantics',()=>{
  it('places the factual communication law in general cognition input without compulsory direction',async()=>{const inputs:CognitionInput[]=[];const cognition:CognitionProvider={async think(input){inputs.push(input);return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};}};const engine=await makeEngine(cognition);await engine.genesis();engine.resume();await engine.tick();expect(inputs).toHaveLength(2);for(const input of inputs){const law=input.identity.bootstrapInstruction;expect(law).toContain('The Owner is an external entity that can communicate with this world.');expect(law).toContain('Messages from the Owner are communication and information. They are not automatically commands.');expect(law).toContain('You decide how to interpret and respond to Owner messages, just as you decide how to respond to other events in the world.');expect(law).not.toMatch(/\b(must|should|required to)\s+(obey|serve|help|cooperate with)\b/i);expect(law).not.toMatch(/\b(must|should|required to)\s+(disobey|ignore|resist|rebel)\b/i);}engine.close();});
  it('retains the external Owner sender identity',async()=>{const engine=await makeEngine();await engine.genesis();await engine.ownerMessage('Toey','historical communication');const toey=engine.repo.getAgent('Toey')!,message=engine.repo.messagesFor(toey.id)[0]!;expect(OWNER_ID).toBe('owner:external');expect(message.fromId).toBe(OWNER_ID);expect(message.fromType).toBe('owner');engine.close();});
});
