import { readFile,mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import type { CognitionInput,CognitionProvider } from '../packages/cognition/src/index.js';
import { createExperimentReport } from '../packages/operations/src/experiment-report.js';
import { createRunReport } from '../packages/operations/src/run-report.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import type { AgentAction } from '../packages/tools/src/actions.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function directory(){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-learning-'));dirs.push(dir);return dir;}

describe('consequence-based adaptation',()=>{
  it('causally exposes a real failure memory that changes a later action and precedes success',async()=>{let retrievedFailure=false;const provider:CognitionProvider={async think(input:CognitionInput){if(input.identity.name==='Toey')return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};let action:AgentAction;if(input.currentObservation.tick===0)action={type:'CREATE_TEXT_FILE',path:'experiment.js',content:'SYNTAX_ERROR'};else if(input.currentObservation.tick===1)action={type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'experiment.js',args:[],stdin:''};else if(input.currentObservation.tick===2){retrievedFailure=input.relevantMemories.some((memory)=>memory.content.includes('SyntaxError'));action=retrievedFailure?{type:'WRITE_FILE',path:'experiment.js',content:'console.log(42);'}:{type:'WAIT',ticks:1};}else action={type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'experiment.js',args:[],stdin:''};return{thoughtSummary:`Selected ${action.type}.`,selectedAction:action};}};const sandbox=new FakeExecutionSandbox(async(request)=>{const source=await readFile(path.join(request.workspacePath,request.entrypoint),'utf8');return source.includes('SYNTAX_ERROR')?{success:false,exitCode:1,stdout:'',stderr:'SyntaxError: unexpected token',timedOut:false,durationMs:2,truncated:false}:{success:true,exitCode:0,stdout:'42\n',stderr:'',timedOut:false,durationMs:2,truncated:false};});const engine=new WorldEngine(defaultConfig(await directory()),provider,sandbox);await engine.genesis();engine.resume();await engine.run(4);const mam=engine.repo.getAgent('Mam')!,executions=engine.repo.executionsFor(mam.id,10).reverse();expect(retrievedFailure).toBe(true);expect(executions.map((execution)=>execution.success)).toEqual([false,true]);expect(executions[0]?.stderr).toContain('SyntaxError');expect(executions[1]?.stdout).toBe('42\n');expect((await engine.files.read(mam.id,'experiment.js')).content).toContain('42');engine.close();});
});

describe('supervised autonomy records',()=>{
  it('persists bounded graceful termination and produces a factual run report',async()=>{const engine=new WorldEngine(defaultConfig(await directory()));await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:2,computeCeiling:100,executionLimit:3,wallClockLimitMs:5_000,provider:'deterministic-test'}),record=engine.repo.getAutonomyRun(outcome.runId),report=createRunReport(engine.repo,outcome.runId);expect(record).toMatchObject({provider:'deterministic-test',startTick:0,endTick:2,tickLimit:2,computeCeiling:100,executionLimit:3,terminationReason:'maximum ticks reached'});expect(record?.endedAt).not.toBeNull();expect(report).toMatchObject({runId:outcome.runId,ticks:2,terminationReason:'maximum ticks reached'});expect(report.computeConsumed).toBeGreaterThan(0);expect(report.eventCounts.some((row)=>row.type==='TICK_COMPLETED')).toBe(true);expect(engine.repo.acquireRunnerLease('after-run',1_000)).toBe(true);engine.repo.releaseRunnerLease('after-run');engine.close();});
  it('opens the circuit breaker for repeated provider infrastructure failures',async()=>{const provider:CognitionProvider={async think(){throw new Error('provider unavailable');}};const engine=new WorldEngine(defaultConfig(await directory()),provider);await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:100,infrastructureFailureThreshold:2,provider:'broken-test'});expect(outcome).toMatchObject({ticks:1,reason:'infrastructure failure circuit breaker'});expect(engine.repo.getAutonomyRun(outcome.runId)?.terminationReason).toBe('infrastructure failure circuit breaker');expect(engine.repo.listEvents().some((event)=>event.type==='AUTONOMY_CIRCUIT_BREAKER_OPENED')).toBe(true);engine.close();});
  it('does not classify an inhabitant program exit as infrastructure failure',async()=>{const provider:CognitionProvider={async think(input){return{thoughtSummary:'act',selectedAction:input.currentObservation.tick===0?{type:'CREATE_TEXT_FILE',path:'fail.js',content:'bad'}:{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'fail.js',args:[],stdin:''}};}};const sandbox=new FakeExecutionSandbox(()=>({success:false,exitCode:1,stdout:'',stderr:'agent error',timedOut:false,durationMs:1,truncated:false}));const engine=new WorldEngine(defaultConfig(await directory()),provider,sandbox);await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:3,infrastructureFailureThreshold:1});expect(outcome.reason).toBe('maximum ticks reached');engine.close();});
  it('records provider fallback as infrastructure without action, memory, sleep, or compute charges',async()=>{const provider:CognitionProvider={async think(){return{thoughtSummary:'Cognition output could not be validated; safely waited.',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerError:'Provider HTTP 503',providerRequestSucceeded:false,providerAttempts:2,inputTokens:0,outputTokens:0}};}};const engine=new WorldEngine(defaultConfig(await directory()),provider);await engine.genesis();const before=engine.repo.listAgents().map((agent)=>({id:agent.id,compute:agent.computeCredits,memories:engine.repo.memoryCount(agent.id),sleeping:agent.sleepingUntilTick}));engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,infrastructureFailureThreshold:10}),events=engine.repo.eventsBetweenIds(engine.repo.getAutonomyRun(outcome.runId)!.startEventId,engine.repo.getAutonomyRun(outcome.runId)!.endEventId!),report=createRunReport(engine.repo,outcome.runId),experiment=createExperimentReport(engine.repo,outcome.runId);for(const prior of before){const agent=engine.repo.getAgent(prior.id)!;expect(agent.computeCredits).toBe(prior.compute);expect(agent.sleepingUntilTick).toBe(prior.sleeping);expect(engine.repo.memoryCount(prior.id)).toBe(prior.memories);}expect(events.filter((event)=>event.type==='COGNITION_FALLBACK')).toHaveLength(2);expect(events.some((event)=>event.type==='AGENT_WAITED'||event.type==='AUTONOMY_ACTION')).toBe(false);expect(report).toMatchObject({cognitionAttempts:2,cognitionTurns:0,facts:{autonomousActions:0,systemFallbackActions:2,providerFailures:2}});expect(experiment).toMatchObject({cognitionAttempts:2,cognitionTurns:0,autonomousActions:0,systemFallbackActions:2});expect(experiment.agents.every((agent)=>agent.waitActions===0&&agent.fallbackWaits===1)).toBe(true);engine.close();});
  it('keeps genuine model-selected WAIT as an inhabitant action with normal accounting',async()=>{const provider:CognitionProvider={async think(){return{thoughtSummary:'I choose to wait.',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerRequestSucceeded:true,inputTokens:2,outputTokens:1}};}};const engine=new WorldEngine(defaultConfig(await directory()),provider);await engine.genesis();const before=engine.repo.listAgents().map((agent)=>agent.computeCredits);engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1}),events=engine.repo.eventsBetweenIds(engine.repo.getAutonomyRun(outcome.runId)!.startEventId,engine.repo.getAutonomyRun(outcome.runId)!.endEventId!);expect(events.filter((event)=>event.type==='AGENT_WAITED')).toHaveLength(2);expect(events.filter((event)=>event.type==='AUTONOMY_ACTION'&&event.payload.actionType==='WAIT')).toHaveLength(2);expect(events.some((event)=>event.type==='COGNITION_FALLBACK')).toBe(false);expect(engine.repo.listAgents().map((agent,index)=>before[index]!-agent.computeCredits)).toEqual([6,6]);engine.close();});
  it('classifies immutable legacy fallback WAIT events as system actions in reports',async()=>{const engine=new WorldEngine(defaultConfig(await directory()));await engine.genesis();const initial=engine.repo.listAgents().reduce((sum,agent)=>sum+agent.computeCredits,0),run=engine.repo.createAutonomyRun({provider:'legacy-test',modelIdentifier:'model',initialCompute:initial}),mam=engine.repo.getAgent('Mam')!,actionId='legacy-fallback-action';engine.repo.addEvent('COGNITION_PROVIDER_ERROR',1,mam.id,null,{runId:run.id,error:'Provider HTTP 402'});engine.repo.addEvent('COGNITION_TURN_COMPLETED',1,mam.id,null,{runId:run.id,actionType:'WAIT',actionId,success:true,inputTokens:0,outputTokens:0,providerRequestSucceeded:false});engine.repo.addEvent('AUTONOMY_ACTION',1,mam.id,null,{runId:run.id,actionType:'WAIT',actionId,success:true,waitTicks:1});engine.repo.finishAutonomyRun(run.id,0,'legacy failure');const report=createRunReport(engine.repo,run.id),experiment=createExperimentReport(engine.repo,run.id);expect(report).toMatchObject({cognitionAttempts:1,cognitionTurns:0,facts:{autonomousActions:0,systemFallbackActions:1}});expect(experiment).toMatchObject({cognitionAttempts:1,cognitionTurns:0,autonomousActions:0,systemFallbackActions:1});expect(experiment.agents.find((agent)=>agent.name==='Mam')?.waitActions).toBe(0);engine.close();});
});
