import { readFile,mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import type { CognitionInput,CognitionProvider } from '../packages/cognition/src/index.js';
import { createRunReport } from '../packages/operations/src/run-report.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import type { AgentAction } from '../packages/tools/src/actions.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function directory(){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-learning-'));dirs.push(dir);return dir;}

describe('consequence-based adaptation',()=>{
  it('causally exposes a real failure memory that changes a later action and precedes success',async()=>{let retrievedFailure=false;const provider:CognitionProvider={async think(input:CognitionInput){if(input.identity.name==='Toey')return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};let action:AgentAction;if(input.currentObservation.tick===0)action={type:'CREATE_TEXT_FILE',path:'experiment.js',content:'SYNTAX_ERROR'};else if(input.currentObservation.tick===1)action={type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'experiment.js',args:[],stdin:''};else if(input.currentObservation.tick===2){retrievedFailure=input.relevantMemories.some((memory)=>memory.content.includes('SyntaxError'));action=retrievedFailure?{type:'WRITE_FILE',path:'experiment.js',content:'console.log(42);'}:{type:'WAIT',ticks:1};}else action={type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'experiment.js',args:[],stdin:''};return{thoughtSummary:`Selected ${action.type}.`,selectedAction:action};}};const sandbox=new FakeExecutionSandbox(async(request)=>{const source=await readFile(path.join(request.workspacePath,request.entrypoint),'utf8');return source.includes('SYNTAX_ERROR')?{success:false,exitCode:1,stdout:'',stderr:'SyntaxError: unexpected token',timedOut:false,durationMs:2,truncated:false}:{success:true,exitCode:0,stdout:'42\n',stderr:'',timedOut:false,durationMs:2,truncated:false};});const engine=new WorldEngine(defaultConfig(await directory()),provider,sandbox);await engine.genesis();engine.resume();await engine.run(4);const mam=engine.repo.getAgent('Mam')!,executions=engine.repo.executionsFor(mam.id,10).reverse();expect(retrievedFailure).toBe(true);expect(executions.map((execution)=>execution.success)).toEqual([false,true]);expect(executions[0]?.stderr).toContain('SyntaxError');expect(executions[1]?.stdout).toBe('42\n');expect((await engine.files.read(mam.id,'experiment.js')).content).toContain('42');engine.close();});
});

describe('supervised autonomy records',()=>{
  it('persists bounded graceful termination and produces a factual run report',async()=>{const engine=new WorldEngine(defaultConfig(await directory()));await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:2,computeCeiling:100,executionLimit:3,wallClockLimitMs:5_000,provider:'deterministic-test'}),record=engine.repo.getAutonomyRun(outcome.runId),report=createRunReport(engine.repo,outcome.runId);expect(record).toMatchObject({provider:'deterministic-test',startTick:0,endTick:2,tickLimit:2,computeCeiling:100,executionLimit:3,terminationReason:'maximum ticks reached'});expect(record?.endedAt).not.toBeNull();expect(report).toMatchObject({runId:outcome.runId,ticks:2,terminationReason:'maximum ticks reached'});expect(report.computeConsumed).toBeGreaterThan(0);expect(report.eventCounts.some((row)=>row.type==='TICK_COMPLETED')).toBe(true);expect(engine.repo.acquireRunnerLease('after-run',1_000)).toBe(true);engine.repo.releaseRunnerLease('after-run');engine.close();});
  it('opens the circuit breaker for repeated provider infrastructure failures',async()=>{const provider:CognitionProvider={async think(){throw new Error('provider unavailable');}};const engine=new WorldEngine(defaultConfig(await directory()),provider);await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:100,infrastructureFailureThreshold:2,provider:'broken-test'});expect(outcome).toMatchObject({ticks:1,reason:'infrastructure failure circuit breaker'});expect(engine.repo.getAutonomyRun(outcome.runId)?.terminationReason).toBe('infrastructure failure circuit breaker');expect(engine.repo.listEvents().some((event)=>event.type==='AUTONOMY_CIRCUIT_BREAKER_OPENED')).toBe(true);engine.close();});
  it('does not classify an inhabitant program exit as infrastructure failure',async()=>{const provider:CognitionProvider={async think(input){return{thoughtSummary:'act',selectedAction:input.currentObservation.tick===0?{type:'CREATE_TEXT_FILE',path:'fail.js',content:'bad'}:{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'fail.js',args:[],stdin:''}};}};const sandbox=new FakeExecutionSandbox(()=>({success:false,exitCode:1,stdout:'',stderr:'agent error',timedOut:false,durationMs:1,truncated:false}));const engine=new WorldEngine(defaultConfig(await directory()),provider,sandbox);await engine.genesis();engine.resume();const outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:3,infrastructureFailureThreshold:1});expect(outcome.reason).toBe('maximum ticks reached');engine.close();});
});
