import Database from 'better-sqlite3';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { WorldRepository } from '../packages/persistence/src/repository.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
describe('in-place Milestone 3 schema migration',()=>{
  it('adds new tables without replacing founders or historical events',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ai-world-migration-'));dirs.push(dir);const original=new WorldEngine(defaultConfig(dir));const genesis=await original.genesis(),ids=genesis.agents.map((agent)=>agent.id),eventUid=original.repo.listEvents(1)[0]?.eventUid;original.close();const dbPath=path.join(dir,'world.sqlite'),legacy=new Database(dbPath);legacy.exec('DROP TABLE IF EXISTS tool_invocations; DROP TABLE IF EXISTS tool_versions; DROP TABLE IF EXISTS tools; DROP TABLE IF EXISTS filesystem_operations; DROP TABLE IF EXISTS owner_ingress; DROP TABLE IF EXISTS autonomy_runs; DROP TABLE IF EXISTS checkpoints;');legacy.close();const migrated=new WorldEngine(defaultConfig(dir));await migrated.genesis();expect(migrated.repo.listAgents().map((agent)=>agent.id)).toEqual(ids);expect(migrated.repo.listAgents()).toHaveLength(2);expect(migrated.repo.listEvents(100).some((event)=>event.eventUid===eventUid)).toBe(true);const tables=(migrated.repo.db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all() as {name:string}[]).map((row)=>row.name);expect(tables).toEqual(expect.arrayContaining(['tools','tool_versions','tool_invocations','filesystem_operations','owner_ingress','autonomy_runs','checkpoints']));migrated.close();});
  it('adds run-label and live-limit columns before indexing a legacy autonomy table',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ai-world-legacy-run-'));dirs.push(dir);const dbPath=path.join(dir,'world.sqlite'),legacy=new Database(dbPath);legacy.exec('CREATE TABLE autonomy_runs (id TEXT PRIMARY KEY, started_at TEXT NOT NULL, ended_at TEXT, start_tick INTEGER NOT NULL, end_tick INTEGER, provider TEXT NOT NULL, initial_compute INTEGER NOT NULL, compute_ceiling INTEGER, tick_limit INTEGER, execution_limit INTEGER, wall_clock_limit_ms INTEGER, termination_reason TEXT)');legacy.close();const migrated=new WorldRepository(dbPath),columns=(migrated.db.prepare('PRAGMA table_info(autonomy_runs)').all() as {name:string}[]).map((row)=>row.name);expect(columns).toEqual(expect.arrayContaining(['label','model_identifier','preflight','postflight','cognition_turn_limit','input_token_limit','output_token_limit']));expect((migrated.db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='idx_autonomy_runs_label'").get() as {name:string}).name).toBe('idx_autonomy_runs_label');migrated.close();});
});
