import Database from 'better-sqlite3';
import { mkdtemp,readFile,rm,stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import type { CognitionProvider } from '../packages/cognition/src/index.js';
import { OpenAICompatibleCognitionProvider } from '../packages/cognition/src/index.js';
import { WorldCheckpointService } from '../packages/operations/src/checkpoint.js';
import { createExperimentReport } from '../packages/operations/src/experiment-report.js';
import { LiveReadinessDoctor } from '../packages/operations/src/live-doctor.js';
import type { SandboxDoctor } from '../packages/operations/src/doctor.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup(provider?:CognitionProvider){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-m4-'));dirs.push(dir,`${dir}-checkpoints`);const engine=new WorldEngine(defaultConfig(dir),provider);await engine.genesis();return engine;}
const sandboxReport={operationallyVerified:true,checks:[],runtimeIdentity:[]} as const;

describe('Milestone 4 live readiness and recovery',()=>{
  it('checks live readiness without exposing credentials or spending inference tokens',async()=>{const engine=await setup();engine.resume();const agents=engine.repo.listAgents(),founders=Object.fromEntries(agents.map((agent)=>[agent.name,agent.id])),sandbox={verify:vi.fn(async()=>sandboxReport)} as unknown as SandboxDoctor,provider={verifyConnectivity:vi.fn(async()=>({configured:true,provider:'openai-compatible',modelIdentifier:'model-test',connected:true}))} as unknown as OpenAICompatibleCognitionProvider,env={COGNITION_PROVIDER:'openai',OPENAI_API_KEY:'fake-never-print',OPENAI_MODEL:'model-test'};const report=await new LiveReadinessDoctor(engine,sandbox,provider,env,founders).verify({live:true});expect(report.readyForLiveExperiment).toBe(true);expect(provider.verifyConnectivity).toHaveBeenCalledOnce();expect(JSON.stringify(report)).not.toContain('fake-never-print');expect(report.checks).toEqual(expect.arrayContaining([expect.objectContaining({name:'Population',passed:true}),expect.objectContaining({name:'Runner lease',passed:true}),expect.objectContaining({name:'Operation reconciliation',passed:true})]));engine.close();});
  it('creates a consistent Owner-only checkpoint containing database, artifacts, tool store, and hashes',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!;await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'before.txt',content:'checkpoint content'});await engine.perform(mam.id,{type:'CREATE_DIRECTORY',path:'tool'});await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'tool/main.js',content:'console.log(1)'});await engine.perform(mam.id,{type:'PUBLISH_TOOL',sourceDirectory:'tool',entrypoint:'main.js',runtime:'node',name:'checkpoint-tool',description:'test',visibility:'PRIVATE'});const record=await new WorldCheckpointService(engine.config.dataDir,engine.repo).create('before-live');expect(record).toMatchObject({label:'before-live',tick:0,databaseHash:expect.stringMatching(/^[a-f0-9]{64}$/),artifactHash:expect.stringMatching(/^[a-f0-9]{64}$/)});expect((await stat(path.join(record.backupPath,'world.sqlite'))).isFile()).toBe(true);expect(await readFile(path.join(record.backupPath,'agents',mam.id,'workspace','before.txt'),'utf8')).toBe('checkpoint content');expect((await stat(path.join(record.backupPath,'system','tool-store'))).isDirectory()).toBe(true);const backup=new Database(path.join(record.backupPath,'world.sqlite'),{readonly:true});expect(backup.pragma('integrity_check',{simple:true})).toBe('ok');backup.close();expect(engine.repo.listCheckpoints()[0]?.id).toBe(record.id);engine.close();});
});

describe('Milestone 4 bounded run evidence',()=>{
  it('persists pre/postflight, run attribution, provider usage, token limits, and stagnation facts',async()=>{const provider:CognitionProvider={async think(){return{thoughtSummary:'I will wait.',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{inputTokens:7,outputTokens:3,providerLatencyMs:12,providerRequestSucceeded:true}};}};const engine=await setup(provider),mam=engine.repo.getAgent('Mam')!;await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'existing.txt',content:'persist'});engine.resume();const result=await new ContinuousWorldRunner(engine).run({tickMs:0,label:'bounded-test',maxTicks:10,maxInputTokens:10,maxOutputTokens:100,maxCognitionTurns:20,computeCeiling:100,executionLimit:2,wallClockLimitMs:5_000,provider:'fake-live',modelIdentifier:'model-test'}),run=engine.repo.getAutonomyRun('bounded-test')!,events=engine.repo.eventsBetweenIds(run.startEventId,run.endEventId!),report=createExperimentReport(engine.repo,'bounded-test');expect(result.reason).toBe('provider input-token limit reached');expect(run.preflight).toMatchObject({startTick:0,modelIdentifier:'model-test',worldStatus:'running'});expect(run.preflight?.agents.find((agent)=>agent.name==='Mam')?.privateFileCount).toBe(1);expect(run.postflight).not.toBeNull();expect(events.filter((event)=>event.type==='AUTONOMY_ACTION')).toHaveLength(2);expect(events.filter((event)=>event.type==='AUTONOMY_ACTION').every((event)=>event.payload.runId===run.id)).toBe(true);expect(report).toMatchObject({inputTokens:14,outputTokens:6,terminationReason:'provider input-token limit reached'});expect(report.agents.every((agent)=>agent.waitActions===1&&agent.longestWaitOnlySequence===1&&agent.noArtifactChangeTurns===1)).toBe(true);expect(engine.repo.runnerLeaseStatus().present).toBe(false);engine.close();});
  it('sanitizes provider failures so API keys cannot enter persisted errors',async()=>{const secret='fake-api-key-never-persist',fetcher=vi.fn(async()=>{throw new Error(`request failed with ${secret}`);}) as unknown as typeof fetch,provider=new OpenAICompatibleCognitionProvider({apiKey:secret,model:'model-test',fetcher,maxRetries:0}),engine=await setup(provider);engine.resume();await engine.tick('run-test');const persisted=JSON.stringify(engine.repo.listEvents(100));expect(persisted).not.toContain(secret);expect(persisted).toContain('Provider request or response validation failed');engine.close();});
});
