import { describe,expect,it,vi } from 'vitest';
import { mkdtemp,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { BOOTSTRAP_INSTRUCTION } from '../packages/shared/src/index.js';
import { configuredCognitionProvider,type CognitionInput } from '../packages/cognition/src/index.js';
import { LiveReadinessDoctor } from '../packages/operations/src/live-doctor.js';
import { SandboxDoctor } from '../packages/operations/src/doctor.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const env={COGNITION_PROVIDER:'opencode-zen',OPENCODE_ZEN_API_KEY:'zen-test-secret',OPENCODE_ZEN_MODEL:'space-bunny-free'};
const input={identity:{id:'mam',name:'Mam',bootstrapInstruction:'private identity'},currentObservation:{tick:185,world:{status:'running' as const,populationCount:2,simulatedTime:'2026-01-01'},self:{} as never,nearbyOrRelevantEvents:[],privateArtifacts:[],sharedArtifacts:[],workingArtifacts:[],newlyDeliveredMessages:[],recentPeerConversation:[],recentExecutions:[],accessibleResources:{computeCredits:8493,storageBytes:24472},kernelCapabilities:[],userlandTools:[],contextDelivery:{newObservationEventIds:[],newMessageIds:[],actionResultIds:[],sharedConsequenceIds:[],continuityEventIds:[],truncations:[]}},relevantMemories:[],availableActions:[]} satisfies CognitionInput;
const complete=(extra:Record<string,unknown>={})=>({choices:[{message:{content:JSON.stringify({thoughtSummary:'Wait.',selectedAction:{type:'WAIT',ticks:1}}),reasoning_content:'hidden reasoning'},finish_reason:null}],usage:{prompt_tokens:81,completion_tokens:13,total_tokens:94,completion_tokens_details:{reasoning_tokens:7}},...extra});
const json=(value:unknown,status=200,headers?:HeadersInit)=>new Response(JSON.stringify(value),{status,...(headers?{headers}:{})});

describe('OpenCode Zen adapter',()=>{
  it('uses the exact Zen endpoint, model and existing prompt; keeps usage and drops reasoning',async()=>{const calls:Array<{url:string;init:RequestInit}>=[];const fetcher=vi.fn(async(url:string,init:RequestInit)=>{calls.push({url,init});return init.method==='GET'?json({data:[{id:'space-bunny-free'}]}):json(complete());}) as unknown as typeof fetch;const selection=configuredCognitionProvider(env,fetcher),provider=selection.provider!;expect(await provider.verifyConnectivity()).toMatchObject({provider:'opencode-zen',endpointIdentity:'OpenCode Zen',connected:true,modelAvailable:true,inferenceVerified:false});const result=await provider.think(input);expect(calls.map((call)=>call.url)).toEqual(['https://opencode.ai/zen/v1/models','https://opencode.ai/zen/v1/chat/completions']);expect(calls.every((call)=>(call.init.headers as Record<string,string>).Authorization==='Bearer zen-test-secret')).toBe(true);const body=JSON.parse(String(calls[1]!.init.body));expect(body.model).toBe('space-bunny-free');expect(body.messages[0].content).toContain(BOOTSTRAP_INSTRUCTION);expect(body.messages[1].content).toContain('Mam');expect(body.messages[1].content).not.toContain('private identity');expect(result.reasoningMetadata).toMatchObject({inputTokens:81,outputTokens:13,usage:{prompt_tokens:81,completion_tokens:13,total_tokens:94}});expect(JSON.stringify(result)).not.toContain('hidden reasoning');expect(JSON.stringify(result)).not.toContain('reasoning_tokens');});

  it('checks model visibility without inference and reports absence',async()=>{const fetcher=vi.fn(async(...args:[string,RequestInit])=>{expect(args[0]).toBe('https://opencode.ai/zen/v1/models');return json({data:[{id:'other-model'}]});});const readiness=await configuredCognitionProvider(env,fetcher as unknown as typeof fetch).provider!.verifyConnectivity();expect(readiness).toMatchObject({connected:true,modelAvailable:false,inferenceVerified:false});expect(fetcher).toHaveBeenCalledOnce();expect(fetcher.mock.calls[0]![1]).toMatchObject({method:'GET'});});

  it.each([[429,true],[401,false],[403,false],[404,false],[503,true]] as const)('classifies HTTP %i correctly',async(status,retryable)=>{const fetcher=vi.fn(async()=>json({error:{code:`code-${status}`,type:'upstream',message:'Bearer zen-test-secret'}},status,{'retry-after':'1'})) as unknown as typeof fetch;const result=await configuredCognitionProvider(env,fetcher).provider!.think(input,{suspendHttp429:true});expect(result.reasoningMetadata?.providerFailure).toMatchObject({phase:'http',httpStatus:status,code:`code-${status}`,retryable});expect(result.reasoningMetadata?.providerRequestSucceeded).toBe(false);expect(JSON.stringify(result)).not.toContain('zen-test-secret');});

  it.each([
    ['malformed JSON','{broken','response_parse'],
    ['empty choices',{choices:[]},'response_schema'],
    ['truncated action',{choices:[{message:{content:'{"thoughtSummary":'}}]},'response_parse'],
    ['invalid cognition',{choices:[{message:{content:JSON.stringify({thoughtSummary:'wait',selectedAction:{type:'INVALID'}})}}]},'response_schema'],
  ])('rejects %s safely',async(_name,body,phase)=>{const fetcher=vi.fn(async()=>typeof body==='string'?new Response(body):json(body)) as unknown as typeof fetch;const result=await configuredCognitionProvider(env,fetcher).provider!.think(input);expect(result.reasoningMetadata?.providerFailure).toMatchObject({phase});expect(result.reasoningMetadata?.providerRequestSucceeded).toBe(false);});

  it('never sends a key when configuration is incomplete',async()=>{const fetcher=vi.fn(),provider=configuredCognitionProvider({COGNITION_PROVIDER:'opencode-zen'},fetcher as unknown as typeof fetch).provider!;expect((await provider.verifyConnectivity()).configured).toBe(false);expect(fetcher).not.toHaveBeenCalled();});

  it('accepts a completion without usage while marking upstream usage unknown',async()=>{const fetcher=vi.fn(async()=>json(complete({usage:undefined,reasoning:'private',unexpected:{opaque:true}}))) as unknown as typeof fetch;const result=await configuredCognitionProvider(env,fetcher).provider!.think(input);expect(result.reasoningMetadata).toMatchObject({inputTokens:0,outputTokens:0,providerRequestSucceeded:true,providerUsageAvailable:false});expect(JSON.stringify(result)).not.toMatch(/private|opaque/);});

  it('redacts an echoed Zen key even in structured provider error fields',async()=>{const fetcher=vi.fn(async()=>json({error:{code:`blocked-${env.OPENCODE_ZEN_API_KEY}`,type:env.OPENCODE_ZEN_API_KEY}},401)) as unknown as typeof fetch;const result=await configuredCognitionProvider(env,fetcher).provider!.think(input);expect(JSON.stringify(result)).not.toContain(env.OPENCODE_ZEN_API_KEY);expect(result.reasoningMetadata?.providerFailure).toMatchObject({phase:'http',httpStatus:401,retryable:false});});

  it('reports model visibility and scans world data for the Zen secret',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'aw-zen-doctor-'));const fetcher=vi.fn(async()=>json({data:[{id:'space-bunny-free'}]})) as unknown as typeof fetch,provider=configuredCognitionProvider(env,fetcher).provider!,engine=new WorldEngine(defaultConfig(dir));try{await engine.genesis();const founders=Object.fromEntries(engine.repo.listAgents().map((agent)=>[agent.name,agent.id])),sandbox={verify:vi.fn(async()=>({operationallyVerified:true,checks:[],runtimeIdentity:[]}))} as unknown as SandboxDoctor,doctor=new LiveReadinessDoctor(engine,sandbox,provider,env,founders);const report=await doctor.verify({live:true});expect(report.checks).toEqual(expect.arrayContaining([expect.objectContaining({name:'Configured model availability',passed:true,detail:'space-bunny-free found'}),expect.objectContaining({name:'Secret isolation',passed:true})]));expect(JSON.stringify(report)).not.toContain(env.OPENCODE_ZEN_API_KEY);await writeFile(path.join(dir,'fake-secret-leak.txt'),env.OPENCODE_ZEN_API_KEY);const leaked=await doctor.verify({live:true});expect(leaked.checks).toContainEqual(expect.objectContaining({name:'Secret isolation',passed:false}));}finally{engine.close();await rm(dir,{recursive:true,force:true});}});
});
