import { createServer,type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { configuredCognitionProvider,OpenAICompatibleCognitionProvider,type CognitionInput } from '../packages/cognition/src/index.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

interface CapturedRequest{url:string;headers:Record<string,string|string[]|undefined>;body:string;}
const servers:Server[]=[],dirs:string[]=[];
afterEach(async()=>{await Promise.all(servers.splice(0).map((server)=>new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()))));for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
const input={identity:{id:'a',name:'Mam',bootstrapInstruction:'You exist.'},currentObservation:{tick:1,world:{status:'running' as const,populationCount:1,simulatedTime:'2026-01-01T00:00:00.000Z'},self:{} as never,nearbyOrRelevantEvents:[],privateArtifacts:[],sharedArtifacts:[],workingArtifacts:[],newlyDeliveredMessages:[],recentExecutions:[],accessibleResources:{computeCredits:1,storageBytes:0},kernelCapabilities:[],userlandTools:[],contextDelivery:{newObservationEventIds:[],newMessageIds:[],actionResultIds:[],sharedConsequenceIds:[],continuityEventIds:[],truncations:[]}},relevantMemories:[],availableActions:[]} satisfies CognitionInput;
const validBody={choices:[{message:{content:JSON.stringify({thoughtSummary:'I will wait.',selectedAction:{type:'WAIT',ticks:1}})}}],usage:{prompt_tokens:4,completion_tokens:2}};
const response=(body:unknown,status=200)=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':'application/json'}});

async function mockProviderServer(status=200){const requests:CapturedRequest[]=[];const server=createServer((request,response)=>{const chunks:Buffer[]=[];request.on('data',(chunk:Buffer)=>chunks.push(chunk));request.on('end',()=>{requests.push({url:request.url??'',headers:request.headers,body:Buffer.concat(chunks).toString('utf8')});response.writeHead(status,{'content-type':'application/json'});response.end(JSON.stringify(request.url?.endsWith('/chat/completions')?validBody:{data:{label:'not-inspected'}}));});});servers.push(server);await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const address=server.address() as AddressInfo;return{baseUrl:`http://127.0.0.1:${address.port}/api/v1`,requests};}

describe('first-class OpenRouter cognition provider',()=>{
  it('sends the fake OpenRouter key and exact model slug only to its configured endpoint',async()=>{const router=await mockProviderServer(),direct=await mockProviderServer(),key='fake-openrouter-key';const selection=configuredCognitionProvider({COGNITION_PROVIDER:'openrouter',OPENROUTER_API_KEY:key,OPENROUTER_BASE_URL:router.baseUrl,OPENROUTER_MODEL:'openai/gpt-5-mini',OPENROUTER_HTTP_REFERER:'https://example.test',OPENROUTER_APP_TITLE:'AutomaticWorld',OPENAI_API_KEY:'fake-direct-key',OPENAI_BASE_URL:direct.baseUrl,OPENAI_MODEL:'gpt-5-mini'});expect(selection.selected).toBe('openrouter');expect((await selection.provider!.verifyConnectivity())).toMatchObject({provider:'openrouter',endpointIdentity:'OpenRouter',modelIdentifier:'openai/gpt-5-mini',connected:true,inferenceVerified:false});await selection.provider!.think(input);expect(router.requests.map((request)=>request.url)).toEqual(['/api/v1/key','/api/v1/chat/completions']);expect(router.requests.every((request)=>request.headers.authorization===`Bearer ${key}`)).toBe(true);expect(router.requests[0]?.headers['http-referer']).toBe('https://example.test');expect(router.requests[0]?.headers['x-openrouter-title']).toBe('AutomaticWorld');expect(JSON.parse(router.requests[1]!.body).model).toBe('openai/gpt-5-mini');expect(direct.requests).toHaveLength(0);});

  it('refuses to send an OpenRouter key to the official OpenAI endpoint',()=>{const fetcher=vi.fn();const selection=configuredCognitionProvider({COGNITION_PROVIDER:'openrouter',OPENROUTER_API_KEY:'fake-openrouter-key',OPENROUTER_BASE_URL:'https://api.openai.com/v1',OPENROUTER_MODEL:'openai/gpt-5-mini'},fetcher as unknown as typeof fetch);expect(selection.provider).toBeNull();expect(selection.error).toMatch(/not allowed/i);expect(fetcher).not.toHaveBeenCalled();});

  it('keeps direct OpenAI configuration independent',async()=>{const direct=await mockProviderServer(),selection=configuredCognitionProvider({COGNITION_PROVIDER:'openai',OPENAI_API_KEY:'fake-direct-key',OPENAI_BASE_URL:direct.baseUrl,OPENAI_MODEL:'gpt-5-mini',OPENROUTER_API_KEY:'fake-openrouter-key',OPENROUTER_MODEL:'openai/gpt-5-mini'});expect((await selection.provider!.verifyConnectivity())).toMatchObject({provider:'openai',endpointIdentity:'OpenAI',modelIdentifier:'gpt-5-mini',connected:true,inferenceVerified:false});await selection.provider!.think(input);expect(direct.requests.every((request)=>request.headers.authorization==='Bearer fake-direct-key')).toBe(true);expect(JSON.parse(direct.requests[1]!.body).model).toBe('gpt-5-mini');});

  it('fails readiness cleanly when the OpenRouter key is missing without falling back to an OpenAI key',async()=>{const fetcher=vi.fn(),selection=configuredCognitionProvider({COGNITION_PROVIDER:'openrouter',OPENAI_API_KEY:'must-not-be-used',OPENROUTER_MODEL:'openai/gpt-5-mini'},fetcher as unknown as typeof fetch);expect(await selection.provider!.verifyConnectivity()).toMatchObject({configured:false,connected:false,error:'OPENROUTER_API_KEY and OPENROUTER_MODEL are required'});expect(fetcher).not.toHaveBeenCalled();});

  it('fails closed for an unknown provider',()=>{const selection=configuredCognitionProvider({COGNITION_PROVIDER:'unknown-provider',OPENROUTER_API_KEY:'fake-openrouter-key'});expect(selection).toMatchObject({selected:null,provider:null,error:'Unsupported cognition provider'});});

  it('sanitizes OpenRouter errors before they can enter world history',async()=>{const secret='fake-openrouter-key-never-persist',fetcher=vi.fn(async()=>{throw new Error(`failed at https://openrouter.ai/?key=${secret}`);}) as unknown as typeof fetch,selection=configuredCognitionProvider({COGNITION_PROVIDER:'openrouter',OPENROUTER_API_KEY:secret,OPENROUTER_MODEL:'openai/gpt-5-mini'},fetcher),dir=await mkdtemp(path.join(tmpdir(),'ai-world-openrouter-error-'));dirs.push(dir);const engine=new WorldEngine(defaultConfig(dir),selection.provider!);await engine.genesis();engine.resume();await engine.tick('run-test');const persisted=JSON.stringify({events:engine.repo.listEvents(100),memories:engine.repo.listAgents().flatMap((agent)=>engine.repo.memoriesFor(agent.id))});engine.close();expect(persisted).not.toContain(secret);expect(persisted).not.toContain('openrouter.ai');expect(persisted).toContain('Provider transport failed');});

  it('persists sanitized phase metadata for all provider failure categories',async()=>{const secret='sk-never-persist-this',cases:Array<{name:string;fetcher:typeof fetch;phase:string;httpStatus?:number;providerCode?:string}>=[{name:'transport',fetcher:vi.fn(async()=>{throw new Error(`socket failed at https://example.test/?key=${secret}`);}) as unknown as typeof fetch,phase:'transport'},{name:'timeout',fetcher:vi.fn((_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))))) as unknown as typeof fetch,phase:'timeout'},{name:'HTTP 429',fetcher:vi.fn(async()=>response({error:{code:429,message:`slow ${secret}`}},429)) as unknown as typeof fetch,phase:'http',httpStatus:429,providerCode:'429'},{name:'HTTP 500',fetcher:vi.fn(async()=>response({error:{code:'server_error',message:'unavailable'}},500)) as unknown as typeof fetch,phase:'http',httpStatus:500,providerCode:'server_error'},{name:'response parse',fetcher:vi.fn(async()=>response('not json')) as unknown as typeof fetch,phase:'response_parse',httpStatus:200},{name:'response schema',fetcher:vi.fn(async()=>response({choices:[{message:{content:JSON.stringify({thoughtSummary:'x',selectedAction:{type:'SHELL'}})}}]})) as unknown as typeof fetch,phase:'response_schema',httpStatus:200}];for(const item of cases){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-provider-phase-'));dirs.push(dir);const provider=new OpenAICompatibleCognitionProvider({apiKey:'test',fetcher:item.fetcher,timeoutMs:5,maxRetries:0}),engine=new WorldEngine(defaultConfig(dir),provider);await engine.genesis();engine.repo.setSleepingUntil(engine.repo.getAgent('Toey')!.id,2);engine.resume();await engine.tick('phase-test');const event=engine.repo.listEvents(100).find((candidate)=>candidate.type==='COGNITION_PROVIDER_ERROR')!;engine.close();expect(event.payload,item.name).toMatchObject({phase:item.phase,retryable:true,attemptCount:1,attempts:1,...(item.httpStatus!==undefined?{httpStatus:item.httpStatus}:{}),...(item.providerCode?{providerCode:item.providerCode}:{})});const serialized=JSON.stringify(event);expect(serialized).not.toContain(secret);expect(serialized).not.toContain('Bearer');expect(serialized).not.toContain('example.test');expect(serialized).not.toContain('thoughtSummary');}});

  it('keeps credentials and provider infrastructure out of observations, execution requests, and world state',async()=>{const key='fake-openrouter-isolation-key',endpoint='https://openrouter.ai/api/v1',model='openai/gpt-5-mini',fetcher=vi.fn(async()=>new Response(JSON.stringify(validBody),{status:200,headers:{'content-type':'application/json'}})) as unknown as typeof fetch,selection=configuredCognitionProvider({COGNITION_PROVIDER:'openrouter',OPENROUTER_API_KEY:key,OPENROUTER_BASE_URL:endpoint,OPENROUTER_MODEL:model},fetcher);let executionRequest='';const sandbox=new FakeExecutionSandbox((request)=>{executionRequest=JSON.stringify(request);return{success:true,exitCode:0,stdout:'ok',stderr:'',timedOut:false,durationMs:1,truncated:false};}),dir=await mkdtemp(path.join(tmpdir(),'ai-world-openrouter-isolation-'));dirs.push(dir);const engine=new WorldEngine(defaultConfig(dir),selection.provider!,sandbox);await engine.genesis();const mam=engine.repo.getAgent('Mam')!,observation=JSON.stringify(await engine.observe(mam));expect(observation).not.toContain(key);expect(observation).not.toContain(endpoint);expect(observation).not.toContain(model);expect(observation).not.toContain('openrouter');await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'program.js',content:'console.log("ok")'});await engine.perform(mam.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'program.js',args:[],stdin:''});expect(executionRequest).not.toContain(key);expect(executionRequest).not.toContain(endpoint);expect(executionRequest).not.toContain(model);engine.resume();await engine.tick('run-test');const worldState=JSON.stringify({world:engine.repo.getWorld(),agents:engine.repo.listAgents(),events:engine.repo.listEvents(100),messages:engine.repo.messagesFor(mam.id),memories:engine.repo.memoriesFor(mam.id),executions:engine.repo.executionsFor(mam.id)});expect(worldState).not.toContain(key);expect(worldState).not.toContain(endpoint);expect(worldState).not.toContain(model);expect(worldState).not.toContain('openrouter');engine.close();});
});
