import { fundCognition } from './resource-fixtures.js';
import { createHash } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { configuredCognitionProvider,type CognitionProvider,type CognitionOutput } from '../packages/cognition/src/index.js';
import { migratePendingProvider } from '../packages/operations/src/pending-provider.js';
import { eventVisibility } from '../packages/shared/src/index.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';

const dirs:string[]=[];
const target={provider:'opencode-zen',modelIdentifier:'space-bunny-free'};
const env={OPENCODE_ZEN_API_KEY:'zen-secret-test'};
const policy={initialBackoffMs:50,maxBackoffMs:50,maxSuspensionMs:500,retryAfterMaxMs:50};
const limited: CognitionOutput={thoughtSummary:'Safely waited.',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerError:'Provider HTTP 429',providerRequestSucceeded:false,providerAttempts:1,providerFailure:{phase:'http',httpStatus:429,retryable:true}}};
const models=vi.fn(async()=>new Response(JSON.stringify({data:[{id:'space-bunny-free'}]}))) as unknown as typeof fetch;
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const snapshot=(engine:WorldEngine)=>({world:engine.repo.getWorld(),agents:engine.repo.listAgents(),cursors:engine.repo.listAgents().map((agent)=>engine.repo.observationCursor(agent.id)),messages:engine.repo.listAgents().map((agent)=>engine.repo.messagesFor(agent.id)),memories:engine.repo.listAgents().map((agent)=>engine.repo.memoriesFor(agent.id)),events:engine.repo.listEvents(1000),schedule:engine.repo.tickSchedule()});
async function frozen(){const dir=await mkdtemp(path.join(tmpdir(),'aw-pending-provider-'));dirs.push(dir);const controller=new AbortController(),provider:CognitionProvider={async think(){queueMicrotask(()=>controller.abort());return limited;}},engine=new WorldEngine(defaultConfig(dir),provider);await engine.genesis();fundCognition(engine);engine.resume();const result=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'minimax/minimax-m3:free',rateLimitSuspension:policy,signal:controller.signal});expect(result.ticks).toBe(0);engine.pause();return{engine,dir};}
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});

describe('Owner pending-provider migration',()=>{
  it('changes only routing and cooldown, preserving frozen context and all inhabitant state',async()=>{const {engine}=await frozen(),before=snapshot(engine),pending=before.schedule!,contextHash=hash(pending.pendingContext!),beforeDiagnostic=engine.repo.pendingProviderDiagnostic();expect(before.world?.currentTick).toBe(0);expect(pending).toMatchObject({tick:1,provider:'openrouter',pendingAgentId:engine.repo.getAgent('Mam')!.id,completedAgentIds:[],state:'PAUSED'});const result=await migratePendingProvider(engine.repo,target,env,models);const after=snapshot(engine);expect(result.changed).toBe(true);expect(hash(after.schedule!.pendingContext!)).toBe(contextHash);expect(engine.repo.pendingProviderDiagnostic()).toMatchObject({pendingContextSha256:contextHash,agentState:beforeDiagnostic.agentState});expect(after.schedule).toMatchObject({id:pending.id,tick:pending.tick,agentIds:pending.agentIds,completedAgentIds:pending.completedAgentIds,pendingAgentId:pending.pendingAgentId,provider:'opencode-zen',modelIdentifier:'space-bunny-free',state:'ACTIVE',cooldownStartedAtMs:null,nextRetryAtMs:null,rateLimitAttempts:0});expect(after.world).toEqual(before.world);expect(after.agents).toEqual(before.agents);expect(after.cursors).toEqual(before.cursors);expect(after.messages).toEqual(before.messages);expect(after.memories).toEqual(before.memories);expect(after.events.slice(1)).toEqual(before.events);expect(after.events[0]).toMatchObject({type:'PENDING_PROVIDER_MIGRATED',payload:{oldProvider:'openrouter',newProvider:'opencode-zen',ownerInitiated:true}});expect(eventVisibility(after.events[0]!)).toBe('OWNER_KERNEL_ONLY');expect(engine.repo.tickScheduleDiagnostic()).toMatchObject({active:false,pendingScheduler:true,cooldownActive:false});expect((await migratePendingProvider(engine.repo,target,env,models)).changed).toBe(false);expect(engine.repo.listEvents(1000).filter((event)=>event.type==='PENDING_PROVIDER_MIGRATED')).toHaveLength(1);engine.close();});

  it('rejects missing scheduler, active runner, missing key and unavailable model without mutation',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'aw-pending-empty-'));dirs.push(dir);const empty=new WorldEngine(defaultConfig(dir));await empty.genesis();fundCognition(empty);await expect(migratePendingProvider(empty.repo,target,env,models)).rejects.toThrow(/No frozen/);empty.close();const {engine}=await frozen(),before=snapshot(engine);expect(engine.repo.acquireRunnerLease('test-token',30_000)).toBe(true);await expect(migratePendingProvider(engine.repo,target,env,models)).rejects.toThrow(/runner lease/);engine.repo.releaseRunnerLease('test-token');await expect(migratePendingProvider(engine.repo,target,{},models)).rejects.toThrow(/configuration/);const missing=vi.fn(async()=>new Response(JSON.stringify({data:[]}))) as unknown as typeof fetch;await expect(migratePendingProvider(engine.repo,target,env,missing)).rejects.toThrow(/not found/);await expect(migratePendingProvider(engine.repo,{provider:'invalid',modelIdentifier:'x'},env,models)).rejects.toThrow(/Unsupported/);expect(snapshot(engine)).toEqual(before);engine.close();});

  it('rolls back routing when audit insertion fails',async()=>{const {engine}=await frozen(),before=snapshot(engine);engine.repo.db.exec("CREATE TRIGGER reject_migration BEFORE INSERT ON events WHEN NEW.type='PENDING_PROVIDER_MIGRATED' BEGIN SELECT RAISE(ABORT,'blocked'); END");await expect(migratePendingProvider(engine.repo,target,env,models)).rejects.toThrow(/blocked/);expect(snapshot(engine)).toEqual(before);engine.close();});

  it('survives restart and completes Mam and Toey exactly once under Zen',async()=>{const {engine,dir}=await frozen(),before=snapshot(engine),beforeHash=hash(before.schedule!.pendingContext!);await migratePendingProvider(engine.repo,target,env,models);engine.close();const calls:string[]=[];const fetcher=vi.fn(async(url:string,init:RequestInit)=>{expect(url).toBe('https://opencode.ai/zen/v1/chat/completions');const body=JSON.parse(String(init.body));expect(body.model).toBe('space-bunny-free');calls.push(JSON.parse(body.messages[1].content).identity.name);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({thoughtSummary:'Selected WAIT.',selectedAction:{type:'WAIT',ticks:1}})}}],usage:{prompt_tokens:7,completion_tokens:2,total_tokens:9}}));}) as unknown as typeof fetch;const provider=configuredCognitionProvider({COGNITION_PROVIDER:'opencode-zen',...env},fetcher).provider!,restarted=new WorldEngine(defaultConfig(dir),provider);expect(hash(restarted.repo.tickSchedule()!.pendingContext!)).toBe(beforeHash);restarted.resume();const run=await new ContinuousWorldRunner(restarted).run({tickMs:0,maxTicks:1,provider:'opencode-zen',modelIdentifier:'space-bunny-free',rateLimitSuspension:policy});expect(run).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(calls).toEqual(['Mam','Toey']);expect(restarted.repo.getWorld()?.currentTick).toBe(1);expect(restarted.repo.tickSchedule()).toBeNull();const events=restarted.repo.listEvents(1000);for(const name of ['Mam','Toey']){const agent=restarted.repo.getAgent(name)!;expect(events.filter((event)=>event.type==='AUTONOMY_ACTION'&&event.actorId===agent.id)).toHaveLength(1);expect(restarted.repo.economy.self(agent.id).cognitionCredits.total).toBe(9999);expect(restarted.repo.observationCursor(agent.id).lastSuccessfulTick).toBe(1);}expect(events.filter((event)=>event.type==='TICK_COMPLETED')).toHaveLength(1);expect(events.filter((event)=>event.type==='COGNITION_TURN_COMPLETED').map((event)=>event.payload.totalTokens)).toEqual([9,9]);restarted.close();});
});

describe('Zen long-profile cooldown',()=>{
  it('preserves the later inhabitant on HTTP 429 and resumes the same boundary',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'aw-zen-cooldown-'));dirs.push(dir);const calls:string[]=[];let frozenResources:{compute:number;cursor:unknown;sleep:number}|undefined;const fetcher=vi.fn(async(_url:string,init:RequestInit)=>{const request=JSON.parse(String(init.body)),name=JSON.parse(request.messages[1].content).identity.name;calls.push(name);if(calls.length===2){const toey=engine.repo.getAgent('Toey')!;frozenResources={compute:engine.repo.economy.self(toey.id).cognitionCredits.total,cursor:engine.repo.observationCursor(toey.id),sleep:toey.sleepingUntilTick};return new Response(JSON.stringify({error:{code:'rate_limit'}}),{status:429,headers:{'retry-after':'0'}});}return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({thoughtSummary:'Selected WAIT.',selectedAction:{type:'WAIT',ticks:1}})}}],usage:{prompt_tokens:7,completion_tokens:2}}));}) as unknown as typeof fetch;const engine=new WorldEngine(defaultConfig(dir),configuredCognitionProvider({COGNITION_PROVIDER:'opencode-zen',...env},fetcher).provider!);await engine.genesis();fundCognition(engine);engine.resume();const run=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'opencode-zen',modelIdentifier:'space-bunny-free',rateLimitSuspension:policy});expect(run.ticks).toBe(1);expect(calls).toEqual(['Mam','Toey','Toey']);expect(frozenResources).toEqual({compute:10000,cursor:expect.objectContaining({lastSuccessfulTick:null}),sleep:0});const events=engine.repo.listEvents(1000);expect(events.filter((event)=>event.type==='PROVIDER_COOLDOWN_STARTED')).toHaveLength(1);expect(events.filter((event)=>event.type==='PROVIDER_COOLDOWN_RETRY')).toHaveLength(1);expect(events.filter((event)=>event.type==='COGNITION_FALLBACK')).toHaveLength(0);expect(events.filter((event)=>event.type==='TICK_COMPLETED')).toHaveLength(1);engine.close();});
});
