import { fundCognition,local } from './resource-fixtures.js';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import type { CognitionOutput,CognitionProvider } from '../packages/cognition/src/index.js';
import { createRunReport } from '../packages/operations/src/run-report.js';
import { WorldEngine,defaultConfig,type WorldConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner,type RateLimitSuspensionOptions } from '../packages/world/src/runner.js';

const dirs:string[]=[];
const policy:RateLimitSuspensionOptions={initialBackoffMs:5,maxBackoffMs:20,maxSuspensionMs:250,retryAfterMaxMs:100};
const success=(ticks=1):CognitionOutput=>({thoughtSummary:'Selected WAIT.',selectedAction:{type:'WAIT',ticks},reasoningMetadata:{providerRequestSucceeded:true,providerAttempts:1,inputTokens:7,outputTokens:2}});
const limited=(retryAfterMs?:number):CognitionOutput=>({thoughtSummary:'Cognition output could not be validated; safely waited.',selectedAction:{type:'WAIT',ticks:1},reasoningMetadata:{providerError:'Provider HTTP 429',providerRequestSucceeded:false,providerAttempts:1,inputTokens:0,outputTokens:0,providerFailure:{phase:'http',httpStatus:429,code:429,message:'Provider returned error',retryable:true,...(retryAfterMs===undefined?{}:{retryAfterMs})}}});
async function setup(provider:CognitionProvider,overrides:Partial<WorldConfig>={}){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-429-'));dirs.push(dir);const engine=new WorldEngine({...defaultConfig(dir),...overrides},provider);await engine.genesis();fundCognition(engine);engine.resume();return{engine,dir};}
const state=(engine:WorldEngine)=>engine.repo.listAgents().map((agent)=>({id:agent.id,compute:engine.repo.economy.self(agent.id).cognitionCredits.total,sleep:agent.sleepingUntilTick,cursor:engine.repo.observationCursor(agent.id),memories:engine.repo.memoryCount(agent.id)}));
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});

describe('long-run HTTP 429 suspension',()=>{
  it('freezes the same cognition opportunity, retries it, and completes the tick once without a synthetic WAIT',async()=>{const calls:string[]=[];let mamCalls=0;const provider:CognitionProvider={async think(input){calls.push(input.identity.name);if(input.identity.name==='Mam'&&mamCalls++===0)return limited();return success();}}, {engine}=await setup(provider),before=state(engine),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy}),events=engine.repo.eventsBetweenIds(engine.repo.getAutonomyRun(outcome.runId)!.startEventId,engine.repo.getAutonomyRun(outcome.runId)!.endEventId!);expect(outcome).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(calls).toEqual(['Mam','Mam','Toey']);expect(events.filter((event)=>event.type==='TICK_COMPLETED')).toHaveLength(1);expect(events.filter((event)=>event.type==='COGNITION_PROVIDER_ERROR'||event.type==='COGNITION_FALLBACK')).toHaveLength(0);expect(events.filter((event)=>event.type==='AUTONOMY_ACTION')).toHaveLength(2);expect(events.filter((event)=>event.type==='PROVIDER_COOLDOWN_STARTED')).toHaveLength(1);expect(events.filter((event)=>event.type==='PROVIDER_COOLDOWN_RETRY')).toHaveLength(1);expect(events.filter((event)=>event.type==='PROVIDER_COOLDOWN_RECOVERED')).toHaveLength(1);expect(engine.repo.listAgents().map((agent,index)=>before[index]!.compute-engine.repo.economy.self(agent.id).cognitionCredits.total)).toEqual([1,1]);engine.close();});

  it('uses one provider/model cooldown and does not call the next inhabitant after a confirmed 429',async()=>{const calls:string[]=[];let limitedOnce=false;const provider:CognitionProvider={async think(input){calls.push(input.identity.name);if(!limitedOnce){limitedOnce=true;return limited();}return success();}}, {engine}=await setup(provider);await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'minimax/minimax-m3:free',rateLimitSuspension:policy});expect(calls).toEqual(['Mam','Mam','Toey']);expect(engine.repo.listEvents().find((event)=>event.type==='PROVIDER_COOLDOWN_STARTED')?.payload).toMatchObject({provider:'openrouter',modelIdentifier:'minimax/minimax-m3:free',httpStatus:429,providerCode:'429'});engine.close();});

  it('persists partial-tick progress across cancellation and restart without running the completed inhabitant twice',async()=>{const controller=new AbortController(),firstCalls:string[]=[];const firstProvider:CognitionProvider={async think(input){firstCalls.push(input.identity.name);if(input.identity.name==='Toey'){queueMicrotask(()=>controller.abort());return limited(50);}return success();}}, {engine,dir}=await setup(firstProvider),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!,mamBefore=local(engine,mam.id),toeyBefore=local(engine,toey.id),first=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy,signal:controller.signal});expect(first).toMatchObject({ticks:0,reason:'shutdown signal'});expect(firstCalls).toEqual(['Mam','Toey']);expect(engine.repo.getWorld()?.currentTick).toBe(0);expect(local(engine,mam.id)).toBe(mamBefore);expect(local(engine,toey.id)).toBe(toeyBefore);expect(engine.repo.tickSchedule()).toMatchObject({state:'PAUSED',completedAgentIds:[mam.id],pendingAgentId:toey.id});expect(engine.repo.runnerLeaseStatus().present).toBe(false);engine.close();const resumedCalls:string[]=[];const resumed=new WorldEngine(defaultConfig(dir),{async think(input){resumedCalls.push(input.identity.name);return success();}});const second=await new ContinuousWorldRunner(resumed).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy});expect(second).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(resumedCalls).toEqual(['Toey']);expect(resumed.repo.listEvents().filter((event)=>event.type==='AUTONOMY_ACTION'&&event.actorId===mam.id&&event.tick===1)).toHaveLength(1);expect(resumed.repo.listEvents().filter((event)=>event.type==='AUTONOMY_ACTION'&&event.actorId===toey.id&&event.tick===1)).toHaveLength(1);expect(resumed.repo.listEvents().filter((event)=>event.type==='TICK_COMPLETED'&&event.tick===1)).toHaveLength(1);expect(resumed.repo.tickSchedule()).toBeNull();resumed.close();});

  it('terminates explicitly at maximum suspension with compute, cursor, sleep, and memory unchanged',async()=>{const {engine}=await setup({async think(){return limited();}}),before=state(engine),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:{initialBackoffMs:50,maxBackoffMs:50,maxSuspensionMs:10,retryAfterMaxMs:50}}),after=state(engine);expect(outcome).toMatchObject({ticks:0,reason:'provider rate-limit suspension exhausted'});expect(engine.repo.getWorld()?.currentTick).toBe(0);expect(after).toEqual(before);expect(engine.repo.tickSchedule()).toMatchObject({state:'PAUSED',rateLimitAttempts:1});expect(engine.repo.listEvents().some((event)=>event.type==='AUTONOMY_ACTION'||event.type==='AGENT_WAITED'||event.type==='TICK_COMPLETED')).toBe(false);expect(engine.repo.runnerLeaseStatus().present).toBe(false);engine.close();});

  it('counts cooldown against wall-clock limits without advancing simulation',async()=>{const {engine}=await setup({async think(){return limited(100);}}),before=state(engine),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,wallClockLimitMs:15,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy});expect(outcome).toMatchObject({ticks:0,reason:'wall-clock limit reached'});expect(engine.repo.getWorld()?.currentTick).toBe(0);expect(state(engine)).toEqual(before);expect(engine.repo.tickSchedule()?.state).toBe('PAUSED');engine.close();});

  it('honors Retry-After within the long bound and uses exponential fallback when absent',async()=>{let calls=0;const {engine}=await setup({async think(){return calls++===0?limited(30):success();}}),started=Date.now(),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy}),event=engine.repo.eventsBetweenIds(engine.repo.getAutonomyRun(outcome.runId)!.startEventId,engine.repo.getAutonomyRun(outcome.runId)!.endEventId!).find((item)=>item.type==='PROVIDER_COOLDOWN_STARTED');expect(Date.now()-started).toBeGreaterThanOrEqual(25);expect(event?.payload.backoffMs).toBe(30);engine.close();let fallbackCalls=0;const second=await setup({async think(){return fallbackCalls++===0?limited():success();}});const secondRun=await new ContinuousWorldRunner(second.engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy}),fallbackEvent=second.engine.repo.eventsBetweenIds(second.engine.repo.getAutonomyRun(secondRun.runId)!.startEventId,second.engine.repo.getAutonomyRun(secondRun.runId)!.endEventId!).find((item)=>item.type==='PROVIDER_COOLDOWN_STARTED');expect(fallbackEvent?.payload.backoffMs).toBe(policy.initialBackoffMs);second.engine.close();});

  it('keeps the runner lease healthy through cooldown longer than its heartbeat interval',async()=>{let calls=0;const {engine}=await setup({async think(){return calls++===0?limited(160):success();}},{runnerLeaseMs:300,runnerHeartbeatMs:40}),renew=vi.spyOn(engine.repo,'renewRunnerLease'),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:{...policy,maxSuspensionMs:500,retryAfterMaxMs:200}});expect(outcome.ticks).toBe(1);expect(renew.mock.calls.length).toBeGreaterThanOrEqual(3);expect(engine.repo.listEvents().some((event)=>event.type==='RUNNER_LEASE_LOST')).toBe(false);engine.close();});

  it('does not count handled 429s toward the infrastructure breaker and reports suspension metrics',async()=>{let calls=0;const {engine}=await setup({async think(){return calls++===0?limited():success();}}),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,infrastructureFailureThreshold:1,provider:'openrouter',modelIdentifier:'model',rateLimitSuspension:policy}),report=createRunReport(engine.repo,outcome.runId);expect(outcome.reason).toBe('maximum ticks reached');expect(engine.repo.listEvents().some((event)=>event.type==='AUTONOMY_CIRCUIT_BREAKER_OPENED')).toBe(false);expect(report.facts).toMatchObject({providerFailures:0,rateLimitSuspensions:1,rateLimitRetries:1,rateLimitRecoveries:1});expect(report.facts.rateLimitSuspensionMs).toBeGreaterThanOrEqual(0);engine.close();});

  it('retains conservative default-profile fallback behavior',async()=>{const {engine}=await setup({async think(){return limited();}}),outcome=await new ContinuousWorldRunner(engine).run({tickMs:0,maxTicks:1,infrastructureFailureThreshold:10,provider:'openrouter',modelIdentifier:'model'}),events=engine.repo.eventsBetweenIds(engine.repo.getAutonomyRun(outcome.runId)!.startEventId,engine.repo.getAutonomyRun(outcome.runId)!.endEventId!);expect(outcome.ticks).toBe(1);expect(events.filter((event)=>event.type==='COGNITION_PROVIDER_ERROR')).toHaveLength(2);expect(events.filter((event)=>event.type==='COGNITION_FALLBACK')).toHaveLength(2);expect(events.some((event)=>event.type.startsWith('PROVIDER_COOLDOWN_'))).toBe(false);expect(engine.repo.tickSchedule()).toBeNull();engine.close();});
});
