import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import { InjectedCrash,type MutationTransition } from '../packages/operations/src/reconciliation.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function base(){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-reconcile-'));dirs.push(dir);const engine=new WorldEngine(defaultConfig(dir));await engine.genesis();return engine;}

describe('durable filesystem reconciliation',()=>{
  it.each(['after-prepared','after-filesystem-commit','after-filesystem-journal','after-database-commit'] as MutationTransition[])('reconciles an interrupted private replacement at %s exactly once',async(transition)=>{const initial=await base(),dir=initial.config.dataDir,mam=initial.repo.getAgent('Mam')!;await initial.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'nested/value.txt',content:'old'});initial.close();let injected=false;const crashed=new WorldEngine(defaultConfig(dir),undefined,undefined,{}, {onTransition(point){if(point===transition&&!injected){injected=true;throw new InjectedCrash(point);}}});await expect(crashed.mutations.mutate({agentId:mam.id,space:'private',path:'nested/value.txt',kind:'write',content:'replacement',tick:1,eventType:'FILE_UPDATED'})).rejects.toThrow(InjectedCrash);crashed.close();const restarted=new WorldEngine(defaultConfig(dir));await restarted.initialize();const committed=transition!=='after-prepared';expect((await restarted.files.read(mam.id,'nested/value.txt')).content).toBe(committed?'replacement':'old');expect(restarted.repo.getAgent(mam.id)?.storageBytes).toBe(committed?11:3);expect(restarted.repo.getArtifactRevision('private','nested/value.txt')?.revision).toBe(committed?2:1);expect(restarted.repo.listEvents(100).filter((event)=>event.type==='FILE_UPDATED')).toHaveLength(committed?1:0);expect(restarted.repo.incompleteFilesystemOperations()).toHaveLength(0);expect((await restarted.files.list(mam.id,'nested')).some((file)=>file.includes('.aw-'))).toBe(false);restarted.close();});
  it('finishes an interrupted private creation without false revisions or quota',async()=>{const initial=await base(),dir=initial.config.dataDir,mam=initial.repo.getAgent('Mam')!;initial.close();const crashed=new WorldEngine(defaultConfig(dir),undefined,undefined,{}, {onTransition(point){if(point==='after-prepared')throw new InjectedCrash(point);}});await expect(crashed.mutations.mutate({agentId:mam.id,space:'private',path:'new.txt',kind:'create',content:'new',tick:1,eventType:'FILE_CREATED'})).rejects.toThrow();crashed.close();const restarted=new WorldEngine(defaultConfig(dir));await restarted.initialize();expect(await restarted.files.inspectFile(mam.id,'new.txt')).toBeNull();expect(restarted.repo.getArtifactRevision('private','new.txt')).toBeNull();expect(restarted.repo.getAgent(mam.id)?.storageBytes).toBe(0);restarted.close();});
  it('reconciles an interrupted shared mutation with one shared revision',async()=>{const initial=await base(),dir=initial.config.dataDir,toey=initial.repo.getAgent('Toey')!;await initial.perform(toey.id,{type:'CREATE_TEXT_FILE',space:'SHARED',path:'state.txt',content:'one'});const current=await initial.files.read(toey.id,'state.txt','shared');initial.close();const crashed=new WorldEngine(defaultConfig(dir),undefined,undefined,{}, {onTransition(point){if(point==='after-filesystem-journal')throw new InjectedCrash(point);}});await expect(crashed.mutations.mutate({agentId:toey.id,space:'shared',path:'state.txt',kind:'write',content:'two-two',expectedHash:current.hash,tick:2,eventType:'FILE_UPDATED'})).rejects.toThrow();crashed.close();const restarted=new WorldEngine(defaultConfig(dir));await restarted.initialize();expect((await restarted.files.read(toey.id,'state.txt','shared')).content).toBe('two-two');expect(restarted.repo.getArtifactRevision('shared','state.txt')?.revision).toBe(2);expect(restarted.repo.getAgent(toey.id)?.storageBytes).toBe(7);expect(restarted.repo.listEvents(100).filter((event)=>event.type==='FILE_UPDATED')).toHaveLength(1);restarted.close();});
});
