import { randomUUID,createHash } from 'node:crypto';
import { mkdtemp,readFile,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';
import { afterEach,describe,expect,it } from 'vitest';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';
import { WorldRepository } from '../packages/persistence/src/repository.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { OwnershipFenceError } from '../packages/sandbox/src/filesystem.js';
import { CAPABILITIES,type AgentRecord } from '../packages/shared/src/index.js';
import { formatCapital } from '../packages/resources/src/economy.js';
import { createRunReport } from '../packages/operations/src/run-report.js';
import { WorldCheckpointService } from '../packages/operations/src/checkpoint.js';
import { economyCli } from '../packages/operations/src/economy-cli.js';
import type { CognitionProvider } from '../packages/cognition/src/index.js';

const dirs:string[]=[],engines:WorldEngine[]=[],repos:WorldRepository[]=[];
afterEach(async()=>{for(const e of engines.splice(0))if(e.repo.db.open)e.close();for(const r of repos.splice(0))if(r.db.open)r.close();for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
const success={thoughtSummary:'Selected WAIT.',selectedAction:{type:'WAIT' as const,ticks:1},reasoningMetadata:{providerRequestSucceeded:true,providerAttempts:2,inputTokens:12,outputTokens:3}};
async function directory(){const dir=await mkdtemp(path.join(tmpdir(),'aw-resources-'));dirs.push(dir);return dir;}
async function setup(provider?:CognitionProvider,execute=()=>({success:false,exitCode:1,stdout:'',stderr:'program error',timedOut:false,durationMs:1,truncated:false})){
  const e=new WorldEngine({...defaultConfig(await directory()),initialLocalCompute:100},provider,new FakeExecutionSandbox(execute));engines.push(e);await e.genesis();return e;
}
const account=(e:WorldEngine,name='Mam')=>`AGENT:${e.repo.getAgent(name)!.id}`;
const inject=(e:WorldEngine,amount:number,name='Mam',resource:'COGNITION_CREDIT'|'LOCAL_COMPUTE'='COGNITION_CREDIT',key=randomUUID())=>e.repo.economy.injectResource({resource,amount,to:account(e,name),source:'PROVIDER_FREE_ALLOWANCE',key});
async function legacy(){
  const dir=await directory(),repo=new WorldRepository(path.join(dir,'world.sqlite'));repos.push(repo);repo.createWorld({id:randomUUID(),createdAt:new Date().toISOString(),currentTick:1805,simulatedTime:'2026-09-04T11:06:42.886Z',status:'paused'});
  for(const [name,amount,storage,sleep] of [['Mam',2610,36495,1900],['Toey',0,47924,1724]] as const){const a:AgentRecord={id:randomUUID(),name,computeCredits:amount,storageBytes:storage,sleepingUntilTick:sleep,eligibleFromTick:0,createdAt:new Date().toISOString(),generation:0,parentIds:[],status:'active',cognitionConfig:{provider:'kernel-private'},capabilities:[...CAPABILITIES],metadata:{},};repo.createAgent(a);}
  return {repo,dir};
}

describe('explicit resource-model migration and conservation',()=>{
  it('exercises actual Owner CLI preview/guards/apply/doctor only in an isolated legacy fixture',async()=>{const {repo,dir}=await legacy();repo.close();const loader=pathToFileURL(path.resolve('node_modules/tsx/dist/loader.mjs')).href,cli=path.resolve('apps/world-cli/src/index.ts'),run=(args:string[])=>spawnSync(process.execPath,['--import',loader,cli,...args],{cwd:dir,env:{...process.env,WORLD_DATA_DIR:dir},encoding:'utf8',timeout:10000});const preview=run(['resources','migrate-legacy','--preview']);expect(preview.status,preview.stderr).toBe(0);expect(JSON.parse(preview.stdout).agents.map((a:any)=>[a.name,a.localCompute,a.cognitionCredits])).toEqual([['Mam',2610,0],['Toey',0,0]]);for(const args of [['resume'],['run','--ticks','1'],['experiment','--live','--ticks','1']]){const blocked=run(args);expect(blocked.status).not.toBe(0);expect(blocked.stderr).toContain('migration required');}const apply=run(['resources','migrate-legacy','--apply']);expect(apply.status,apply.stderr).toBe(0);expect(JSON.parse(apply.stdout)).toEqual({applied:true,version:2});const doctor=run(['doctor','--integrity-only']);expect(doctor.status,doctor.stderr).toBe(0);expect(JSON.parse(doctor.stdout)).toMatchObject({sqliteIntegrity:'ok',resourceModelVersion:2,resourceEconomyIntegrity:'ok',world:{status:'paused',currentTick:1805}});const duplicate=run(['resources','migrate-legacy','--apply']);expect(JSON.parse(duplicate.stdout)).toEqual({applied:false,version:2});},20000);
  it('previews without mutation and maps T1805 legacy compute only to Local Compute',async()=>{
    const {repo}=await legacy(),before=repo.db.prepare('SELECT total_changes() n').get(),preview=repo.economy.migrationPreview();
    expect(preview.agents.map(a=>[a.name,a.legacyCompute,a.localCompute,a.cognitionCredits,a.storageBytes])).toEqual([['Mam',2610,2610,0,36495],['Toey',0,0,0,47924]]);expect(repo.db.prepare('SELECT total_changes() n').get()).toEqual(before);
    const agents=repo.listAgents(),world=repo.getWorld();repo.economy.migrateLegacy();expect(repo.getWorld()).toEqual(world);expect(repo.listAgents()).toEqual(agents);expect(repo.economy.total('LOCAL_COMPUTE')).toBe(2610);expect(repo.economy.total('COGNITION_CREDIT')).toBe(0);expect(repo.economy.capital('WORLD_TREASURY')).toEqual({});expect(repo.economy.integrity()).toEqual([]);expect(repo.economy.migrateLegacy()).toEqual({applied:false,version:2});expect(repo.listEvents(100).filter(e=>e.type==='RESOURCE_MODEL_MIGRATED')).toHaveLength(1);
  });
  it.each(['running','lease','scheduler'] as const)('refuses apply with %s and creates no economy schema',async(condition)=>{
    const {repo}=await legacy();if(condition==='running')repo.setWorldStatus('running');if(condition==='lease')repo.acquireRunnerLease('fixture',1000);if(condition==='scheduler')repo.beginTickSchedule(1806,repo.listAgents().map(a=>a.id),'fixture','fixture');expect(()=>repo.economy.migrateLegacy()).toThrow();expect(repo.economy.version()).toBe(1);expect(repo.db.prepare("SELECT 1 FROM sqlite_master WHERE name='value_ledger'").get()).toBeUndefined();
  });
  it('rolls back the complete migration including DDL when final audit insertion fails',async()=>{
    const {repo}=await legacy();repo.db.exec("CREATE TRIGGER injected_crash BEFORE INSERT ON events WHEN NEW.type='RESOURCE_MODEL_MIGRATED' BEGIN SELECT RAISE(ABORT,'fixture crash'); END");expect(()=>repo.economy.migrateLegacy()).toThrow('fixture crash');expect(repo.economy.version()).toBe(1);expect(repo.db.prepare("SELECT 1 FROM sqlite_master WHERE name='value_accounts'").get()).toBeUndefined();expect(repo.getAgent('Mam')!.computeCredits).toBe(2610);repo.db.exec('DROP TRIGGER injected_crash');expect(repo.economy.migrateLegacy().applied).toBe(true);
  });
  it('guards resume, run, tick and continuous execution before provider calls or scheduler writes',async()=>{
    const {repo,dir}=await legacy();repo.close();let calls=0;const e=new WorldEngine({...defaultConfig(dir),deferSchema:true},{async think(){calls++;return success;}});engines.push(e);expect(()=>e.resume()).toThrow('migration required');await expect(e.run(1)).rejects.toThrow('migration required');await expect(e.tick()).rejects.toThrow('migration required');await expect(new ContinuousWorldRunner(e).run({tickMs:0})).rejects.toThrow('migration required');expect(calls).toBe(0);expect(e.repo.getWorld()!.currentTick).toBe(1805);expect(e.repo.tickSchedule()).toBeNull();expect(e.repo.runnerLeaseStatus().present).toBe(false);
  });
  it('preserves pending legacy descendant escrow without duplicating spendable compute',async()=>{
    const {repo}=await legacy(),a=repo.getAgent('Mam')!,b=repo.getAgent('Toey')!,p=repo.createDescendantProposal({proposerAgentId:a.id,coParentAgentId:b.id,proposedName:'Escrow',contribution:500,minimumContribution:0,actionCost:0,tick:1805});repo.economy.migrateLegacy();expect(repo.economy.self(a.id).localCompute).toEqual({total:2610,reserved:500,available:2110});repo.cancelDescendantProposal(p.id,a.id,1805);expect(repo.economy.self(a.id).localCompute.available).toBe(2610);expect(repo.economy.integrity()).toEqual([]);
  });
});

describe('auditable resources and integer capital',()=>{
  it('starts new cognition and capital at zero without regeneration',async()=>{const e=await setup();expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionDormant).toBe(true);e.resume();await e.run(3);expect(e.repo.economy.total('COGNITION_CREDIT')).toBe(0);expect(e.repo.economy.capital(account(e))).toEqual({});expect(e.repo.getWorld()!.currentTick).toBe(3);expect(e.repo.listEvents(100).some(e=>e.type==='ACTION_FAILED')).toBe(false);});
  it('transfers both resources atomically and protects reserved balances',async()=>{
    const e=await setup();inject(e,10);e.repo.economy.transfer('RESOURCE','LOCAL_COMPUTE',100,account(e,'Toey'),'WORLD_RESERVE','empty-b');e.repo.economy.transfer('RESOURCE','COGNITION_CREDIT',3,account(e),account(e,'Toey'),'transfer-c');e.repo.economy.transfer('RESOURCE','LOCAL_COMPUTE',25,account(e),account(e,'Toey'),'transfer-l');expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id)).toMatchObject({cognitionCredits:{total:7},localCompute:{total:75}});expect(e.repo.economy.self(e.repo.getAgent('Toey')!.id)).toMatchObject({cognitionCredits:{total:3},localCompute:{total:25},cognitionDormant:false});
    e.repo.economy.reserve('protected','RESOURCE','COGNITION_CREDIT',account(e),6,'DESCENDANT');expect(()=>e.repo.economy.transfer('RESOURCE','COGNITION_CREDIT',2,account(e),account(e,'Toey'),'overdraft')).toThrow('available');expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionCredits.total).toBe(7);expect(e.repo.economy.integrity()).toEqual([]);
  });
  it('rejects unauthorized transfer sources and invalid accounts',async()=>{const e=await setup();inject(e,3);const toey=e.repo.getAgent('Toey')!;expect(()=>e.repo.economy.transfer('RESOURCE','COGNITION_CREDIT',1,account(e),account(e,'Toey'),'theft',toey.id)).toThrow('owner');expect(()=>e.repo.economy.transfer('RESOURCE','COGNITION_CREDIT',1,account(e),'AGENT:unknown','bad')).toThrow('account');});
  it('records investment, verified revenue and internal monetary ownership without FX',async()=>{const e=await setup(),s=e.repo.economy;const args={currency:'USD',amount:500,to:account(e),key:'investment',reference:'owner fixture'};const id=s.recordCapital(args);expect(s.recordCapital(args)).toBe(id);s.recordCapital({currency:'THB',amount:2500,to:'WORLD_TREASURY',key:'revenue',reference:'verified sale',artifact:'project/main.js',relatedAgent:e.repo.getAgent('Mam')!.id},true);s.transfer('CAPITAL','USD',200,account(e),account(e,'Toey'),'gift',e.repo.getAgent('Mam')!.id);expect(s.capital(account(e)).USD!.total).toBe(300);expect(s.capital(account(e,'Toey')).USD!.total).toBe(200);expect(s.capital('WORLD_TREASURY').THB!.total).toBe(2500);expect(()=>s.transfer('CAPITAL','THB',1,account(e),account(e,'Toey'),'no-fx')).toThrow('available');expect(()=>s.recordCapital({...args,amount:501})).toThrow('conflict');expect(s.integrity()).toEqual([]);});
  it.each([-1,1.1,Number.MAX_SAFE_INTEGER+1])('rejects invalid value %s',async(amount)=>{const e=await setup();expect(()=>inject(e,amount)).toThrow('integer');expect(()=>e.repo.economy.recordCapital({currency:'USD',amount,to:account(e),key:'bad'})).toThrow('integer');});
  it('rejects currency mismatch and overflow without partial movement',async()=>{const e=await setup(),s=e.repo.economy;expect(()=>s.recordCapital({currency:'usd',amount:1,to:account(e),key:'bad'})).toThrow('Currency');s.recordCapital({currency:'USD',amount:Number.MAX_SAFE_INTEGER,to:account(e),key:'max'});expect(()=>s.recordCapital({currency:'USD',amount:1,to:account(e),key:'overflow'})).toThrow('integer');expect(s.capital(account(e)).USD!.total).toBe(Number.MAX_SAFE_INTEGER);expect(s.ledger('CAPITAL')).toHaveLength(1);});
  it('treats claims in messages as communication rather than revenue authority',async()=>{const e=await setup();await e.perform(e.repo.getAgent('Mam')!.id,{type:'SEND_MESSAGE',to:'Toey',content:'I earned USD 100'});expect(e.repo.economy.ledger('CAPITAL')).toEqual([]);expect(()=>e.repo.economy.recordCapital({currency:'USD',amount:100,to:account(e),key:'missing-ref'},true)).toThrow('reference');});
  it('rejects secret-looking economic metadata and keeps ledgers immutable',async()=>{const e=await setup();expect(()=>e.repo.economy.recordCapital({currency:'USD',amount:10,to:account(e),key:'bad',reference:'api_key=fixture'})).toThrow('non-secret');inject(e,1);expect(()=>e.repo.db.prepare('UPDATE value_ledger SET amount=99').run()).toThrow('Immutable');expect(()=>e.repo.db.prepare('DELETE FROM value_ledger').run()).toThrow('Immutable');e.repo.economy.reserve('x','RESOURCE','COGNITION_CREDIT',account(e),1,'COGNITION');expect(()=>e.repo.db.prepare('DELETE FROM reservation_journal').run()).toThrow('Immutable');});
  it('formats exact minor units including zero and three-decimal currencies',()=>{expect(formatCapital('USD',500)).toBe('USD 5.00');expect(formatCapital('THB',2500)).toBe('THB 25.00');expect(formatCapital('JPY',5)).toBe('JPY 5');expect(formatCapital('KWD',500)).toBe('KWD 0.500');});
});

describe('resource purchase authority and atomic settlement',()=>{
  it('persists a request without spending or minting; denial moves no value',async()=>{const e=await setup(),s=e.repo.economy,r=s.request(e.repo.getAgent('Mam')!.id,{resource:'COGNITION_CREDIT',amount:100,reason:'capacity'});expect(s.total('COGNITION_CREDIT')).toBe(0);expect(s.ledger('CAPITAL')).toHaveLength(0);expect(s.decideRequest(r.id,false).status).toBe('DENIED');expect(s.total('COGNITION_CREDIT')).toBe(0);});
  it('reserves approved funds, debits actual cost and credits actual capacity exactly once',async()=>{const e=await setup(),s=e.repo.economy;s.recordCapital({currency:'USD',amount:1000,to:account(e),key:'invest'});const r=s.request(e.repo.getAgent('Mam')!.id,{resource:'COGNITION_CREDIT',amount:100,currency:'USD',maxSpend:200,reason:'capacity'});s.decideRequest(r.id,true);expect(s.capital(account(e)).USD).toEqual({total:1000,reserved:200,available:800});expect(()=>s.transfer('CAPITAL','USD',801,account(e),account(e,'Toey'),'reserved')).toThrow('available');const settlement={cost:150,amount:100,key:'purchase',reference:'externally verified capacity'};s.settleRequest(r.id,settlement);s.settleRequest(r.id,settlement);expect(s.capital(account(e)).USD).toEqual({total:850,reserved:0,available:850});expect(s.self(e.repo.getAgent('Mam')!.id).cognitionCredits.total).toBe(100);expect(()=>s.settleRequest(r.id,{...settlement,cost:151})).toThrow('conflict');expect(s.integrity()).toEqual([]);});
  it('supports free external capacity and rejects agent funding another account',async()=>{const e=await setup(),s=e.repo.economy;expect(()=>s.request(e.repo.getAgent('Mam')!.id,{resource:'LOCAL_COMPUTE',amount:1,reason:'x',fundingAccount:account(e,'Toey')})).toThrow('own');const r=s.request(e.repo.getAgent('Mam')!.id,{resource:'COGNITION_CREDIT',amount:100,reason:'free external allowance'});s.decideRequest(r.id,true);s.settleRequest(r.id,{cost:0,amount:100,key:'free',reference:'free allowance allocation'});expect(s.total('COGNITION_CREDIT')).toBe(100);expect(s.ledger('CAPITAL')).toEqual([]);});
  it('rolls back capital debit and released hold when capacity credit fails',async()=>{const e=await setup(),s=e.repo.economy;s.recordCapital({currency:'USD',amount:500,to:account(e),key:'fund'});const r=s.request(e.repo.getAgent('Mam')!.id,{resource:'COGNITION_CREDIT',amount:100,currency:'USD',maxSpend:200,reason:'capacity'});s.decideRequest(r.id,true);e.repo.db.exec("CREATE TRIGGER settlement_crash BEFORE INSERT ON value_ledger WHEN NEW.category='PURCHASE_SETTLEMENT' AND NEW.kind='RESOURCE' BEGIN SELECT RAISE(ABORT,'fixture crash'); END");expect(()=>s.settleRequest(r.id,{cost:200,amount:100,key:'crash',reference:'receipt'})).toThrow('fixture crash');expect(s.capital(account(e)).USD).toEqual({total:500,reserved:200,available:300});expect(s.getRequest(r.id).status).toBe('APPROVED');expect(s.total('COGNITION_CREDIT')).toBe(0);expect(s.integrity()).toEqual([]);});
  it('preserves settlement idempotency across a process restart',async()=>{const e=await setup(),s=e.repo.economy;s.recordCapital({currency:'USD',amount:1000,to:account(e),key:'fund'});const r=s.request(e.repo.getAgent('Mam')!.id,{resource:'COGNITION_CREDIT',amount:100,currency:'USD',maxSpend:200,reason:'capacity'});s.decideRequest(r.id,true);const receipt={amount:100,cost:200,key:'receipt',reference:'verified external receipt'};s.settleRequest(r.id,receipt);const dir=e.config.dataDir,id=e.repo.getAgent('Mam')!.id;e.close();const restarted=new WorldEngine(defaultConfig(dir));engines.push(restarted);restarted.repo.economy.settleRequest(r.id,receipt);expect(restarted.repo.economy.self(id)).toMatchObject({cognitionCredits:{total:100},capital:{USD:{total:800,reserved:0}}});expect(restarted.repo.economy.integrity()).toEqual([]);});
  it('releases an approved hold on denial and requires approval before settlement',async()=>{const e=await setup(),s=e.repo.economy;s.recordCapital({currency:'USD',amount:500,to:account(e),key:'fund'});const r=s.request(e.repo.getAgent('Mam')!.id,{resource:'LOCAL_COMPUTE',amount:10,currency:'USD',maxSpend:200,reason:'capacity'});expect(()=>s.settleRequest(r.id,{cost:0,amount:10,key:'too-soon',reference:'receipt'})).toThrow('Approve');s.decideRequest(r.id,true);s.decideRequest(r.id,false);expect(s.capital(account(e)).USD!.reserved).toBe(0);});
});

describe('logical cognition reservation and dormancy',()=>{
  it('reuses a durably charged execution result when action publication was interrupted',async()=>{let calls=0,executions=0;const e=await setup({async think(){calls++;return {...success,selectedAction:{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'main.js',args:[],stdin:''}};}},()=>{executions++;return {success:true,exitCode:0,stdout:'42',stderr:'',timedOut:false,durationMs:1,truncated:false};});const id=e.repo.getAgent('Mam')!.id;await e.perform(id,{type:'CREATE_TEXT_FILE',path:'main.js',content:'console.log(42)'});inject(e,1);const cache=(e as any).cacheAction.bind(e);(e as any).cacheAction=(action:any,result:any)=>{if(action.type==='EXECUTE_PROGRAM')throw new OwnershipFenceError('fixture interrupted during result publication');return cache(action,result);};e.resume();await e.tick();expect(e.repo.getWorld()!.currentTick).toBe(0);expect(e.repo.executionsFor(id)).toHaveLength(0);expect(e.repo.economy.consumed('LOCAL_COMPUTE')).toBe(27);const dir=e.config.dataDir;e.close();const restarted=new WorldEngine(defaultConfig(dir),{async think(){calls++;return success;}},new FakeExecutionSandbox(()=>{executions++;return {success:true,exitCode:0,stdout:'42',stderr:'',timedOut:false,durationMs:1,truncated:false};}));engines.push(restarted);await restarted.tick();expect(calls).toBe(1);expect(executions).toBe(1);expect(restarted.repo.executionsFor(id)).toHaveLength(1);expect(restarted.repo.economy.consumed('LOCAL_COMPUTE')).toBe(27);expect(restarted.repo.economy.integrity()).toEqual([]);});
  it.each(['TRANSFER_CAPITAL','REQUEST_RESOURCE_PURCHASE','PROPOSE_DESCENDANT'] as const)('replays %s after a committed action without duplicate movement or request',async(type)=>{let calls=0,toeyId='';const e=await setup({async think(){calls++;return {...success,selectedAction:type==='TRANSFER_CAPITAL'?{type,currency:'USD',amount:200,to:`AGENT:${toeyId}`}:type==='REQUEST_RESOURCE_PURCHASE'?{type,resource:'COGNITION_CREDIT',amount:100,reason:'capacity'}:{type,coParentAgentId:toeyId,proposedName:'ReplayChild',localComputeContribution:20,cognitionContribution:2}};}});toeyId=e.repo.getAgent('Toey')!.id;inject(e,type==='PROPOSE_DESCENDANT'?3:1);e.repo.economy.recordCapital({currency:'USD',amount:500,to:account(e),key:'fixture-capital'});e.resume();const perform=e.perform.bind(e);e.perform=async(...args)=>{await perform(...args);throw new OwnershipFenceError('fixture crash after economic commit');};await e.tick();expect(e.repo.getWorld()!.currentTick).toBe(0);const dir=e.config.dataDir;e.close();const restarted=new WorldEngine(defaultConfig(dir),{async think(){calls++;return success;}});engines.push(restarted);await restarted.tick();expect(calls).toBe(1);expect(restarted.repo.getWorld()!.currentTick).toBe(1);if(type==='TRANSFER_CAPITAL'){expect(restarted.repo.economy.capital(account(restarted)).USD!.total).toBe(300);expect(restarted.repo.economy.capital(account(restarted,'Toey')).USD!.total).toBe(200);}if(type==='REQUEST_RESOURCE_PURCHASE')expect(restarted.repo.economy.requests()).toHaveLength(1);if(type==='PROPOSE_DESCENDANT'){expect(restarted.repo.listDescendantProposals()).toHaveLength(1);expect(restarted.repo.economy.self(restarted.repo.getAgent('Mam')!.id)).toMatchObject({cognitionCredits:{reserved:2},localCompute:{reserved:20}});}expect(restarted.repo.economy.integrity()).toEqual([]);});
  it('replays a durable successful outcome after interruption without a second provider call or charge',async()=>{let calls=0;const e=await setup({async think(){calls++;return success;}});inject(e,1);e.resume();const perform=e.perform.bind(e);e.perform=async()=>{throw new OwnershipFenceError('fixture interrupted after outcome commit');};await e.tick();expect(e.repo.getWorld()!.currentTick).toBe(0);expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionCredits.total).toBe(0);e.perform=perform;const dir=e.config.dataDir;e.close();const restarted=new WorldEngine(defaultConfig(dir),{async think(){calls++;return success;}});engines.push(restarted);await restarted.tick();expect(calls).toBe(1);expect(restarted.repo.getWorld()!.currentTick).toBe(1);expect(restarted.repo.economy.consumed('COGNITION_CREDIT')).toBe(1);expect(restarted.repo.listEvents(100).filter(e=>e.type==='AGENT_WAITED')).toHaveLength(1);expect(restarted.repo.economy.integrity()).toEqual([]);});
  it('rejects a conflicting reservation consumption retry',async()=>{const e=await setup();inject(e,2);const s=e.repo.economy;s.reserve('logical','RESOURCE','COGNITION_CREDIT',account(e),1,'COGNITION');s.resolveReservation('logical',1);s.resolveReservation('logical',1);expect(()=>s.resolveReservation('logical',0)).toThrow('conflict');expect(s.self(e.repo.getAgent('Mam')!.id).cognitionCredits.total).toBe(1);});
  it('holds scarce credits out of transfers during a suspended opportunity',async()=>{const e=await setup();inject(e,1);e.repo.economy.reserve('pending','RESOURCE','COGNITION_CREDIT',account(e),1,'COGNITION');expect(()=>e.repo.economy.transfer('RESOURCE','COGNITION_CREDIT',1,account(e),account(e,'Toey'),'steal-hold')).toThrow('available');expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionCredits).toEqual({total:1,reserved:1,available:0});});
  it('recovers abandoned execution conservatively without refunding uncertain CPU use',async()=>{const e=await setup();e.repo.economy.reserve('abandoned','RESOURCE','LOCAL_COMPUTE',account(e),100,'EXECUTION');const dir=e.config.dataDir;e.close();const restarted=new WorldEngine(defaultConfig(dir));engines.push(restarted);await restarted.initialize();expect(restarted.repo.economy.self(restarted.repo.getAgent('Mam')!.id).localCompute.total).toBe(0);expect(restarted.repo.economy.reservation('abandoned')!.status).toBe('CONSUMED');expect(restarted.repo.economy.integrity()).toEqual([]);});
  it('charges one successful logical turn including short HTTP retries, then skips dormant ticks',async()=>{let calls=0;const e=await setup({async think(){calls++;return success;}});inject(e,1);e.resume();await e.run(3);expect(calls).toBe(1);expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionCredits).toEqual({total:0,reserved:0,available:0});expect(e.repo.economy.consumed('COGNITION_CREDIT')).toBe(1);expect(e.repo.listEvents(100).filter(e=>e.type==='COGNITION_DORMANT')).toHaveLength(1);expect(e.repo.listEvents(100).some(e=>e.type==='ACTION_FAILED')).toBe(false);});
  it('refunds terminal failure and invalid action without consuming an opportunity',async()=>{const e=await setup({async think(){return{...success,reasoningMetadata:{providerRequestSucceeded:false,providerError:'terminal fixture failure'}};}});inject(e,1);e.resume();await e.tick();expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).cognitionCredits).toEqual({total:1,reserved:0,available:1});expect(e.repo.economy.consumed('COGNITION_CREDIT')).toBe(0);});
  it('retains one reservation across timeout suspension and restart',async()=>{
    const abort=new AbortController(),e=await setup({async think(){queueMicrotask(()=>abort.abort());return {...success,reasoningMetadata:{providerRequestSucceeded:false,providerFailure:{phase:'timeout',retryable:true},providerAttempts:3}};}});inject(e,1);e.resume();const policy={initialBackoffMs:1,maxBackoffMs:1,maxSuspensionMs:1000,retryAfterMaxMs:1};await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1,provider:'fixture',modelIdentifier:'fixture',rateLimitSuspension:policy,signal:abort.signal});const id=e.repo.getAgent('Mam')!.id;expect(e.repo.economy.self(id).cognitionCredits).toEqual({total:1,reserved:1,available:0});const dir=e.config.dataDir,context=e.repo.tickSchedule()!.pendingContext;e.close();let calls=0;const restarted=new WorldEngine(defaultConfig(dir),{async think(input){calls++;expect(JSON.parse(context!).input).toEqual(input);return success;}});engines.push(restarted);await new ContinuousWorldRunner(restarted).run({tickMs:0,maxTicks:1,provider:'fixture',modelIdentifier:'fixture',rateLimitSuspension:policy});expect(calls).toBe(1);expect(restarted.repo.economy.self(id).cognitionCredits).toEqual({total:0,reserved:0,available:0});expect(restarted.repo.db.prepare("SELECT count(*) n FROM value_ledger WHERE category='COGNITION_CONSUMED'").get()).toEqual({n:1});expect(restarted.repo.economy.integrity()).toEqual([]);
  });
  it('makes a peer-funded dormant inhabitant eligible on normal scheduling',async()=>{const calls:string[]=[],e=await setup({async think(input){calls.push(input.identity.name);return success;}});inject(e,2);const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;expect((await e.perform(mam.id,{type:'TRANSFER_RESOURCE',resource:'COGNITION_CREDIT',amount:1,to:account(e,'Toey')})).success).toBe(true);expect(e.repo.economy.self(toey.id).cognitionDormant).toBe(false);e.resume();await e.tick();expect(calls).toEqual(['Mam','Toey']);});
  it('allows cognition and kernel primitives at zero Local Compute but blocks execution',async()=>{let executions=0;const e=await setup({async think(){return success;}},()=>{executions++;return {success:true,exitCode:0,stdout:'',stderr:'',timedOut:false,durationMs:1,truncated:false};}),a=e.repo.getAgent('Mam')!;e.repo.economy.transfer('RESOURCE','LOCAL_COMPUTE',100,account(e),'WORLD_RESERVE','empty');inject(e,2);e.resume();await e.tick();for(const action of [{type:'INSPECT_SELF'},{type:'WAIT',ticks:1},{type:'SEND_MESSAGE',to:'Toey',content:'hello'},{type:'CREATE_TEXT_FILE',path:'main.js',content:'0'},{type:'READ_FILE',path:'main.js'},{type:'LIST_FILES'},{type:'REQUEST_RESOURCE_PURCHASE',resource:'LOCAL_COMPUTE',amount:100,reason:'capacity'}])expect((await e.perform(a.id,action)).success).toBe(true);expect((await e.perform(a.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'main.js'})).success).toBe(false);expect(executions).toBe(0);expect(e.repo.economy.self(a.id).localCompute.total).toBe(0);});
  it('charges actual failed execution and protects pending execution from transfer',async()=>{const e=await setup(),a=e.repo.getAgent('Mam')!;await e.perform(a.id,{type:'CREATE_TEXT_FILE',path:'main.js',content:'bad'});expect((await e.perform(a.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'main.js'})).success).toBe(false);expect(e.repo.economy.self(a.id).localCompute.total).toBe(73);expect(e.repo.economy.self(a.id).localCompute.reserved).toBe(0);expect(e.repo.economy.integrity()).toEqual([]);});
  it('makes the maximum execution hold unavailable before entering the sandbox',async()=>{const e=await setup(undefined,()=>{expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).localCompute).toEqual({total:100,reserved:100,available:0});expect(()=>e.repo.economy.transfer('RESOURCE','LOCAL_COMPUTE',1,account(e),account(e,'Toey'),'during-execution')).toThrow('available');return {success:false,exitCode:1,stdout:'',stderr:'',timedOut:true,durationMs:5000,truncated:false};});await e.perform(e.repo.getAgent('Mam')!.id,{type:'CREATE_TEXT_FILE',path:'main.js',content:'loop'});await e.perform(e.repo.getAgent('Mam')!.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'main.js'});expect(e.repo.economy.self(e.repo.getAgent('Mam')!.id).localCompute.reserved).toBe(0);expect(e.repo.economy.consumed('LOCAL_COMPUTE')).toBe(75);});
  it('keeps kernel-generated provider/payment information outside inhabitant context',async()=>{const e=await setup(),a=e.repo.getAgent('Mam')!;e.repo.db.prepare('UPDATE agents SET cognition_config=? WHERE id=?').run(JSON.stringify({provider:'space-bunny-free',endpoint:'https://example.invalid/api',apiKey:'fixture'}),a.id);const context=JSON.stringify(await e.observe(e.repo.getAgent(a.id)!));expect(context).not.toMatch(/space-bunny-free|opencode-zen|https:\/\/|apiKey|billing|payment credentials/);expect(context).not.toContain('computeCredits');expect(context).toContain('cognitionCredits');expect(context).toContain('localCompute');});
});

describe('resource descendants, checkpoints, reports and Owner surface',()=>{
  it('uses a compensating journal entry rather than editing capital history',async()=>{const e=await setup(),s=e.repo.economy,original=s.recordCapital({currency:'USD',amount:500,to:account(e),key:'incorrect-investment'}),history=s.ledger('CAPITAL')[0],id=s.compensate(original,'correction','Owner correction fixture');expect(s.compensate(original,'correction','Owner correction fixture')).toBe(id);expect(s.capital(account(e)).USD!.total).toBe(0);expect(s.ledger('CAPITAL')[0]).toEqual(history);expect(s.ledger('CAPITAL')).toHaveLength(2);expect(()=>s.compensate(original,'another','duplicate correction')).toThrow();expect(s.integrity()).toEqual([]);});
  it('escrows both resources and creates only the exact child endowment, with zero-credit children permitted',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;inject(e,10);inject(e,10,'Toey');const initial=e.repo.economy.total('COGNITION_CREDIT'),p=await e.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:'Child',localComputeContribution:20,cognitionContribution:3}),id=String((p.effects[0]!.proposal as {id:string}).id);expect(e.repo.economy.self(mam.id)).toMatchObject({cognitionCredits:{reserved:3},localCompute:{reserved:20}});const accepted=await e.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId:id,response:'ACCEPT',localComputeContribution:30,cognitionContribution:2});expect(accepted.success).toBe(true);expect(e.repo.economy.self(e.repo.getAgent('Child')!.id)).toMatchObject({cognitionCredits:{total:5},localCompute:{total:50}});expect(e.repo.economy.total('COGNITION_CREDIT')).toBe(initial);expect(e.repo.economy.total('LOCAL_COMPUTE')).toBe(200);expect(e.repo.economy.integrity()).toEqual([]);});
  it('releases both descendant resources on rejection',async()=>{const e=await setup(),mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;inject(e,5);const p=await e.perform(mam.id,{type:'PROPOSE_DESCENDANT',coParentAgentId:toey.id,proposedName:'Unborn',localComputeContribution:50,cognitionContribution:5}),id=String((p.effects[0]!.proposal as {id:string}).id);await e.perform(toey.id,{type:'RESPOND_DESCENDANT_PROPOSAL',proposalId:id,response:'REJECT'});expect(e.repo.economy.self(mam.id)).toMatchObject({cognitionCredits:{available:5,reserved:0},localCompute:{available:100,reserved:0}});});
  it('captures economy accounts, ledgers, holds, requests and model version in a checkpoint',async()=>{const e=await setup();inject(e,2);e.repo.economy.reserve('hold','RESOURCE','COGNITION_CREDIT',account(e),1,'DESCENDANT');e.repo.economy.recordCapital({currency:'THB',amount:200,to:account(e),key:'money'});e.repo.economy.request(e.repo.getAgent('Mam')!.id,{resource:'LOCAL_COMPUTE',amount:50,reason:'capacity'});const cp=await new WorldCheckpointService(e.config.dataDir,e.repo).create('economy-fixture');dirs.push(`${e.config.dataDir}-checkpoints`);const restored=new WorldRepository(path.join(cp.backupPath,'world.sqlite'),{readonly:true});repos.push(restored);expect(restored.economy.version()).toBe(2);expect(restored.economy.accounts()).toEqual(e.repo.economy.accounts());expect(restored.economy.ledger()).toEqual(e.repo.economy.ledger());expect(restored.economy.requests()).toEqual(e.repo.economy.requests());expect(restored.economy.reservation('hold')!.status).toBe('RESERVED');expect(restored.economy.integrity()).toEqual([]);});
  it('reports separate resources and preserves original legacy report fields',async()=>{const e=await setup();inject(e,2);e.resume();const run=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1,maxCognitionCredits:1,maxLocalCompute:100});const report=createRunReport(e.repo,run.runId);expect(report).toMatchObject({initialCognitionCredits:2,remainingCognitionCredits:1,cognitionCreditsConsumed:1,initialLocalCompute:200,remainingLocalCompute:200,localComputeConsumed:0});expect(report).not.toHaveProperty('computeConsumed');const {repo}=await legacy(),old=repo.createAutonomyRun({provider:'historical',initialCompute:3000,computeCeiling:1000});repo.finishAutonomyRun(old.id,1805,'historical');repo.economy.migrateLegacy();expect(createRunReport(repo,old.id)).toMatchObject({initialCompute:3000,remainingCompute:2610,computeConsumed:390});expect(createRunReport(repo,old.id)).not.toHaveProperty('initialCognitionCredits');});
  it('exposes read-only preview/status and authoritative CLI operations with explicit references',async()=>{const {repo}=await legacy();expect(economyCli(repo,['resources','migrate-legacy','--preview'])).toMatchObject({resourceModelVersion:1});expect(economyCli(repo,['resources','migrate-legacy','--apply'])).toMatchObject({applied:true});economyCli(repo,['resources','inject','--resource','COGNITION_CREDIT','--amount','500','--to','Mam','--source','provider_free_allowance','--key','fixture-allowance']);economyCli(repo,['economy','invest','--currency','USD','--amount','1000','--to','Mam','--key','investment']);expect(repo.economy.self(repo.getAgent('Mam')!.id)).toMatchObject({cognitionCredits:{total:500},capital:{USD:{total:1000}}});});
  it('detects corrupted account totals and reservation caches',async()=>{const e=await setup();inject(e,2);e.repo.db.prepare("UPDATE value_accounts SET total=total+1 WHERE unit='COGNITION_CREDIT' AND account=?").run(account(e));expect(e.repo.economy.integrity().join(' ')).toContain('Ledger mismatch');});
  it('keeps read-only migration preview byte-for-byte unchanged across reopen',async()=>{const {repo,dir}=await legacy();repo.close();const file=path.join(dir,'world.sqlite'),before=createHash('sha256').update(await readFile(file)).digest('hex'),r=new WorldRepository(file,{readonly:true});repos.push(r);r.economy.migrationPreview();r.close();expect(createHash('sha256').update(await readFile(file)).digest('hex')).toBe(before);await writeFile(path.join(dir,'fixture-marker'),'fixture');});
});
