import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it,vi } from 'vitest';
import type { CognitionProvider } from '../packages/cognition/src/index.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig,type WorldConfig } from '../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../packages/world/src/runner.js';
const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function engine(provider?:CognitionProvider,sandbox=new FakeExecutionSandbox(()=>({success:true,exitCode:0,stdout:'',stderr:'',timedOut:false,durationMs:1,truncated:false})),overrides:Partial<WorldConfig>={}){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-runner-'));dirs.push(dir);const e=new WorldEngine({...defaultConfig(dir),...overrides},provider,sandbox);await e.genesis();e.resume();return e;}
function currentLeaseToken(e:WorldEngine):string{return(e.repo.db.prepare('SELECT token FROM runner_lease').get() as {token:string}).token;}
describe('continuous runner',()=>{
  it('honors a maximum tick count and releases its database lease',async()=>{const e=await engine();const result=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:2});expect(result).toMatchObject({ticks:2,reason:'maximum ticks reached'});expect(result.runId).toMatch(/^[0-9a-f-]{36}$/);expect(e.repo.getWorld()?.currentTick).toBe(2);expect(e.repo.acquireRunnerLease('later',1_000)).toBe(true);e.close();});
  it('allows two immediate sequential runs to acquire and release independently',async()=>{const e=await engine();const first=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1}),second=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1});expect(first).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(second).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(second.runId).not.toBe(first.runId);expect(e.repo.getWorld()?.currentTick).toBe(2);expect(e.repo.runnerLeaseStatus().present).toBe(false);e.close();});
  it('atomically replaces an expired lease and fences the former owner',async()=>{const e=await engine();expect(e.repo.acquireRunnerLease('old-token',1_000,'old-runner')).toBe(true);e.repo.db.prepare('UPDATE runner_lease SET expires_at=?').run(Date.now()-1);expect(e.repo.acquireRunnerLease('new-token',1_000,'new-runner')).toBe(true);expect(e.repo.renewRunnerLease('old-token',1_000)).toBe(false);expect(e.repo.releaseRunnerLease('old-token')).toBe(false);expect(e.repo.runnerLeaseState('new-token')).toBe('owned');expect(e.repo.runnerLeaseDiagnostic('new-token')).toMatchObject({runnerId:'new-runner',active:true,currentProcessOwner:true});e.repo.releaseRunnerLease('new-token');e.close();});
  it('reports a start failure without a started event when another runner owns the lease',async()=>{const e=await engine();expect(e.repo.acquireRunnerLease('existing',5_000,'existing-runner')).toBe(true);await expect(new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1})).rejects.toThrow('another valid runner owns');const events=e.repo.listEvents(30);expect(events.some((event)=>event.type==='RUNNER_START_FAILED')).toBe(true);expect(events.some((event)=>event.type==='RUNNER_STARTED')).toBe(false);e.repo.releaseRunnerLease('existing');e.close();});
  it('finishes an in-flight cycle before graceful abort and persists shutdown',async()=>{let cognitionStarted!:()=>void;const started=new Promise<void>((resolve)=>{cognitionStarted=resolve;}),provider:CognitionProvider={async think(){cognitionStarted();await new Promise((resolve)=>setTimeout(resolve,20));return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};}};const e=await engine(provider),controller=new AbortController(),running=new ContinuousWorldRunner(e).run({tickMs:100,maxTicks:10,signal:controller.signal});await started;controller.abort();const result=await running;expect(result.reason).toBe('shutdown signal');expect(result.ticks).toBe(1);expect(e.repo.getWorld()?.currentTick).toBe(1);expect(e.repo.listEvents().some((event)=>event.type==='RUNNER_STOPPED')).toBe(true);e.close();});
  it('heartbeats through slow cognition and excludes a second runner',async()=>{let cognitionStarted!:()=>void,calls=0;const started=new Promise<void>((resolve)=>{cognitionStarted=resolve;}),provider:CognitionProvider={async think(){if(calls++===0)cognitionStarted();await new Promise((resolve)=>setTimeout(resolve,200));return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};}};const e=await engine(provider,undefined,{runnerLeaseMs:5_000,runnerHeartbeatMs:50}),renew=vi.spyOn(e.repo,'renewRunnerLease'),running=new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:2});await started;await new Promise((resolve)=>setTimeout(resolve,250));expect(e.repo.acquireRunnerLease('second-runner',5_000)).toBe(false);const result=await running;expect(result).toMatchObject({ticks:2,reason:'maximum ticks reached'});expect(calls).toBe(4);expect(renew.mock.calls.length).toBeGreaterThanOrEqual(3);expect(e.repo.listEvents(200).some((event)=>event.type==='RUNNER_LEASE_LOST')).toBe(false);expect(e.repo.acquireRunnerLease('after-slow-cognition',5_000)).toBe(true);e.repo.releaseRunnerLease('after-slow-cognition');e.close();});
  it('heartbeats while a slow sandbox action executes',async()=>{let executionStarted!:()=>void;const started=new Promise<void>((resolve)=>{executionStarted=resolve;}),provider:CognitionProvider={async think(input){return{thoughtSummary:'act',selectedAction:input.identity.name==='Mam'?{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'slow.js',args:[],stdin:''}:{type:'WAIT',ticks:1}};}},sandbox=new FakeExecutionSandbox(async()=>{executionStarted();await new Promise((resolve)=>setTimeout(resolve,300));return{success:true,exitCode:0,stdout:'ok',stderr:'',timedOut:false,durationMs:300,truncated:false};}),e=await engine(provider,sandbox,{runnerLeaseMs:1_000,runnerHeartbeatMs:50}),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'slow.js',content:'console.log("ok")'});const running=new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1});await started;await new Promise((resolve)=>setTimeout(resolve,200));expect(e.repo.acquireRunnerLease('second-runner',1_000)).toBe(false);const result=await running;expect(result).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(e.repo.executionsFor(mam.id,1)[0]?.success).toBe(true);expect(e.repo.listEvents(200).some((event)=>event.type==='RUNNER_LEASE_LOST')).toBe(false);e.close();});
  it('stops at a safe boundary when the fencing token is replaced and a later runner can start',async()=>{let cognitionStarted!:()=>void;const started=new Promise<void>((resolve)=>{cognitionStarted=resolve;}),provider:CognitionProvider={async think(){cognitionStarted();await new Promise((resolve)=>setTimeout(resolve,80));return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};}};const e=await engine(provider,undefined,{runnerLeaseMs:200,runnerHeartbeatMs:20}),running=new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:3});await started;const token=currentLeaseToken(e);e.repo.releaseRunnerLease(token);expect(e.repo.acquireRunnerLease('replacement-owner',500)).toBe(true);const result=await running;expect(result).toMatchObject({ticks:0,reason:'runner lease lost'});expect(e.repo.getWorld()?.currentTick).toBe(0);expect(e.repo.runnerLeaseState('replacement-owner')).toBe('owned');const loss=e.repo.listEvents(50).find((event)=>event.type==='RUNNER_LEASE_LOST');expect(loss?.payload.reason).toBe('ownership token replaced');expect(e.repo.listEvents(50).filter((event)=>event.type==='COGNITION_TURN_COMPLETED')).toHaveLength(0);e.repo.releaseRunnerLease('replacement-owner');const second=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1});expect(second).toMatchObject({ticks:1,reason:'maximum ticks reached'});e.close();});
  it('fences persistence of a slow execution result after ownership replacement',async()=>{let executionStarted!:()=>void;const started=new Promise<void>((resolve)=>{executionStarted=resolve;}),provider:CognitionProvider={async think(input){return{thoughtSummary:'act',selectedAction:input.identity.name==='Mam'?{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'slow.js',args:[],stdin:''}:{type:'WAIT',ticks:1}};}},sandbox=new FakeExecutionSandbox(async()=>{executionStarted();await new Promise((resolve)=>setTimeout(resolve,80));return{success:true,exitCode:0,stdout:'late',stderr:'',timedOut:false,durationMs:80,truncated:false};}),e=await engine(provider,sandbox,{runnerLeaseMs:200,runnerHeartbeatMs:20}),mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'slow.js',content:'console.log("late")'});const running=new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:2});await started;const token=currentLeaseToken(e);e.repo.releaseRunnerLease(token);expect(e.repo.acquireRunnerLease('replacement-owner',500)).toBe(true);const result=await running,events=e.repo.listEvents(100);expect(result).toMatchObject({ticks:0,reason:'runner lease lost'});expect(e.repo.getWorld()?.currentTick).toBe(0);expect(e.repo.executionsFor(mam.id)).toHaveLength(0);expect(events.some((event)=>event.type==='PROGRAM_EXECUTION_COMPLETED')).toBe(false);expect(e.repo.runnerLeaseState('replacement-owner')).toBe('owned');e.repo.releaseRunnerLease('replacement-owner');e.close();});
  it('keeps heartbeating while all inhabitants wait beyond the lease TTL',async()=>{let calls=0;const provider:CognitionProvider={async think(){calls++;return{thoughtSummary:'wait well beyond this lease',selectedAction:{type:'WAIT',ticks:10}};}};const e=await engine(provider,undefined,{runnerLeaseMs:300,runnerHeartbeatMs:50}),renew=vi.spyOn(e.repo,'renewRunnerLease'),result=await new ContinuousWorldRunner(e).run({tickMs:75,maxTicks:6});expect(result).toMatchObject({ticks:6,reason:'maximum ticks reached'});expect(calls).toBe(2);expect(renew.mock.calls.length).toBeGreaterThanOrEqual(5);expect(e.repo.listEvents(100).some((event)=>event.type==='RUNNER_LEASE_LOST')).toBe(false);expect(e.repo.getWorld()?.currentTick).toBe(6);e.close();});
  it('retries transient SQLite contention in the heartbeat',async()=>{const provider:CognitionProvider={async think(){await new Promise((resolve)=>setTimeout(resolve,200));return{thoughtSummary:'wait',selectedAction:{type:'WAIT',ticks:1}};}},e=await engine(provider,undefined,{runnerLeaseMs:5_000,runnerHeartbeatMs:50}),renew=e.repo.renewRunnerLease.bind(e.repo);let busy=2;const spy=vi.spyOn(e.repo,'renewRunnerLease').mockImplementation((token,ttl)=>{if(busy-->0)throw Object.assign(new Error('busy'),{code:'SQLITE_BUSY'});return renew(token,ttl);});const result=await new ContinuousWorldRunner(e).run({tickMs:0,maxTicks:1});expect(result).toMatchObject({ticks:1,reason:'maximum ticks reached'});expect(spy.mock.calls.length).toBeGreaterThanOrEqual(3);expect(e.repo.listEvents(100).some((event)=>event.type==='RUNNER_LEASE_LOST')).toBe(false);e.close();});
});
