import { readFile,mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup(){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-tools-'));dirs.push(dir);const sandbox=new FakeExecutionSandbox(async(request)=>{const source=await readFile(path.join(request.workspacePath,request.entrypoint),'utf8');const input=JSON.parse(request.stdin||'{}') as {value?:number};const multiplier=/MULTIPLIER\s*=\s*(\d+)/.exec(source)?.[1]??'1';return{success:true,exitCode:0,stdout:`${(input.value??0)*Number(multiplier)}\n`,stderr:'',timedOut:false,durationMs:7,truncated:false};});const engine=new WorldEngine(defaultConfig(dir),undefined,sandbox);await engine.genesis();return engine;}
async function createToolSource(engine:WorldEngine,agentId:string,multiplier=2){await engine.perform(agentId,{type:'CREATE_DIRECTORY',path:'tools/Fluffy/data'});await engine.perform(agentId,{type:'CREATE_TEXT_FILE',path:'tools/Fluffy/main.js',content:`const MULTIPLIER = ${multiplier};\nconst cfg = require('./data/constants.json');\nprocess.stdin.on('data', () => console.log(MULTIPLIER * cfg.base));`});await engine.perform(agentId,{type:'CREATE_TEXT_FILE',path:'tools/Fluffy/data/constants.json',content:'{"base":21}'});}

describe('immutable userland tools',()=>{
  it('snapshots a multi-file program, records provenance, and keeps kernel/userland capabilities distinct',async()=>{const engine=await setup(),toey=engine.repo.getAgent('Toey')!;await createToolSource(engine,toey.id);const published=await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/Fluffy',entrypoint:'main.js',runtime:'node',name:'Fluffy',description:'opaque description',visibility:'SHARED',usage:'JSON stdin'});expect(published.success).toBe(true);const version=(published.effects[0] as any).toolVersion;expect(version).toMatchObject({publisherAgentId:toey.id,publisherName:'Toey',version:1,visibility:'SHARED',runtime:'node',entrypoint:'main.js'});expect(version.manifest).toMatchObject({name:'Fluffy',fileCount:2,totalBytes:expect.any(Number),inputProtocol:'json-stdin',sourceHash:version.sourceHash});expect(await readFile(path.join(engine.tools.storeRoot,version.sourceHash,'data','constants.json'),'utf8')).toBe('{"base":21}');const observation=await engine.observe(toey);expect(observation.kernelCapabilities.some((capability)=>capability.type==='EXECUTE_PROGRAM')).toBe(true);expect(observation.userlandTools.some((tool)=>tool.versionId===version.id)).toBe(true);engine.close();});
  it('supports private visibility and rejects unauthorized inspect and invocation',async()=>{const engine=await setup(),toey=engine.repo.getAgent('Toey')!,mam=engine.repo.getAgent('Mam')!;await createToolSource(engine,toey.id);const result=await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/Fluffy',entrypoint:'main.js',runtime:'node',name:'SecretName',description:'private',visibility:'PRIVATE'}),version=(result.effects[0] as any).toolVersion;expect(engine.repo.accessibleTools(mam.id).some((tool)=>tool.versionId===version.id)).toBe(false);expect((await engine.perform(mam.id,{type:'INSPECT_TOOL',toolVersionId:version.id})).success).toBe(false);expect((await engine.perform(mam.id,{type:'INVOKE_TOOL',toolVersionId:version.id,input:{value:21}})).success).toBe(false);engine.close();});
  it('demonstrates Toey publishing and Mam discovering, inspecting, and invoking real shared artifact output',async()=>{const engine=await setup(),toey=engine.repo.getAgent('Toey')!,mam=engine.repo.getAgent('Mam')!;engine.repo.addMemory(toey.id,'knowledge','Toey private memory',0);await createToolSource(engine,toey.id);const publish=await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/Fluffy',entrypoint:'main.js',runtime:'node',name:'abc',description:'whatever Toey calls it',visibility:'SHARED'}),version=(publish.effects[0] as any).toolVersion,before=engine.repo.getAgent(mam.id)!.computeCredits;const listed=await engine.perform(mam.id,{type:'LIST_TOOLS'}),inspected=await engine.perform(mam.id,{type:'INSPECT_TOOL',toolVersionId:version.id}),invoked=await engine.perform(mam.id,{type:'INVOKE_TOOL',toolVersionId:version.id,input:{value:21}});expect((listed.effects[0] as any).tools).toEqual(expect.arrayContaining([expect.objectContaining({versionId:version.id,publisherName:'Toey',name:'abc'})]));expect((inspected.effects[0] as any).toolVersion.sourceHash).toBe(version.sourceHash);expect(invoked.success).toBe(true);expect((invoked.effects[0] as any).execution.stdout).toBe('42\n');expect(engine.repo.getAgent(mam.id)!.computeCredits).toBeLessThan(before);expect(engine.repo.executionsFor(mam.id)[0]?.entrypoint).toContain(version.id);expect(engine.repo.memoriesFor(mam.id).some((memory)=>memory.content.includes('Toey private memory'))).toBe(false);await expect(engine.files.inspectFile(mam.id,`../../../system/tool-store/${version.sourceHash}/main.js`)).rejects.toThrow(/traversal/i);engine.close();});
  it('keeps old versions immutable, creates newer versions, and survives restart with history',async()=>{const engine=await setup(),dir=engine.config.dataDir,toey=engine.repo.getAgent('Toey')!;await createToolSource(engine,toey.id,2);const first=(await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/Fluffy',entrypoint:'main.js',runtime:'node',name:'Fluffy',description:'v1',visibility:'SHARED'})).effects[0] as any;await engine.perform(toey.id,{type:'WRITE_FILE',path:'tools/Fluffy/main.js',content:'const MULTIPLIER = 3;'});const second=(await engine.perform(toey.id,{type:'PUBLISH_TOOL',sourceDirectory:'tools/Fluffy',entrypoint:'main.js',runtime:'node',name:'Fluffy',description:'v2',visibility:'SHARED',previousVersionId:first.toolVersion.id})).effects[0] as any;expect(second.toolVersion).toMatchObject({version:2,previousVersionId:first.toolVersion.id});expect(second.toolVersion.sourceHash).not.toBe(first.toolVersion.sourceHash);expect(await readFile(path.join(engine.tools.storeRoot,first.toolVersion.sourceHash,'main.js'),'utf8')).toContain('MULTIPLIER = 2');engine.close();const restarted=new WorldEngine(defaultConfig(dir));await restarted.initialize();expect(restarted.repo.getToolVersion(first.toolVersion.id)?.version).toBe(1);expect(restarted.repo.getToolVersion(second.toolVersion.id)?.version).toBe(2);restarted.close();});
  it('performs bounded private/shared text search without leaking private artifacts',async()=>{const engine=await setup(),mam=engine.repo.getAgent('Mam')!,toey=engine.repo.getAgent('Toey')!;await engine.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'private.txt',content:'needle private'});await engine.perform(toey.id,{type:'CREATE_TEXT_FILE',space:'SHARED',path:'shared.txt',content:'needle shared\nsecond'});const privateSearch=await engine.perform(mam.id,{type:'SEARCH_TEXT',space:'PRIVATE',query:'needle',maxResults:1}),sharedSearch=await engine.perform(mam.id,{type:'SEARCH_TEXT',space:'SHARED',query:'needle',maxResults:20});expect((privateSearch.effects[0] as any).results).toEqual([{path:'private.txt',line:1,excerpt:'needle private'}]);expect((sharedSearch.effects[0] as any).results).toEqual([{path:'shared.txt',line:1,excerpt:'needle shared'}]);expect((sharedSearch.effects[0] as any).results.some((item:any)=>item.path==='private.txt')).toBe(false);engine.close();});
});
