import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { DeterministicCognitionProvider } from '../packages/cognition/src/index.js';
import { WorldEngine, defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];
async function makeEngine(actions:any[]=[{type:'WAIT'}]){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-'));dirs.push(dir);return new WorldEngine(defaultConfig(dir),new DeterministicCognitionProvider(actions));}
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});

describe('persistent autonomous world',()=>{
  it('Genesis is idempotent and creates exactly Mam and Toey with stable IDs',async()=>{const e=await makeEngine();const first=await e.genesis(),ids=first.agents.map((a)=>a.id);expect(first.created).toBe(true);const second=await e.genesis();expect(second.created).toBe(false);expect(second.agents.map((a)=>a.name)).toEqual(['Mam','Toey']);expect(second.agents.map((a)=>a.id)).toEqual(ids);e.close();});
  it('Scenario A: WAIT advances and persists one deterministic tick',async()=>{const e=await makeEngine([{type:'WAIT'},{type:'WAIT'}]);await e.genesis();await e.tick();expect(e.repo.getWorld()?.currentTick).toBe(1);expect(e.repo.listEvents().some((x)=>x.type==='AGENT_WAITED')).toBe(true);e.close();});
  it('Scenario B: creates a real private artifact and consumes storage',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!;const r=await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'notes/hello.txt',content:'hello'});expect(r.success).toBe(true);expect(await readFile(path.join(e.config.dataDir,'agents',mam.id,'workspace','notes','hello.txt'),'utf8')).toBe('hello');expect(e.repo.getAgent(mam.id)?.storageBytes).toBe(5);expect(e.repo.listEvents().some((x)=>x.type==='FILE_CREATED')).toBe(true);e.close();});
  it('Scenario C: persists private addressed messages across restart',async()=>{const e=await makeEngine();await e.genesis();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:'Toey',content:'hello'});expect(e.repo.messagesFor(toey.id)).toHaveLength(1);expect(e.repo.messagesFor(mam.id)).toHaveLength(0);e.close();const restarted=new WorldEngine(defaultConfig(dir));expect(restarted.repo.messagesFor(toey.id)[0]?.content).toBe('hello');restarted.close();});
  it('Scenario D: rejects traversal and logs a security event',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!;const r=await e.perform(mam.id,{type:'READ_FILE',path:'../../../../etc/passwd',area:'private'});expect(r.success).toBe(false);expect(e.repo.listEvents()[0]?.type).toBe('SECURITY_VIOLATION');e.close();});
  it('isolates private workspaces and rejects absolute and malformed actions',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(toey.id,{type:'CREATE_TEXT_FILE',path:'secret.txt',content:'private'});expect((await e.perform(mam.id,{type:'READ_FILE',path:`../../${toey.id}/workspace/secret.txt`})).success).toBe(false);expect((await e.perform(mam.id,{type:'READ_FILE',path:'C:\\Windows\\win.ini'})).success).toBe(false);expect((await e.perform(mam.id,{type:'SHELL',command:'env'})).success).toBe(false);e.close();});
  it('Scenario E: restart preserves IDs, tick, memories, messages, and artifacts',async()=>{const e=await makeEngine([{type:'WAIT'},{type:'WAIT'}]);await e.genesis();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'durable.txt',content:'yes'});await e.perform(mam.id,{type:'SEND_MESSAGE',to:'Toey',content:'persist'});e.repo.addMemory(mam.id,'knowledge','I recorded this.',0);await e.tick();e.close();const r=new WorldEngine(defaultConfig(dir));await r.genesis();expect(r.repo.getAgent('Mam')?.id).toBe(mam.id);expect(r.repo.getAgent('Toey')?.id).toBe(toey.id);expect(r.repo.getWorld()?.currentTick).toBe(1);expect(r.repo.memoriesFor(mam.id).length).toBeGreaterThan(0);expect(r.repo.messagesFor(toey.id)[0]?.content).toBe('persist');expect(await r.files.read(mam.id,'durable.txt')).toBe('yes');expect(r.repo.listAgents()).toHaveLength(2);r.close();});
  it('distinguishes Owner messages without granting command authority',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!;e.ownerMessage('Mam','Hello');expect(e.repo.messagesFor(mam.id)[0]).toMatchObject({fromType:'owner',fromId:'owner:external',content:'Hello'});e.close();});
});
