import { mkdtemp,readFile,rm,symlink,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import { DeterministicCognitionProvider,type CognitionInput } from '../packages/cognition/src/index.js';
import { FakeExecutionSandbox } from '../packages/sandbox/src/docker.js';
import type { ExecutionSandbox } from '../packages/sandbox/src/filesystem.js';
import type { AgentAction } from '../packages/tools/src/actions.js';
import { WorldEngine,defaultConfig } from '../packages/world/src/engine.js';

const dirs:string[]=[];
const fakeResult={success:true,exitCode:0,stdout:'42\n',stderr:'',timedOut:false,durationMs:82,truncated:false};
async function makeEngine(actions:AgentAction[]|((input:CognitionInput)=>AgentAction)=[{type:'WAIT',ticks:1}],sandbox:ExecutionSandbox=new FakeExecutionSandbox(()=>fakeResult),hooks:ConstructorParameters<typeof WorldEngine>[3]={}){const dir=await mkdtemp(path.join(tmpdir(),'ai-world-'));dirs.push(dir);return new WorldEngine(defaultConfig(dir),new DeterministicCognitionProvider(actions),sandbox,hooks);}
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});

describe('Milestone 1 invariants',()=>{
  it('keeps Genesis idempotent with exactly Mam and Toey and stable IDs',async()=>{const e=await makeEngine();const first=await e.genesis(),ids=first.agents.map((a)=>a.id);expect((await e.genesis()).agents.map((a)=>a.id)).toEqual(ids);expect(e.repo.listAgents().map((a)=>a.name)).toEqual(['Mam','Toey']);e.close();});
  it('WAIT advances and persists one running tick',async()=>{const e=await makeEngine([{type:'WAIT',ticks:1},{type:'WAIT',ticks:1}]);await e.genesis();e.resume();await e.tick();expect(e.repo.getWorld()?.currentTick).toBe(1);expect(e.repo.listEvents().some((x)=>x.type==='AGENT_WAITED')).toBe(true);e.close();});
  it('creates a real private artifact and consumes storage',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!;expect((await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'notes/hello.txt',content:'hello'})).success).toBe(true);expect(await readFile(path.join(e.config.dataDir,'agents',mam.id,'workspace','notes','hello.txt'),'utf8')).toBe('hello');expect(e.repo.getAgent(mam.id)?.storageBytes).toBe(5);e.close();});
  it('persists addressed messages and keeps them recipient-private',async()=>{const e=await makeEngine();await e.genesis();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(mam.id,{type:'SEND_MESSAGE',to:'Toey',content:'hello'});expect(e.repo.messagesFor(mam.id)).toHaveLength(0);e.close();const r=new WorldEngine(defaultConfig(dir));expect(r.repo.messagesFor(toey.id)[0]?.content).toBe('hello');r.close();});
  it('restart preserves identity, tick, memories, messages, artifacts, and population',async()=>{const e=await makeEngine([{type:'WAIT',ticks:1},{type:'WAIT',ticks:1}]);await e.genesis();e.resume();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'durable.txt',content:'yes'});await e.perform(mam.id,{type:'SEND_MESSAGE',to:'Toey',content:'persist'});e.repo.addMemory(mam.id,'knowledge','I recorded this.',0);await e.tick();e.close();const r=new WorldEngine(defaultConfig(dir));await r.genesis();expect(r.repo.getAgent('Mam')?.id).toBe(mam.id);expect(r.repo.getWorld()?.currentTick).toBe(1);expect(r.repo.memoriesFor(mam.id)).toHaveLength(1);expect(r.repo.messagesFor(toey.id)).toHaveLength(1);expect((await r.files.read(mam.id,'durable.txt')).content).toBe('yes');expect(r.repo.listAgents()).toHaveLength(2);r.close();});
});

describe('filesystem security and atomicity',()=>{
  it.each(['../secret','..\\secret','a/../../secret','a\\..\\..\\secret','C:\\Windows\\win.ini','C:/Windows/win.ini','/etc/passwd','\\\\server\\share\\x'])(`rejects hostile path %s and audits it`,async(hostile)=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!;expect((await e.perform(mam.id,{type:'READ_FILE',path:hostile})).success).toBe(false);expect(e.repo.listEvents()[0]?.type).toBe('SECURITY_VIOLATION');e.close();});
  it('blocks another workspace, the world database, and configuration through traversal',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;for(const hostile of [`../../${toey.id}/workspace/private.txt`,'../../../world.sqlite','../../../../../.env'])expect((await e.perform(mam.id,{type:'READ_FILE',path:hostile})).success).toBe(false);e.close();});
  it('rejects existing symlink or junction redirection where supported',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,outside=await mkdtemp(path.join(tmpdir(),'ai-world-outside-'));dirs.push(outside);await writeFile(path.join(outside,'secret.txt'),'host secret');const link=path.join(e.files.root(mam.id,'private'),'escape');try{await symlink(outside,link,process.platform==='win32'?'junction':'dir');}catch(error){if((error as NodeJS.ErrnoException).code==='EPERM'){e.close();return;}throw error;}const result=await e.perform(mam.id,{type:'READ_FILE',path:'escape/secret.txt'});expect(result.success).toBe(false);expect(result.error).toMatch(/links|canonical|reparse/i);e.close();});
  it('leaves original content and accounting intact when a staged write is interrupted',async()=>{const e=await makeEngine();await e.genesis();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'safe.txt',content:'original'});const before=e.repo.getAgent(mam.id)!.storageBytes;e.close();const failed=new WorldEngine(defaultConfig(dir),new DeterministicCognitionProvider(),new FakeExecutionSandbox(()=>fakeResult),{onWriteStage(point){if(point==='after-stage')throw new Error('injected interruption');}});const result=await failed.perform(mam.id,{type:'WRITE_FILE',path:'safe.txt',content:'replacement'});expect(result.success).toBe(false);expect((await failed.files.read(mam.id,'safe.txt')).content).toBe('original');expect(failed.repo.getAgent(mam.id)?.storageBytes).toBe(before);expect((await failed.files.list(mam.id)).some((name)=>name.includes('.aw-stage-'))).toBe(false);failed.close();});
  it('requires a matching hash before overwriting existing shared content',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(toey.id,{type:'CREATE_TEXT_FILE',space:'SHARED',path:'note.txt',content:'one'});expect((await e.perform(mam.id,{type:'WRITE_FILE',space:'SHARED',path:'note.txt',content:'two'})).success).toBe(false);const hash=(await e.files.read(mam.id,'note.txt','shared')).hash;expect((await e.perform(mam.id,{type:'WRITE_FILE',space:'SHARED',path:'note.txt',content:'two',expectedHash:hash})).success).toBe(true);e.close();});
});

describe('causal execution, shared collaboration, and learning',()=>{
  it('closes artifact → execution → observation → memory and survives restart',async()=>{let requestSeen='';const sandbox=new FakeExecutionSandbox((request)=>{requestSeen=`${request.runtime}:${request.entrypoint}`;return fakeResult;});const actions=(input:CognitionInput):AgentAction=>input.identity.name==='Mam'?(input.currentObservation.tick===0?{type:'CREATE_TEXT_FILE',path:'experiments/math.js',content:'console.log(21 * 2);'}:{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'experiments/math.js',args:[],stdin:''}):{type:'WAIT',ticks:2};const e=await makeEngine(actions,sandbox);await e.genesis();e.resume();const dir=e.config.dataDir,mam=e.repo.getAgent('Mam')!;await e.tick();await e.tick();expect(requestSeen).toBe('node:experiments/math.js');expect(e.repo.executionsFor(mam.id)[0]?.stdout).toBe('42\n');expect((await e.observe(e.repo.getAgent(mam.id)!)).recentExecutions[0]?.stdout).toBe('42\n');expect(e.repo.memoriesFor(mam.id).some((m)=>m.content.includes('stdout=42'))).toBe(true);const remaining=e.repo.getAgent(mam.id)!.computeCredits;expect(remaining).toBeLessThan(10_000);e.close();const r=new WorldEngine(defaultConfig(dir));expect(r.repo.executionsFor(mam.id)[0]?.stdout).toBe('42\n');expect((await r.files.read(mam.id,'experiments/math.js')).content).toContain('21 * 2');r.close();});
  it('uses a shared artifact as the only causal knowledge-transfer path',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;e.repo.addMemory(toey.id,'knowledge','private Toey knowledge',0);await e.perform(toey.id,{type:'CREATE_TEXT_FILE',space:'SHARED',path:'discovery.txt',content:'shared discovery'});const listed=await e.perform(mam.id,{type:'LIST_FILES',space:'SHARED',path:'.'}),read=await e.perform(mam.id,{type:'READ_FILE',space:'SHARED',path:'discovery.txt'});expect(listed.effects[0]?.files).toContain('discovery.txt');expect(read.effects[0]?.content).toBe('shared discovery');expect(e.repo.memoriesFor(mam.id).some((m)=>m.content.includes('private Toey'))).toBe(false);e.close();});
  it('ranks relevant isolated memories and deduplicates consecutive equivalents',async()=>{const e=await makeEngine();await e.genesis();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;e.repo.addMemory(mam.id,'episodic','Python syntax error in experiment',1,{salience:0.9,tags:['python']});e.repo.addMemory(mam.id,'reflection','waited',2);e.repo.addMemory(mam.id,'reflection','waited',3);e.repo.addMemory(toey.id,'knowledge','Python secret',4,{salience:1});expect(e.repo.relevantMemories(mam.id,'python error',10)[0]?.content).toContain('Python syntax');expect(e.repo.memoriesFor(mam.id).find((m)=>m.content==='waited')?.occurrences).toBe(2);expect(e.repo.relevantMemories(mam.id,'secret',10).some((m)=>m.content.includes('secret'))).toBe(false);e.close();});
  it('does not start execution without the maximum resource reservation',async()=>{let called=false;const e=await makeEngine([],new FakeExecutionSandbox(()=>{called=true;return fakeResult;}));await e.genesis();const mam=e.repo.getAgent('Mam')!;await e.perform(mam.id,{type:'CREATE_TEXT_FILE',path:'x.js',content:'0'});e.repo.updateResources(mam.id,50,1);const result=await e.perform(mam.id,{type:'EXECUTE_PROGRAM',runtime:'node',entrypoint:'x.js'});expect(result.success).toBe(false);expect(called).toBe(false);expect(e.repo.getAgent(mam.id)?.computeCredits).toBe(50);e.close();});
});

describe('pause, sleep, resources, and runner lease',()=>{
  it('persists pause/resume and performs no paused cycles',async()=>{const e=await makeEngine();await e.genesis();expect(await e.tick()).toEqual([]);expect(e.repo.getWorld()?.currentTick).toBe(0);e.resume();await e.tick();e.pause();const dir=e.config.dataDir;e.close();const r=new WorldEngine(defaultConfig(dir));expect(r.repo.getWorld()).toMatchObject({status:'paused',currentTick:1});r.close();});
  it('skips sleeping agents and direct messages wake them',async()=>{const e=await makeEngine();await e.genesis();e.resume();const mam=e.repo.getAgent('Mam')!,toey=e.repo.getAgent('Toey')!;await e.perform(mam.id,{type:'WAIT',ticks:10},0);await e.tick();expect(e.repo.listEvents().filter((x)=>x.tick===1&&x.actorId===mam.id&&x.type==='AGENT_WAITED')).toHaveLength(0);await e.perform(toey.id,{type:'SEND_MESSAGE',to:'Mam',content:'wake'},1);expect(e.repo.getAgent(mam.id)?.sleepingUntilTick).toBe(1);e.close();});
  it('keeps a compute-starved agent persistent and accepts Owner messages',async()=>{const e=await makeEngine();await e.genesis();e.resume();const mam=e.repo.getAgent('Mam')!;e.repo.updateResources(mam.id,0,0);await e.tick();e.ownerMessage('Mam','still here');expect(e.repo.getAgent('Mam')).not.toBeNull();expect(e.repo.messagesFor(mam.id)[0]?.fromType).toBe('owner');e.close();});
  it('prevents a second active runner lease and permits clean release',async()=>{const e=await makeEngine();await e.genesis();expect(e.repo.acquireRunnerLease('one',30_000)).toBe(true);expect(e.repo.acquireRunnerLease('two',30_000)).toBe(false);e.repo.releaseRunnerLease('one');expect(e.repo.acquireRunnerLease('two',30_000)).toBe(true);e.close();});
});
