import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { DeterministicCognitionProvider,type CognitionInput,type CognitionProvider,type Observation } from '../../cognition/src/index.js';
import { WorldRepository } from '../../persistence/src/repository.js';
import { AgentFilesystem,type ExecutionSandbox } from '../../sandbox/src/filesystem.js';
import { DockerExecutionSandbox } from '../../sandbox/src/docker.js';
import { BOOTSTRAP_INSTRUCTION,CAPABILITIES,CAPABILITY_DESCRIPTIONS,GENESIS_NAMES,OWNER_ID,type AgentRecord,type ExecutionResult,type RunPreflightSnapshot } from '../../shared/src/index.js';
import { actionSpace,AgentActionSchema,type ActionResult,type AgentAction } from '../../tools/src/actions.js';
import { FilesystemMutationCoordinator,type MutationHooks } from '../../operations/src/reconciliation.js';
import { UserlandToolStore } from '../../userland/src/store.js';
import { OwnerIngressService } from '../../messaging/src/ingress.js';

export interface WorldConfig{dataDir:string;initialComputeCredits:number;initialStorageBytes:number;computeCostPerTurn:number;computeCostPerAction:number;executionBaseCost:number;executionMaxCost:number;maxFileBytes:number;ownerMaxMessageBytes:number;ownerMaxQueued:number;ownerDeliveriesPerWorldHour:number;runnerLeaseMs:number;}
export const defaultConfig=(dataDir=process.env.WORLD_DATA_DIR??'world-data'):WorldConfig=>({dataDir:path.resolve(dataDir),initialComputeCredits:10_000,initialStorageBytes:1_048_576,computeCostPerTurn:5,computeCostPerAction:1,executionBaseCost:25,executionMaxCost:100,maxFileBytes:64*1024,ownerMaxMessageBytes:4_000,ownerMaxQueued:100,ownerDeliveriesPerWorldHour:3,runnerLeaseMs:30_000});

export class WorldEngine{
  readonly repo:WorldRepository;readonly files:AgentFilesystem;readonly mutations:FilesystemMutationCoordinator;readonly tools:UserlandToolStore;readonly ownerIngress:OwnerIngressService;private initialized=false;
  constructor(readonly config=defaultConfig(),readonly cognition:CognitionProvider=new DeterministicCognitionProvider(),readonly executionSandbox:ExecutionSandbox=new DockerExecutionSandbox(),filesystemHooks:ConstructorParameters<typeof AgentFilesystem>[2]={},mutationHooks:MutationHooks={}){this.repo=new WorldRepository(path.join(config.dataDir,'world.sqlite'));this.files=new AgentFilesystem(config.dataDir,config.maxFileBytes,filesystemHooks);this.mutations=new FilesystemMutationCoordinator(this.repo,this.files,mutationHooks);this.tools=new UserlandToolStore(config.dataDir,this.repo,this.files);this.ownerIngress=new OwnerIngressService(this.repo);}
  close():void{this.repo.close();}
  async initialize():Promise<void>{if(this.initialized)return;await this.files.initializeShared();for(const agent of this.repo.listAgents())await this.files.initializeAgent(agent.id);const world=this.repo.getWorld();if(world){await this.mutations.reconcile(world.currentTick);if(this.repo.clearExpiredRunnerLease())this.repo.addEvent('STALE_RUNNER_LEASE_CLEARED',world.currentTick,null,null,{});}this.initialized=true;}
  async genesis():Promise<{created:boolean;agents:AgentRecord[]}>{await this.files.initializeShared();let created=false;this.repo.transaction(()=>{const world=this.repo.getWorld();if(!world){const now=new Date().toISOString();this.repo.createWorld({id:randomUUID(),createdAt:now,currentTick:0,simulatedTime:now,status:'paused'});this.repo.addEvent('WORLD_CREATED',0,null,null,{});created=true;}for(const name of GENESIS_NAMES){const existing=this.repo.getAgent(name);if(!existing){const agent:AgentRecord={id:randomUUID(),name,createdAt:new Date().toISOString(),generation:0,parentIds:[],status:'active',cognitionConfig:{provider:'world-selected'},capabilities:[...CAPABILITIES],metadata:{genesis:true},computeCredits:this.config.initialComputeCredits,storageBytes:0,sleepingUntilTick:0};this.repo.createAgent(agent);this.repo.addEvent('AGENT_CREATED',0,null,agent.id,{name,generation:0});created=true;}else{const upgraded=[...new Set([...existing.capabilities,...CAPABILITIES])];this.repo.updateCapabilities(existing.id,upgraded);}}});for(const agent of this.repo.listAgents())await this.files.initializeAgent(agent.id);await this.initialize();return{created,agents:this.repo.listAgents()};}
  private requireWorld(){const world=this.repo.getWorld();if(!world)throw new Error('World does not exist. Run genesis first.');return world;}
  pause():void{const world=this.requireWorld();if(world.status!=='paused'){this.repo.setWorldStatus('paused');this.repo.addEvent('WORLD_PAUSED',world.currentTick,OWNER_ID,null,{})}}
  resume():void{const world=this.requireWorld();if(world.status!=='running'){this.repo.setWorldStatus('running');this.repo.addEvent('WORLD_RESUMED',world.currentTick,OWNER_ID,null,{})}}
  async observe(agent:AgentRecord):Promise<Observation>{await this.initialize();const world=this.requireWorld();let privateArtifacts:string[]=[],sharedArtifacts:string[]=[];try{privateArtifacts=await this.files.list(agent.id);}catch{privateArtifacts=[];}try{sharedArtifacts=await this.files.list(agent.id,'.','shared');}catch{sharedArtifacts=[];}const kernelCapabilities=CAPABILITY_DESCRIPTIONS.filter((item)=>agent.capabilities.includes(item.type));return{tick:world.currentTick,self:agent,nearbyOrRelevantEvents:this.repo.listEvents(30).filter((event)=>!event.actorId||event.actorId===agent.id||event.subjectId===agent.id).map((event)=>({type:event.type,tick:event.tick,summary:event.payload})),privateArtifacts,sharedArtifacts,receivedMessages:this.repo.messagesFor(agent.id),recentExecutions:this.repo.executionsFor(agent.id,5),accessibleResources:{computeCredits:agent.computeCredits,storageBytes:agent.storageBytes},kernelCapabilities,userlandTools:this.repo.accessibleTools(agent.id),availableCapabilities:kernelCapabilities};}
  private async buildInput(agent:AgentRecord):Promise<CognitionInput>{const observation=await this.observe(agent),query=[...observation.receivedMessages.map((m)=>m.content),...observation.recentExecutions.flatMap((e)=>[e.stdout,e.stderr,e.error??''])].join(' ');const relevantMemories=this.repo.relevantMemories(agent.id,query,observation.tick);return{identity:{id:agent.id,name:agent.name,bootstrapInstruction:BOOTSTRAP_INSTRUCTION},currentObservation:observation,relevantMemories,availableActions:observation.availableCapabilities,currentResources:observation.accessibleResources,recentMessages:observation.receivedMessages};}
  async capturePreflight(modelIdentifier:string):Promise<RunPreflightSnapshot>{await this.initialize();const world=this.requireWorld(),agents=this.repo.listAgents(),snapshots=[];for(const agent of agents)snapshots.push({agentId:agent.id,name:agent.name,computeCredits:agent.computeCredits,storageBytes:agent.storageBytes,memoryCount:this.repo.memoryCount(agent.id),messageCount:this.repo.messageCount(agent.id),privateFileCount:await this.files.countFiles(agent.id,'private')});return{capturedAt:new Date().toISOString(),startTick:world.currentTick,worldStatus:world.status,modelIdentifier,agents:snapshots,sharedFileCount:agents[0]?await this.files.countFiles(agents[0].id,'shared'):0,publishedToolCount:this.repo.allToolVersions().length};}
  async tick(runId?:string):Promise<ActionResult[]>{const world=this.requireWorld();if(world.status==='paused')return[];const tick=world.currentTick+1,results:ActionResult[]=[];for(const snapshot of this.repo.listAgents().filter((agent)=>agent.status==='active')){const agent=this.repo.getAgent(snapshot.id)!;if(agent.sleepingUntilTick>tick)continue;if(agent.computeCredits<this.config.computeCostPerTurn){this.repo.addEvent('ACTION_FAILED',tick,agent.id,null,{error:'Insufficient compute credits for cognition',...(runId?{runId}:{})});continue;}this.repo.updateResources(agent.id,agent.computeCredits-this.config.computeCostPerTurn,agent.storageBytes);try{const input=await this.buildInput(this.repo.getAgent(agent.id)!);if(runId)this.repo.addEvent('MEMORY_RETRIEVED',tick,agent.id,null,{runId,memoryIds:input.relevantMemories.map((memory)=>memory.id),memoryTicks:input.relevantMemories.map((memory)=>memory.tick)});const output=await this.cognition.think(input),metadata=output.reasoningMetadata??{};if(metadata.providerError)this.repo.addEvent('COGNITION_PROVIDER_ERROR',tick,agent.id,null,{error:metadata.providerError,attempts:metadata.providerAttempts,...(runId?{runId}:{})});const result=await this.perform(agent.id,output.selectedAction,tick);results.push(result);if(runId){this.repo.addEvent('COGNITION_TURN_COMPLETED',tick,agent.id,null,{runId,actionType:output.selectedAction.type,actionId:result.actionId,success:result.success,inputTokens:Number(metadata.inputTokens??0),outputTokens:Number(metadata.outputTokens??0),providerLatencyMs:Number(metadata.providerLatencyMs??0),providerRequestSucceeded:metadata.providerRequestSucceeded!==false});this.repo.addEvent('AUTONOMY_ACTION',tick,agent.id,null,{runId,actionType:output.selectedAction.type,actionId:result.actionId,success:result.success,...this.actionFacts(output.selectedAction,result)});}if(!(output.selectedAction.type==='WAIT'&&output.thoughtSummary===`Selected ${output.selectedAction.type}.`))this.repo.addMemory(agent.id,'reflection',output.thoughtSummary,tick,{salience:0.4});}catch(error){const message=error instanceof Error?error.message:'Unknown cognition failure';this.repo.addEvent('COGNITION_PROVIDER_ERROR',tick,agent.id,null,{error:message,...(runId?{runId}:{})});results.push({success:false,actionId:randomUUID(),agentId:agent.id,tick,effects:[],error:message});}}const simulated=new Date(Date.parse(world.simulatedTime)+60_000).toISOString();this.repo.setTick(tick,simulated);this.repo.addEvent('TICK_COMPLETED',tick,null,null,{actions:results.length,...(runId?{runId}:{})});return results;}
  async run(ticks:number):Promise<ActionResult[][]>{const all:ActionResult[][]=[];for(let i=0;i<ticks;i++){if(this.requireWorld().status==='paused')break;all.push(await this.tick());}return all;}
  async perform(agentId:string,untrusted:unknown,tick=this.requireWorld().currentTick):Promise<ActionResult>{await this.initialize();const actionId=randomUUID(),effects:Record<string,unknown>[]=[];let action:AgentAction;try{action=AgentActionSchema.parse(untrusted);}catch{return this.fail(actionId,agentId,tick,'Malformed action rejected');}const agent=this.repo.getAgent(agentId);if(!agent)throw new Error('Unknown agent');if(!agent.capabilities.includes(action.type))return this.fail(actionId,agentId,tick,'Capability not available',action);if(agent.computeCredits<this.config.computeCostPerAction)return this.fail(actionId,agentId,tick,'Insufficient compute credits',action);try{const proposedBytes='content'in action?Buffer.byteLength(action.content):0;if(agent.storageBytes+proposedBytes>this.config.initialStorageBytes)throw new Error('Storage quota exceeded');let storageDelta=0,extraCompute=0,actionSuccess=true,actionError:string|undefined;
      switch(action.type){
        case'WAIT':this.repo.setSleepingUntil(agentId,tick+action.ticks);effects.push({waitedTicks:action.ticks,wakeTick:tick+action.ticks});this.repo.addEvent('AGENT_WAITED',tick,agentId,null,{ticks:action.ticks});break;
        case'SEND_MESSAGE':if(action.to.toLowerCase()===OWNER_ID){if(Buffer.byteLength(action.content)>this.config.ownerMaxMessageBytes)throw new Error('Owner message exceeds delivery size limit');const outbox=this.repo.queueOwnerMessage(agent,tick,action.content,this.config.ownerMaxQueued,this.config.ownerDeliveriesPerWorldHour);effects.push({outboxId:outbox.id,status:outbox.status,to:OWNER_ID});this.repo.addEvent('OWNER_MESSAGE_QUEUED',tick,agentId,OWNER_ID,{outboxId:outbox.id});}else{const recipient=this.repo.getAgent(action.to);if(!recipient)throw new Error('Recipient not found');const message=this.repo.sendMessage(agentId,'agent',recipient.id,tick,action.content);effects.push({messageId:message.id,toAgentId:recipient.id});this.repo.addEvent('MESSAGE_SENT',tick,agentId,recipient.id,{messageId:message.id});}break;
        case'CREATE_TEXT_FILE':{const space=actionSpace(action),result=await this.mutations.mutate({agentId,space,path:action.path,kind:'create',content:action.content,tick,eventType:'FILE_CREATED'});effects.push({operationId:result.operationId,path:action.path,space:space.toUpperCase(),bytes:result.mutation.after,hash:result.mutation.hash,revision:result.revision});break;}
        case'WRITE_FILE':case'APPEND_FILE':{const space=actionSpace(action),result=await this.mutations.mutate({agentId,space,path:action.path,kind:action.type==='WRITE_FILE'?'write':'append',content:action.content,...(action.expectedHash!==undefined?{expectedHash:action.expectedHash}:{}),tick,eventType:'FILE_UPDATED'});effects.push({operationId:result.operationId,path:action.path,space:space.toUpperCase(),bytes:result.mutation.after,hash:result.mutation.hash,revision:result.revision});break;}
        case'READ_FILE':{const space=actionSpace(action),file=await this.files.read(agentId,action.path,space);effects.push({path:action.path,space:space.toUpperCase(),...file});this.repo.addEvent('FILE_READ',tick,agentId,null,{path:action.path,space:space.toUpperCase(),hash:file.hash});break;}
        case'LIST_FILES':{const space=actionSpace(action),files=await this.files.list(agentId,action.path,space);effects.push({path:action.path,space:space.toUpperCase(),files});break;}
        case'CREATE_DIRECTORY':{const space=actionSpace(action);await this.files.mkdir(agentId,action.path,space);effects.push({path:action.path,space:space.toUpperCase()});this.repo.addEvent('DIRECTORY_CREATED',tick,agentId,null,{path:action.path,space:space.toUpperCase()});break;}
        case'EXECUTE_PROGRAM':{if(agent.computeCredits<this.config.computeCostPerAction+this.config.executionMaxCost)throw new Error('Insufficient compute credits to reserve isolated execution');await this.files.assertExecutable(agentId,action.entrypoint);this.repo.addEvent('PROGRAM_EXECUTION_STARTED',tick,agentId,null,{runtime:action.runtime,entrypoint:action.entrypoint});const result=await this.executionSandbox.execute({runtime:action.runtime,workspacePath:this.files.root(agentId,'private'),entrypoint:action.entrypoint,args:action.args,stdin:action.stdin});const record=this.repo.recordExecution(agentId,tick,action.runtime,action.entrypoint,action.args,result);extraCompute=this.executionCost(result);effects.push({execution:record});actionSuccess=result.success;actionError=result.error??(!result.success?`Program exited with ${result.exitCode}`:undefined);this.repo.addEvent(result.success?'PROGRAM_EXECUTION_COMPLETED':result.timedOut||result.truncated?'SANDBOX_LIMIT_EXCEEDED':'PROGRAM_EXECUTION_FAILED',tick,agentId,null,{executionId:record.id,runtime:action.runtime,entrypoint:action.entrypoint,exitCode:result.exitCode,durationMs:result.durationMs,timedOut:result.timedOut,truncated:result.truncated,stdout:result.stdout,stderr:result.stderr,error:result.error,infrastructureFailure:this.infrastructureFailure(result)});const evidence=`Execution ${action.runtime} ${action.entrypoint}: ${result.success?'succeeded':`failed${result.error?`: ${result.error}`:''}`}; exit=${result.exitCode}; stdout=${result.stdout}; stderr=${result.stderr}`.slice(0,4_000);this.repo.addMemory(agentId,'episodic',evidence,tick,{salience:0.8,tags:['execution',action.runtime,action.entrypoint]});break;}
        case'PUBLISH_TOOL':{const published=await this.tools.publish(agent,tick,{sourceDirectory:action.sourceDirectory,entrypoint:action.entrypoint,runtime:action.runtime,name:action.name,description:action.description,visibility:action.visibility,...(action.usage!==undefined?{usage:action.usage}:{}),...(action.previousVersionId!==undefined?{previousVersionId:action.previousVersionId}:{})},this.config.initialStorageBytes-agent.storageBytes);storageDelta=published.totalBytes;effects.push({toolVersion:published.version});this.repo.addEvent('TOOL_PUBLISHED',tick,agentId,null,{toolId:published.version.toolId,toolVersionId:published.version.id,name:published.version.manifest.name,version:published.version.version,visibility:published.version.visibility,sourceHash:published.version.sourceHash});this.repo.addEvent('TOOL_VERSION_PUBLISHED',tick,agentId,null,{toolVersionId:published.version.id,version:published.version.version,previousVersionId:published.version.previousVersionId});break;}
        case'LIST_TOOLS':{const tools=this.repo.accessibleTools(agentId);effects.push({tools});break;}
        case'INSPECT_TOOL':{const version=this.repo.getToolVersion(action.toolVersionId);if(!version||!this.repo.canAccessTool(agentId,version))throw new Error('Tool version not found or not authorized');effects.push({toolVersion:version});this.repo.addEvent('TOOL_INSPECTED',tick,agentId,version.publisherAgentId,{toolVersionId:version.id,name:version.manifest.name,version:version.version});break;}
        case'INVOKE_TOOL':{if(agent.computeCredits<this.config.computeCostPerAction+this.config.executionMaxCost)throw new Error('Insufficient compute credits to reserve tool invocation');const version=this.repo.getToolVersion(action.toolVersionId);if(!version||!this.repo.canAccessTool(agentId,version))throw new Error('Tool version not found or not authorized');const input=JSON.stringify(action.input);if(Buffer.byteLength(input)>16*1024)throw new Error('Tool JSON input exceeds 16384 bytes');const workspacePath=await this.tools.executablePath(version);this.repo.addEvent('TOOL_INVOKED',tick,agentId,version.publisherAgentId,{toolVersionId:version.id,name:version.manifest.name,version:version.version});const result=await this.executionSandbox.execute({runtime:version.runtime,workspacePath,entrypoint:version.entrypoint,args:[],stdin:input});const record=this.repo.recordExecution(agentId,tick,version.runtime,`tool:${version.id}/${version.entrypoint}`,[],result),invocationId=this.repo.recordToolInvocation(version.id,agentId,record.id,tick);extraCompute=this.executionCost(result);effects.push({toolVersionId:version.id,invocationId,execution:record});actionSuccess=result.success;actionError=result.error??(!result.success?`Tool exited with ${result.exitCode}`:undefined);this.repo.addEvent(result.success?'TOOL_INVOCATION_COMPLETED':'TOOL_INVOCATION_FAILED',tick,agentId,version.publisherAgentId,{toolVersionId:version.id,invocationId,executionId:record.id,name:version.manifest.name,version:version.version,exitCode:result.exitCode,stdout:result.stdout,stderr:result.stderr,error:result.error,infrastructureFailure:this.infrastructureFailure(result)});this.repo.addMemory(agentId,'episodic',`Tool ${version.manifest.name} v${version.version} invocation ${result.success?'succeeded':'failed'}; exit=${result.exitCode}; stdout=${result.stdout}; stderr=${result.stderr}`.slice(0,4_000),tick,{salience:0.8,tags:['tool',version.manifest.name,version.id]});break;}
        case'SEARCH_TEXT':{const space=actionSpace(action),results=await this.files.searchText(agentId,action.query,space,action.maxResults);effects.push({space:space.toUpperCase(),query:action.query,results});this.repo.addEvent('TEXT_SEARCH_COMPLETED',tick,agentId,null,{space:space.toUpperCase(),query:action.query,resultCount:results.length});break;}
        case'INSPECT_WORLD':effects.push({world:this.requireWorld(),population:this.repo.listAgents().length});break;
        case'INSPECT_SELF':effects.push({agent:this.repo.getAgent(agentId)});break;
      }
      const fresh=this.repo.getAgent(agentId)!;this.repo.updateResources(agentId,fresh.computeCredits-this.config.computeCostPerAction-extraCompute,Math.max(0,fresh.storageBytes+storageDelta));this.repo.addEvent('RESOURCE_CONSUMED',tick,agentId,null,{cognition:0,action:this.config.computeCostPerAction,execution:extraCompute,storage:storageDelta});return{success:actionSuccess,actionId,agentId,tick,effects,...(actionError?{error:actionError}:{})};
    }catch(error){return this.fail(actionId,agentId,tick,error instanceof Error?error.message:'Action failed',action);}}
  private executionCost(result:ExecutionResult):number{return Math.min(this.config.executionMaxCost,this.config.executionBaseCost+Math.ceil(result.durationMs/100)+Math.ceil(Buffer.byteLength(result.stdout+result.stderr)/1024));}
  private infrastructureFailure(result:ExecutionResult):boolean{return!!result.error&&/Docker unavailable|image identity not verified|daemon|container engine/i.test(result.error);}
  private actionFacts(action:AgentAction,result:ActionResult):Record<string,unknown>{const facts:Record<string,unknown>={};if('path'in action)facts.path=action.path;if('space'in action||'area'in action)facts.space=String(('space'in action?action.space:undefined)??('area'in action?action.area:undefined)??'PRIVATE').toUpperCase();if(action.type==='WAIT')facts.waitTicks=action.ticks;if(action.type==='SEND_MESSAGE')facts.to=action.to;if(action.type==='EXECUTE_PROGRAM'){facts.entrypoint=action.entrypoint;facts.runtime=action.runtime;}if(action.type==='PUBLISH_TOOL')facts.name=action.name;if(action.type==='INVOKE_TOOL'||action.type==='INSPECT_TOOL')facts.toolVersionId=action.toolVersionId;const execution=(result.effects.find((effect)=>'execution'in effect) as {execution?:{success?:boolean;exitCode?:number|null}}|undefined)?.execution;if(execution)Object.assign(facts,{executionSuccess:execution.success??false,exitCode:execution.exitCode??null});return facts;}
  private fail(actionId:string,agentId:string,tick:number,error:string,action?:AgentAction):ActionResult{const security=/path|absolute|escape|malformed|symbolic|junction|reparse|canonical/i.test(error);this.repo.addEvent(security?'SECURITY_VIOLATION':'ACTION_FAILED',tick,agentId,null,{actionId,actionType:action?.type,error});return{success:false,actionId,agentId,tick,effects:[],error};}
  async ownerMessage(to:string,content:string):Promise<void>{await this.ownerIngress.ingestCli(to,content);}
}
