import { createHash,randomUUID } from 'node:crypto';
import type { RunnerLeaseState,WorldRepository } from '../../persistence/src/repository.js';
import { ProviderInfrastructureSuspension,type ResumableTickControl,type WorldEngine } from './engine.js';

export interface RateLimitSuspensionOptions{initialBackoffMs:number;maxBackoffMs:number;maxSuspensionMs:number;retryAfterMaxMs:number;}
export interface RunnerOptions{tickMs:number;label?:string;maxTicks?:number;maxCognitionTurns?:number;maxInputTokens?:number;maxOutputTokens?:number;computeCeiling?:number;maxCognitionCredits?:number;maxLocalCompute?:number;executionLimit?:number;wallClockLimitMs?:number;provider?:string;modelIdentifier?:string;infrastructureFailureThreshold?:number;rateLimitSuspension?:RateLimitSuspensionOptions;signal?:AbortSignal;}
const delay=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve)=>{if(signal?.aborted){resolve();return;}const onAbort=()=>{clearTimeout(timer);resolve();},timer=setTimeout(()=>{signal?.removeEventListener('abort',onAbort);resolve();},ms);signal?.addEventListener('abort',onAbort,{once:true});});
const sqliteBusy=(error:unknown)=>{const code=(error as {code?:unknown})?.code;return code==='SQLITE_BUSY'||code==='SQLITE_LOCKED';};
const leaseLossReason=(state:RunnerLeaseState)=>state==='replaced'?'ownership token replaced':state==='expired'?'lease expired':state==='missing'?'lease record missing':state==='malformed'?'lease record malformed':'heartbeat renewal failed';
const tokenHash=(token:string)=>createHash('sha256').update(token).digest('hex');

class RunnerLeaseHeartbeat{
  private readonly stopController=new AbortController();private running:Promise<void>|null=null;private loss:string|null=null;
  constructor(private readonly repo:WorldRepository,private readonly token:string,private readonly ttlMs:number,private readonly intervalMs:number){}
  get lostReason(){return this.loss;}
  start():void{if(this.running)throw new Error('Runner heartbeat already started');this.running=this.loop();}
  async stop():Promise<void>{this.stopController.abort();await this.running;}
  ownsAtBoundary():boolean{if(this.loss)return false;try{const state=this.repo.runnerLeaseState(this.token);if(state==='owned')return true;this.loss=leaseLossReason(state);return false;}catch(error){if(sqliteBusy(error))return true;this.loss='lease ownership check failed';return false;}}
  async verifyOwnership():Promise<boolean>{if(this.loss)return false;for(let attempt=0;attempt<4;attempt++){try{const state=this.repo.runnerLeaseState(this.token);if(state==='owned')return true;this.loss=leaseLossReason(state);return false;}catch(error){if(!sqliteBusy(error)){this.loss='lease ownership check failed';return false;}if(attempt<3)await delay(25*2**attempt);}}this.loss='lease ownership check database contention';return false;}
  private async renew():Promise<boolean>{for(let attempt=0;attempt<4;attempt++){try{if(this.repo.renewRunnerLease(this.token,this.ttlMs))return true;const state=this.repo.runnerLeaseState(this.token);this.loss=leaseLossReason(state);return false;}catch(error){if(!sqliteBusy(error)){this.loss='heartbeat renewal failed';return false;}if(attempt<3)await delay(25*2**attempt);}}this.loss='heartbeat database contention';return false;}
  private async loop():Promise<void>{while(!this.stopController.signal.aborted){await delay(this.intervalMs,this.stopController.signal);if(this.stopController.signal.aborted)break;if(!await this.renew())break;}}
}

export class ContinuousWorldRunner{
  constructor(private readonly engine:WorldEngine){}
  async run(options:RunnerOptions):Promise<{runId:string;ticks:number;reason:string}>{
    this.engine.repo.economy.requireModel();if(options.computeCeiling!==undefined)throw new Error('Aggregate compute ceiling is deprecated. Use maxCognitionCredits and maxLocalCompute.');for(const amount of [options.maxCognitionCredits,options.maxLocalCompute])if(amount!==undefined&&(!Number.isSafeInteger(amount)||amount<1))throw new Error('Resource ceilings must be positive safe integers');
    if(this.engine.config.runnerHeartbeatMs<=0||this.engine.config.runnerLeaseMs<this.engine.config.runnerHeartbeatMs*3)throw new Error('Runner lease TTL must be at least three heartbeat intervals');
    this.engine.setCognitionRateLimitSuspensionMode(options.rateLimitSuspension!==undefined);
    const token=randomUUID(),runnerId=randomUUID(),safeTokenHash=tokenHash(token),world=this.engine.repo.getWorld();if(!world)throw new Error('World does not exist');if(world.status!=='running')throw new Error('World is paused; run resume first');if(!this.engine.repo.acquireRunnerLease(token,this.engine.config.runnerLeaseMs,runnerId)){this.engine.repo.addEvent('RUNNER_START_FAILED',world.currentTick,null,null,{runnerId,reason:'another valid runner owns the world or the lease is malformed'});throw new Error('Runner start failed: another valid runner owns the world or the lease is malformed');}
    const heartbeat=new RunnerLeaseHeartbeat(this.engine.repo,token,this.engine.config.runnerLeaseMs,this.engine.config.runnerHeartbeatMs),initialCompute=0,initialCognition=this.engine.repo.economy.total('COGNITION_CREDIT'),initialLocal=this.engine.repo.economy.total('LOCAL_COMPUTE'),startingCognitionConsumed=this.engine.repo.economy.consumed('COGNITION_CREDIT'),startingLocalConsumed=this.engine.repo.economy.consumed('LOCAL_COMPUTE'),modelIdentifier=options.modelIdentifier??'deterministic';heartbeat.start();let run;try{this.engine.repo.economy.reconcileAbandonedExecutions(token);const preflight=await this.engine.capturePreflight(modelIdentifier);run=this.engine.repo.transaction(()=>{const createdRun=this.engine.repo.createAutonomyRun({...(options.label?{label:options.label}:{}),provider:options.provider??'deterministic',modelIdentifier,preflight,initialCompute,...(options.computeCeiling!==undefined?{computeCeiling:options.computeCeiling}:{}),...(options.maxTicks!==undefined?{tickLimit:options.maxTicks}:{}),...(options.maxCognitionTurns!==undefined?{cognitionTurnLimit:options.maxCognitionTurns}:{}),...(options.maxInputTokens!==undefined?{inputTokenLimit:options.maxInputTokens}:{}),...(options.maxOutputTokens!==undefined?{outputTokenLimit:options.maxOutputTokens}:{}),...(options.executionLimit!==undefined?{executionLimit:options.executionLimit}:{}),...(options.wallClockLimitMs!==undefined?{wallClockLimitMs:options.wallClockLimitMs}:{})});this.engine.repo.db.prepare('INSERT INTO resource_run_snapshots(run_id,initial_cognition,initial_local,max_cognition,max_local,start_ledger_id) VALUES(?,?,?,?,?,?)').run(createdRun.id,initialCognition,initialLocal,options.maxCognitionCredits??null,options.maxLocalCompute??null,(this.engine.repo.db.prepare('SELECT COALESCE(max(rowid),0) id FROM value_ledger').get() as {id:number}).id);return createdRun;});}catch(error){await heartbeat.stop();this.engine.repo.releaseRunnerLease(token);this.engine.repo.addEvent('RUNNER_START_FAILED',world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,reason:'runner preflight or run creation failed'});throw error;}
    let ticks=0,reason='stopped',consecutiveInfrastructureFailures=0,cognitionTurns=0,inputTokens=0,outputTokens=0,leaseLossRecorded=false;const started=Date.now(),startingExecutions=this.engine.repo.executionCount(world.currentTick),recordLeaseLoss=()=>{if(leaseLossRecorded)return;leaseLossRecorded=true;this.engine.repo.addEvent('RUNNER_LEASE_LOST',this.engine.repo.getWorld()?.currentTick??world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,reason:heartbeat.lostReason??'ownership verification failed',runId:run.id});};this.engine.repo.addEvent('RUNNER_STARTED',world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,tickMs:options.tickMs,heartbeatMs:this.engine.config.runnerHeartbeatMs,leaseTtlMs:this.engine.config.runnerLeaseMs,runId:run.id});this.engine.repo.addEvent('AUTONOMY_RUN_STARTED',world.currentTick,null,null,{runId:run.id,label:run.label,tickLimit:run.tickLimit,cognitionTurnLimit:run.cognitionTurnLimit,inputTokenLimit:run.inputTokenLimit,outputTokenLimit:run.outputTokenLimit,maxCognitionCredits:options.maxCognitionCredits,maxLocalCompute:options.maxLocalCompute,executionLimit:run.executionLimit,wallClockLimitMs:run.wallClockLimitMs});
    try{
      while(!options.signal?.aborted){
        if(options.maxTicks!==undefined&&ticks>=options.maxTicks){reason='maximum ticks reached';break;}
        if(options.wallClockLimitMs!==undefined&&Date.now()-started>=options.wallClockLimitMs){reason='wall-clock limit reached';break;}
        const latest=this.engine.repo.getWorld();if(latest?.status!=='running'){reason='world paused';break;}if(!await heartbeat.verifyOwnership()){reason='runner lease lost';recordLeaseLoss();break;}
        let control:ResumableTickControl|undefined,recoveringStartedAt:number|null=null,recoveringCause:{phase:string;httpStatus?:number;providerCode?:string}|null=null;
        if(options.rateLimitSuspension){
          let schedule=this.engine.repo.beginTickSchedule(latest.currentTick+1,this.engine.repo.listAgents().filter((agent)=>agent.status==='active'&&agent.eligibleFromTick<=latest.currentTick+1).map((agent)=>agent.id),options.provider??'deterministic',modelIdentifier);
          const cause=()=>schedule.suspensionCause??{phase:'http',httpStatus:429};
          const exhaustionReason=()=>cause().phase==='http'&&cause().httpStatus===429?'provider rate-limit suspension exhausted':'provider suspension exhausted';
          if(schedule.state==='COOLDOWN'){
            const elapsed=schedule.cooldownStartedAtMs===null?0:Date.now()-schedule.cooldownStartedAtMs;
            if(elapsed>=options.rateLimitSuspension.maxSuspensionMs){reason=exhaustionReason();this.engine.repo.pauseTickSchedule(schedule.id);this.engine.repo.addEvent('PROVIDER_COOLDOWN_ABORTED',latest.currentTick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,reason,attemptNumber:schedule.rateLimitAttempts,...cause(),elapsedMs:elapsed});break;}
            const waitMs=Math.max(0,(schedule.nextRetryAtMs??Date.now())-Date.now()),wallRemaining=options.wallClockLimitMs===undefined?Number.MAX_SAFE_INTEGER:Math.max(0,options.wallClockLimitMs-(Date.now()-started)),suspensionRemaining=options.rateLimitSuspension.maxSuspensionMs-elapsed;await delay(Math.min(waitMs,wallRemaining,suspensionRemaining),options.signal);
            if(options.signal?.aborted){reason='shutdown signal';this.engine.repo.pauseTickSchedule(schedule.id);this.engine.repo.addEvent('PROVIDER_COOLDOWN_ABORTED',latest.currentTick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,reason,attemptNumber:schedule.rateLimitAttempts,...cause(),elapsedMs:schedule.cooldownStartedAtMs===null?0:Date.now()-schedule.cooldownStartedAtMs});break;}
            if(options.wallClockLimitMs!==undefined&&Date.now()-started>=options.wallClockLimitMs){reason='wall-clock limit reached';this.engine.repo.pauseTickSchedule(schedule.id);this.engine.repo.addEvent('PROVIDER_COOLDOWN_ABORTED',latest.currentTick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,reason,attemptNumber:schedule.rateLimitAttempts,...cause(),elapsedMs:schedule.cooldownStartedAtMs===null?0:Date.now()-schedule.cooldownStartedAtMs});break;}
            if(schedule.cooldownStartedAtMs!==null&&Date.now()-schedule.cooldownStartedAtMs>=options.rateLimitSuspension.maxSuspensionMs){reason=exhaustionReason();this.engine.repo.pauseTickSchedule(schedule.id);this.engine.repo.addEvent('PROVIDER_COOLDOWN_ABORTED',latest.currentTick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,reason,attemptNumber:schedule.rateLimitAttempts,...cause(),elapsedMs:Date.now()-schedule.cooldownStartedAtMs});break;}
            this.engine.repo.addEvent('PROVIDER_COOLDOWN_RETRY',schedule.tick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,...cause(),attemptNumber:schedule.rateLimitAttempts+1,elapsedMs:schedule.cooldownStartedAtMs===null?0:Date.now()-schedule.cooldownStartedAtMs});this.engine.repo.activateTickScheduleRetry(schedule.id);schedule=this.engine.repo.tickSchedule()!;
          }else if(schedule.state==='PAUSED'){this.engine.repo.addEvent('PROVIDER_COOLDOWN_RETRY',schedule.tick,null,schedule.pendingAgentId,{runId:run.id,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier,...cause(),attemptNumber:schedule.rateLimitAttempts+1,elapsedMs:schedule.cooldownStartedAtMs===null?0:Date.now()-schedule.cooldownStartedAtMs,resumed:true});this.engine.repo.activateTickScheduleRetry(schedule.id);schedule=this.engine.repo.tickSchedule()!;}
          recoveringStartedAt=schedule.pendingAgentId&&schedule.cooldownStartedAtMs!==null?schedule.cooldownStartedAtMs:null;recoveringCause=recoveringStartedAt!==null?cause():null;control={scheduleId:schedule.id,agentIds:schedule.agentIds,completedAgentIds:schedule.completedAgentIds,pendingAgentId:schedule.pendingAgentId,pendingContext:schedule.pendingContext,suspendInfrastructure:true,provider:schedule.provider,modelIdentifier:schedule.modelIdentifier};
        }
        const beforeEvent=this.engine.repo.latestEventId(),beforeTick=latest.currentTick;
        try{await this.engine.tick(run.id,()=>heartbeat.ownsAtBoundary(),token,control);if(recoveringStartedAt!==null){const pendingTurn=this.engine.repo.eventsAfter(beforeEvent).find((event)=>event.type==='COGNITION_TURN_COMPLETED'&&event.actorId===control?.pendingAgentId);if(pendingTurn)this.engine.repo.addEvent(pendingTurn.payload.providerRequestSucceeded===true?'PROVIDER_COOLDOWN_RECOVERED':'PROVIDER_COOLDOWN_ABORTED',this.engine.repo.getWorld()?.currentTick??latest.currentTick,null,control?.pendingAgentId??null,{runId:run.id,provider:control?.provider,modelIdentifier:control?.modelIdentifier,...(recoveringCause??{}),...(pendingTurn.payload.providerRequestSucceeded===true?{}:{reason:'pending cognition fell back after suspension'}),elapsedMs:Date.now()-recoveringStartedAt});}}
        catch(error){
          if(error instanceof ProviderInfrastructureSuspension&&options.rateLimitSuspension){
            const partialTurns=this.engine.repo.eventsAfter(beforeEvent).filter((event)=>event.type==='COGNITION_TURN_COMPLETED'&&event.payload.providerRequestSucceeded!==false);
            cognitionTurns+=partialTurns.length;inputTokens+=partialTurns.reduce((sum,event)=>sum+Number(event.payload.inputTokens??0),0);outputTokens+=partialTurns.reduce((sum,event)=>sum+Number(event.payload.outputTokens??0),0);
            const prior=this.engine.repo.tickSchedule();if(!prior)throw new Error('Provider suspension lost durable tick schedule');const exponent=Math.min(prior.rateLimitAttempts,30),fallbackMs=Math.min(options.rateLimitSuspension.maxBackoffMs,options.rateLimitSuspension.initialBackoffMs*2**exponent),backoffMs=Math.min(error.failure.retryAfterMs??fallbackMs,options.rateLimitSuspension.retryAfterMaxMs,options.rateLimitSuspension.maxSuspensionMs),updated=this.engine.repo.startTickScheduleCooldown(prior.id,Date.now()+backoffMs,{phase:error.failure.phase,...(error.failure.httpStatus!==undefined?{httpStatus:error.failure.httpStatus}:{}),...(error.failure.providerCode?{providerCode:error.failure.providerCode}:{})});if(prior.cooldownStartedAtMs===null)this.engine.repo.addEvent('PROVIDER_COOLDOWN_STARTED',error.tick,null,error.agentId,{runId:run.id,provider:updated.provider,modelIdentifier:updated.modelIdentifier,phase:error.failure.phase,...(error.failure.httpStatus!==undefined?{httpStatus:error.failure.httpStatus}:{}),...(error.failure.providerCode?{providerCode:error.failure.providerCode}:{}),message:error.failure.safeMessage,retryable:error.failure.retryable,attemptNumber:updated.rateLimitAttempts,providerAttempts:error.failure.attemptCount,backoffMs,startedAt:new Date(updated.cooldownStartedAtMs!).toISOString(),elapsedMs:0});this.engine.repo.addEvent('PROVIDER_COOLDOWN_FAILURE',error.tick,null,error.agentId,{runId:run.id,schedulerProgressId:prior.id,provider:updated.provider,modelIdentifier:updated.modelIdentifier,phase:error.failure.phase,...(error.failure.httpStatus!==undefined?{httpStatus:error.failure.httpStatus}:{}),providerAttempts:error.failure.attemptCount,providerUsageAvailable:false,attemptNumber:updated.rateLimitAttempts});continue;
          }
          reason=`database or runner failure: ${error instanceof Error?error.message:'unknown error'}`;this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',latest.currentTick,null,null,{runId:run.id,reason});break;
        }
        const afterTick=this.engine.repo.getWorld()?.currentTick??beforeTick;if(afterTick>beforeTick)ticks+=afterTick-beforeTick;const newEvents=this.engine.repo.eventsAfter(beforeEvent),turnEvents=newEvents.filter((event)=>event.type==='COGNITION_TURN_COMPLETED'&&event.payload.providerRequestSucceeded!==false);cognitionTurns+=turnEvents.length;inputTokens+=turnEvents.reduce((sum,event)=>sum+Number(event.payload.inputTokens??0),0);outputTokens+=turnEvents.reduce((sum,event)=>sum+Number(event.payload.outputTokens??0),0);if(!await heartbeat.verifyOwnership()){reason='runner lease lost';recordLeaseLoss();break;}const infrastructureFailures=newEvents.filter((event)=>event.type==='COGNITION_PROVIDER_ERROR'||event.payload.infrastructureFailure===true).length;consecutiveInfrastructureFailures=infrastructureFailures>0?consecutiveInfrastructureFailures+infrastructureFailures:0;if(consecutiveInfrastructureFailures>=(options.infrastructureFailureThreshold??10)){reason='infrastructure failure circuit breaker';this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',this.engine.repo.getWorld()?.currentTick??latest.currentTick,null,null,{runId:run.id,consecutiveInfrastructureFailures});break;}if(options.maxCognitionTurns!==undefined&&cognitionTurns>=options.maxCognitionTurns){reason='cognition-turn limit reached';break;}if(options.maxInputTokens!==undefined&&inputTokens>=options.maxInputTokens){reason='provider input-token limit reached';break;}if(options.maxOutputTokens!==undefined&&outputTokens>=options.maxOutputTokens){reason='provider output-token limit reached';break;}if(options.maxCognitionCredits!==undefined&&this.engine.repo.economy.consumed('COGNITION_CREDIT')-startingCognitionConsumed>=options.maxCognitionCredits){reason='cognition credit ceiling reached';break;}if(options.maxLocalCompute!==undefined&&this.engine.repo.economy.consumed('LOCAL_COMPUTE')-startingLocalConsumed>=options.maxLocalCompute){reason='local compute ceiling reached';break;}if(options.executionLimit!==undefined&&this.engine.repo.executionCount(world.currentTick)-startingExecutions>=options.executionLimit){reason='execution limit reached';break;}await delay(options.tickMs,options.signal);
      }
      if(options.signal?.aborted&&reason==='stopped')reason='shutdown signal';
      const suspended=this.engine.repo.tickSchedule();
      if(suspended&&suspended.pendingAgentId&&suspended.cooldownStartedAtMs!==null&&suspended.state!=='PAUSED'){
        this.engine.repo.pauseTickSchedule(suspended.id);
        this.engine.repo.addEvent('PROVIDER_COOLDOWN_ABORTED',this.engine.repo.getWorld()?.currentTick??world.currentTick,null,suspended.pendingAgentId,{runId:run.id,provider:suspended.provider,modelIdentifier:suspended.modelIdentifier,reason,attemptNumber:suspended.rateLimitAttempts,...(suspended.suspensionCause??{phase:'http',httpStatus:429}),elapsedMs:Math.max(0,Date.now()-suspended.cooldownStartedAtMs)});
      }
      return{runId:run.id,ticks,reason};
    }
    finally{await heartbeat.stop();const tick=this.engine.repo.getWorld()?.currentTick??world.currentTick;this.engine.repo.releaseRunnerLease(token);this.engine.repo.addEvent('AUTONOMY_RUN_STOPPED',tick,null,null,{runId:run.id,ticks,cognitionTurns,inputTokens,outputTokens,reason});let postflight;try{postflight=await this.engine.capturePreflight(modelIdentifier);}catch{postflight=undefined;}this.engine.repo.transaction(()=>{this.engine.repo.finishAutonomyRun(run.id,tick,reason,postflight);this.engine.repo.db.prepare('UPDATE resource_run_snapshots SET ending_cognition=?,ending_local=?,end_ledger_id=? WHERE run_id=?').run(this.engine.repo.economy.total('COGNITION_CREDIT'),this.engine.repo.economy.total('LOCAL_COMPUTE'),(this.engine.repo.db.prepare('SELECT COALESCE(max(rowid),0) id FROM value_ledger').get() as {id:number}).id,run.id);});this.engine.repo.addEvent('RUNNER_STOPPED',tick,null,null,{runnerId,tokenHash:safeTokenHash,ticks,reason,runId:run.id});}
  }
}
