import { randomUUID } from 'node:crypto';
import type { WorldEngine } from './engine.js';

export interface RunnerOptions{tickMs:number;maxTicks?:number;computeCeiling?:number;executionLimit?:number;wallClockLimitMs?:number;provider?:string;infrastructureFailureThreshold?:number;signal?:AbortSignal;}
const delay=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve)=>{if(signal?.aborted){resolve();return;}const timer=setTimeout(resolve,ms);signal?.addEventListener('abort',()=>{clearTimeout(timer);resolve();},{once:true});});

export class ContinuousWorldRunner{
  constructor(private readonly engine:WorldEngine){}
  async run(options:RunnerOptions):Promise<{runId:string;ticks:number;reason:string}>{
    const token=randomUUID(),world=this.engine.repo.getWorld();if(!world)throw new Error('World does not exist');if(world.status!=='running')throw new Error('World is paused; run resume first');if(!this.engine.repo.acquireRunnerLease(token,this.engine.config.runnerLeaseMs))throw new Error('Another runner holds the world lease');
    const initialCompute=this.engine.repo.listAgents().reduce((sum,a)=>sum+a.computeCredits,0);let run;try{run=this.engine.repo.createAutonomyRun({provider:options.provider??'deterministic',initialCompute,...(options.computeCeiling!==undefined?{computeCeiling:options.computeCeiling}:{}),...(options.maxTicks!==undefined?{tickLimit:options.maxTicks}:{}),...(options.executionLimit!==undefined?{executionLimit:options.executionLimit}:{}),...(options.wallClockLimitMs!==undefined?{wallClockLimitMs:options.wallClockLimitMs}:{})});}catch(error){this.engine.repo.releaseRunnerLease(token);throw error;}let ticks=0,reason='stopped',consecutiveInfrastructureFailures=0;const started=Date.now(),startingExecutions=this.engine.repo.executionCount(world.currentTick);this.engine.repo.addEvent('RUNNER_STARTED',world.currentTick,null,null,{token,tickMs:options.tickMs,runId:run.id});this.engine.repo.addEvent('AUTONOMY_RUN_STARTED',world.currentTick,null,null,{runId:run.id,provider:run.provider,tickLimit:run.tickLimit,computeCeiling:run.computeCeiling,executionLimit:run.executionLimit,wallClockLimitMs:run.wallClockLimitMs});
    try{while(!options.signal?.aborted){if(options.maxTicks!==undefined&&ticks>=options.maxTicks){reason='maximum ticks reached';break;}if(options.wallClockLimitMs!==undefined&&Date.now()-started>=options.wallClockLimitMs){reason='wall-clock limit reached';break;}const latest=this.engine.repo.getWorld();if(latest?.status!=='running'){reason='world paused';break;}if(!this.engine.repo.renewRunnerLease(token,this.engine.config.runnerLeaseMs)){reason='runner lease lost';this.engine.repo.addEvent('RUNNER_LEASE_LOST',latest?.currentTick??0,null,null,{token});break;}const beforeEvent=this.engine.repo.latestEventId();try{await this.engine.tick();}catch(error){reason=`database or runner failure: ${error instanceof Error?error.message:'unknown error'}`;this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',latest.currentTick,null,null,{runId:run.id,reason});break;}ticks++;const newEvents=this.engine.repo.eventsAfter(beforeEvent),infrastructureFailures=newEvents.filter((event)=>event.type==='COGNITION_PROVIDER_ERROR'||event.payload.infrastructureFailure===true).length;consecutiveInfrastructureFailures=infrastructureFailures>0?consecutiveInfrastructureFailures+infrastructureFailures:0;if(consecutiveInfrastructureFailures>=(options.infrastructureFailureThreshold??10)){reason='infrastructure failure circuit breaker';this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',this.engine.repo.getWorld()?.currentTick??latest.currentTick,null,null,{runId:run.id,consecutiveInfrastructureFailures});break;}if(options.computeCeiling!==undefined){const remaining=this.engine.repo.listAgents().reduce((sum,a)=>sum+a.computeCredits,0);if(initialCompute-remaining>=options.computeCeiling){reason='compute ceiling reached';break;}}if(options.executionLimit!==undefined&&this.engine.repo.executionCount(world.currentTick)-startingExecutions>=options.executionLimit){reason='execution limit reached';break;}if(options.tickMs>0)await delay(options.tickMs,options.signal);}if(options.signal?.aborted)reason='shutdown signal';return{runId:run.id,ticks,reason};}
    finally{const tick=this.engine.repo.getWorld()?.currentTick??world.currentTick;this.engine.repo.releaseRunnerLease(token);this.engine.repo.finishAutonomyRun(run.id,tick,reason);this.engine.repo.addEvent('RUNNER_STOPPED',tick,null,null,{token,ticks,reason,runId:run.id});this.engine.repo.addEvent('AUTONOMY_RUN_STOPPED',tick,null,null,{runId:run.id,ticks,reason});}
  }
}
