import { createHash,randomUUID } from 'node:crypto';
import type { RunnerLeaseState,WorldRepository } from '../../persistence/src/repository.js';
import type { WorldEngine } from './engine.js';

export interface RunnerOptions{tickMs:number;label?:string;maxTicks?:number;maxCognitionTurns?:number;maxInputTokens?:number;maxOutputTokens?:number;computeCeiling?:number;executionLimit?:number;wallClockLimitMs?:number;provider?:string;modelIdentifier?:string;infrastructureFailureThreshold?:number;signal?:AbortSignal;}
const delay=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve)=>{if(signal?.aborted){resolve();return;}const onAbort=()=>{clearTimeout(timer);resolve();},timer=setTimeout(()=>{signal?.removeEventListener('abort',onAbort);resolve();},ms);signal?.addEventListener('abort',onAbort,{once:true});});
const sqliteBusy=(error:unknown)=>{const code=(error as {code?:unknown})?.code;return code==='SQLITE_BUSY'||code==='SQLITE_LOCKED';};
const leaseLossReason=(state:RunnerLeaseState)=>state==='replaced'?'ownership token replaced':state==='expired'?'lease expired':state==='missing'?'lease record missing':state==='malformed'?'lease record malformed':'heartbeat renewal failed';
const tokenHash=(token:string)=>createHash('sha256').update(token).digest('hex');

class RunnerLeaseHeartbeat{
  private readonly stopController=new AbortController();private running:Promise<void>|null=null;private loss:string|null=null;
  constructor(private readonly repo:WorldRepository,private readonly token:string,private readonly ttlMs:number,private readonly intervalMs:number){}
  get lostReason(){return this.loss;}
  start():void{if(this.running)throw new Error('Runner heartbeat already started');this.running=this.loop();}
  async stop():Promise<void>{this.stopController.abort();await this.running;}
  ownsAtBoundary():boolean{if(this.loss)return false;try{const state=this.repo.runnerLeaseState(this.token);if(state==='owned')return true;this.loss=leaseLossReason(state);return false;}catch(error){if(sqliteBusy(error))return true;this.loss='lease ownership check failed';return false;}}
  async verifyOwnership():Promise<boolean>{if(this.loss)return false;for(let attempt=0;attempt<4;attempt++){try{const state=this.repo.runnerLeaseState(this.token);if(state==='owned')return true;this.loss=leaseLossReason(state);return false;}catch(error){if(!sqliteBusy(error)){this.loss='lease ownership check failed';return false;}if(attempt<3)await delay(25*2**attempt);}}this.loss='lease ownership check database contention';return false;}
  private async renew():Promise<boolean>{for(let attempt=0;attempt<4;attempt++){try{if(this.repo.renewRunnerLease(this.token,this.ttlMs))return true;const state=this.repo.runnerLeaseState(this.token);this.loss=leaseLossReason(state);return false;}catch(error){if(!sqliteBusy(error)){this.loss='heartbeat renewal failed';return false;}if(attempt<3)await delay(25*2**attempt);}}this.loss='heartbeat database contention';return false;}
  private async loop():Promise<void>{while(!this.stopController.signal.aborted){await delay(this.intervalMs,this.stopController.signal);if(this.stopController.signal.aborted)break;if(!await this.renew())break;}}
}

export class ContinuousWorldRunner{
  constructor(private readonly engine:WorldEngine){}
  async run(options:RunnerOptions):Promise<{runId:string;ticks:number;reason:string}>{
    if(this.engine.config.runnerHeartbeatMs<=0||this.engine.config.runnerLeaseMs<this.engine.config.runnerHeartbeatMs*3)throw new Error('Runner lease TTL must be at least three heartbeat intervals');
    const token=randomUUID(),runnerId=randomUUID(),safeTokenHash=tokenHash(token),world=this.engine.repo.getWorld();if(!world)throw new Error('World does not exist');if(world.status!=='running')throw new Error('World is paused; run resume first');if(!this.engine.repo.acquireRunnerLease(token,this.engine.config.runnerLeaseMs,runnerId)){this.engine.repo.addEvent('RUNNER_START_FAILED',world.currentTick,null,null,{runnerId,reason:'another valid runner owns the world or the lease is malformed'});throw new Error('Runner start failed: another valid runner owns the world or the lease is malformed');}
    const heartbeat=new RunnerLeaseHeartbeat(this.engine.repo,token,this.engine.config.runnerLeaseMs,this.engine.config.runnerHeartbeatMs),initialCompute=this.engine.repo.totalAccountedCompute(),modelIdentifier=options.modelIdentifier??'deterministic';heartbeat.start();let run;try{const preflight=await this.engine.capturePreflight(modelIdentifier);run=this.engine.repo.createAutonomyRun({...(options.label?{label:options.label}:{}),provider:options.provider??'deterministic',modelIdentifier,preflight,initialCompute,...(options.computeCeiling!==undefined?{computeCeiling:options.computeCeiling}:{}),...(options.maxTicks!==undefined?{tickLimit:options.maxTicks}:{}),...(options.maxCognitionTurns!==undefined?{cognitionTurnLimit:options.maxCognitionTurns}:{}),...(options.maxInputTokens!==undefined?{inputTokenLimit:options.maxInputTokens}:{}),...(options.maxOutputTokens!==undefined?{outputTokenLimit:options.maxOutputTokens}:{}),...(options.executionLimit!==undefined?{executionLimit:options.executionLimit}:{}),...(options.wallClockLimitMs!==undefined?{wallClockLimitMs:options.wallClockLimitMs}:{})});}catch(error){await heartbeat.stop();this.engine.repo.releaseRunnerLease(token);this.engine.repo.addEvent('RUNNER_START_FAILED',world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,reason:'runner preflight or run creation failed'});throw error;}
    let ticks=0,reason='stopped',consecutiveInfrastructureFailures=0,cognitionTurns=0,inputTokens=0,outputTokens=0,leaseLossRecorded=false;const started=Date.now(),startingExecutions=this.engine.repo.executionCount(world.currentTick),recordLeaseLoss=()=>{if(leaseLossRecorded)return;leaseLossRecorded=true;this.engine.repo.addEvent('RUNNER_LEASE_LOST',this.engine.repo.getWorld()?.currentTick??world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,reason:heartbeat.lostReason??'ownership verification failed',runId:run.id});};this.engine.repo.addEvent('RUNNER_STARTED',world.currentTick,null,null,{runnerId,tokenHash:safeTokenHash,tickMs:options.tickMs,heartbeatMs:this.engine.config.runnerHeartbeatMs,leaseTtlMs:this.engine.config.runnerLeaseMs,runId:run.id});this.engine.repo.addEvent('AUTONOMY_RUN_STARTED',world.currentTick,null,null,{runId:run.id,label:run.label,tickLimit:run.tickLimit,cognitionTurnLimit:run.cognitionTurnLimit,inputTokenLimit:run.inputTokenLimit,outputTokenLimit:run.outputTokenLimit,computeCeiling:run.computeCeiling,executionLimit:run.executionLimit,wallClockLimitMs:run.wallClockLimitMs});
    try{while(!options.signal?.aborted){if(options.maxTicks!==undefined&&ticks>=options.maxTicks){reason='maximum ticks reached';break;}if(options.wallClockLimitMs!==undefined&&Date.now()-started>=options.wallClockLimitMs){reason='wall-clock limit reached';break;}const latest=this.engine.repo.getWorld();if(latest?.status!=='running'){reason='world paused';break;}if(!await heartbeat.verifyOwnership()){reason='runner lease lost';recordLeaseLoss();break;}const beforeEvent=this.engine.repo.latestEventId(),beforeTick=latest.currentTick;try{await this.engine.tick(run.id,()=>heartbeat.ownsAtBoundary(),token);}catch(error){reason=`database or runner failure: ${error instanceof Error?error.message:'unknown error'}`;this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',latest.currentTick,null,null,{runId:run.id,reason});break;}const afterTick=this.engine.repo.getWorld()?.currentTick??beforeTick;if(afterTick>beforeTick)ticks+=afterTick-beforeTick;const newEvents=this.engine.repo.eventsAfter(beforeEvent),turnEvents=newEvents.filter((event)=>event.type==='COGNITION_TURN_COMPLETED');cognitionTurns+=turnEvents.length;inputTokens+=turnEvents.reduce((sum,event)=>sum+Number(event.payload.inputTokens??0),0);outputTokens+=turnEvents.reduce((sum,event)=>sum+Number(event.payload.outputTokens??0),0);if(!await heartbeat.verifyOwnership()){reason='runner lease lost';recordLeaseLoss();break;}const infrastructureFailures=newEvents.filter((event)=>event.type==='COGNITION_PROVIDER_ERROR'||event.payload.infrastructureFailure===true).length;consecutiveInfrastructureFailures=infrastructureFailures>0?consecutiveInfrastructureFailures+infrastructureFailures:0;if(consecutiveInfrastructureFailures>=(options.infrastructureFailureThreshold??10)){reason='infrastructure failure circuit breaker';this.engine.repo.addEvent('AUTONOMY_CIRCUIT_BREAKER_OPENED',this.engine.repo.getWorld()?.currentTick??latest.currentTick,null,null,{runId:run.id,consecutiveInfrastructureFailures});break;}if(options.maxCognitionTurns!==undefined&&cognitionTurns>=options.maxCognitionTurns){reason='cognition-turn limit reached';break;}if(options.maxInputTokens!==undefined&&inputTokens>=options.maxInputTokens){reason='provider input-token limit reached';break;}if(options.maxOutputTokens!==undefined&&outputTokens>=options.maxOutputTokens){reason='provider output-token limit reached';break;}if(options.computeCeiling!==undefined){const remaining=this.engine.repo.totalAccountedCompute();if(initialCompute-remaining>=options.computeCeiling){reason='compute ceiling reached';break;}}if(options.executionLimit!==undefined&&this.engine.repo.executionCount(world.currentTick)-startingExecutions>=options.executionLimit){reason='execution limit reached';break;}await delay(options.tickMs,options.signal);}if(options.signal?.aborted)reason='shutdown signal';return{runId:run.id,ticks,reason};}
    finally{await heartbeat.stop();const tick=this.engine.repo.getWorld()?.currentTick??world.currentTick;this.engine.repo.releaseRunnerLease(token);this.engine.repo.addEvent('AUTONOMY_RUN_STOPPED',tick,null,null,{runId:run.id,ticks,cognitionTurns,inputTokens,outputTokens,reason});let postflight;try{postflight=await this.engine.capturePreflight(modelIdentifier);}catch{postflight=undefined;}this.engine.repo.finishAutonomyRun(run.id,tick,reason,postflight);this.engine.repo.addEvent('RUNNER_STOPPED',tick,null,null,{runnerId,tokenHash:safeTokenHash,ticks,reason,runId:run.id});}
  }
}
