#!/usr/bin/env node
import { existsSync } from 'node:fs';
import path from 'node:path';
import { economyCli,isReadOnlyEconomyCommand } from '../../../packages/operations/src/economy-cli.js';
import { formatCapital } from '../../../packages/resources/src/economy.js';
import { configuredCognitionProvider } from '../../../packages/cognition/src/index.js';
import { configuredOwnerGateways,ConsoleOwnerGateway,OwnerGatewayDispatcher } from '../../../packages/messaging/src/index.js';
import { createLineWebhookServer,LineWebhookIngress } from '../../../packages/messaging/src/ingress.js';
import { SandboxDoctor } from '../../../packages/operations/src/doctor.js';
import { LiveReadinessDoctor } from '../../../packages/operations/src/live-doctor.js';
import { WorldCheckpointService } from '../../../packages/operations/src/checkpoint.js';
import { migratePendingProvider } from '../../../packages/operations/src/pending-provider.js';
import { formatExperimentLimits,LONG_RATE_LIMIT_SUSPENSION,resolveExperimentCliLimits } from '../../../packages/operations/src/experiment-limits.js';
import { createExperimentReport } from '../../../packages/operations/src/experiment-report.js';
import { createRunReport } from '../../../packages/operations/src/run-report.js';
import { runnerLeaseDoctorChecks } from '../../../packages/operations/src/runner-lease-doctor.js';
import { DockerExecutionSandbox } from '../../../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig } from '../../../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../../../packages/world/src/runner.js';

try{process.loadEnvFile();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
const args=process.argv.slice(2),command=args[0]??'help',live=args.includes('--live');
const option=(name:string)=>{const index=args.indexOf(name);return index>=0?args[index+1]:undefined;};
const integerOption=(name:string,fallback?:number)=>{const raw=option(name);if(raw===undefined&&fallback!==undefined)return fallback;const value=Number(raw);if(!Number.isSafeInteger(value)||value<0)throw new Error(`${name} must be a non-negative integer`);return value;};
if(command==='experiment'&&args.includes('--show-limits'))console.log(formatExperimentLimits(resolveExperimentCliLimits(args)));
else{
const dataConfig=defaultConfig(),readOnly=(['status','agents','events','activity','memories','messages','executions','files','tools','tool','inspect','runs','run-report','experiment-report','owner-outbox','debug','doctor','help'].includes(command)||command==='checkpoint'&&args[1]==='list'||command==='pending-provider'&&args[1]==='show'||['resources','economy'].includes(command)&&isReadOnlyEconomyCommand(args))&&existsSync(path.join(dataConfig.dataDir,'world.sqlite'));
const providerSelection=configuredCognitionProvider(),liveProvider=providerSelection.provider??undefined,engine=new WorldEngine({...dataConfig,readonly:readOnly,deferSchema:command==='resources'||command==='economy'||readOnly},live?liveProvider:undefined,new DockerExecutionSandbox());
const fmt=(n:number)=>n===0?'0 B':n<1024?`${n} B`:`${(n/1024).toFixed(1)} KB`;
function printStatus(){const world=engine.repo.getWorld();if(!world){console.log('No world. Run: pnpm world genesis');return;}const agents=engine.repo.listAgents(),active=agents.filter((agent)=>agent.status==='active'),metrics=engine.repo.descendantMetrics();console.log(`AI WORLD\n\nWorld age: ${world.currentTick} ticks\nSimulated time: ${world.simulatedTime}\nStatus: ${world.status}\n\nPopulation: ${active.length}\nDescendant proposals: ${metrics.descendantProposals}\nDescendants created: ${metrics.descendantsCreated}\nGeneration counts: ${JSON.stringify(metrics.generationCounts)}\n\nAgents\n------------------------------------------------`);for(const agent of agents)console.log(`${agent.name.padEnd(9)} generation ${agent.generation}      ${agent.status}${agent.sleepingUntilTick>world.currentTick?` (waiting until ${agent.sleepingUntilTick})`:''}`);console.log('\nResources\n------------------------------------------------');for(const agent of agents){if(engine.repo.economy.version()===1)console.log(`${agent.name.padEnd(9)} legacy compute: ${agent.computeCredits}     storage: ${fmt(agent.storageBytes)} (resource migration required)`);else{const resources=engine.repo.economy.self(agent.id);console.log(`${agent.name.padEnd(9)} ${agent.status} / ${resources.cognitionDormant?'cognition-dormant':'cognitively available'}\n  cognition: ${resources.cognitionCredits.available} available / ${resources.cognitionCredits.reserved} reserved / ${resources.cognitionCredits.total} total; local compute: ${resources.localCompute.available} available / ${resources.localCompute.reserved} reserved / ${resources.localCompute.total} total\n  storage: ${fmt(agent.storageBytes)}; capital: ${Object.entries(resources.capital).map(([code,balance])=>`${formatCapital(code,balance.total)} (${balance.reserved} minor units reserved)`).join(', ')||'0 (no currency holdings)'}`);}}console.log('\nRecent events\n------------------------------------------------');for(const event of engine.repo.listEvents(10))console.log(`#${event.id} [tick ${event.tick}] ${event.type} ${event.actorId??''}`);}
function activity(limit:number){for(const event of engine.repo.listEvents(limit).reverse()){const actor=event.actorId?engine.repo.getAgent(event.actorId)?.name??(event.actorId==='owner:external'?'Owner':event.actorId):'world';let detail=event.payload.name??event.payload.path??event.payload.entrypoint??event.payload.outboxId??event.payload.ingressId??event.payload.runId??'';if(event.type==='TOOL_VERSION_PUBLISHED')detail=`${event.payload.toolVersionId??''} v${event.payload.version??'?'}`;if(event.type==='TOOL_INSPECTED')detail=`${event.payload.name??''} v${event.payload.version??'?'}`;if(event.type==='TOOL_INVOCATION_COMPLETED'||event.type==='TOOL_INVOCATION_FAILED')detail=`${event.payload.name??''} v${event.payload.version??'?'} -> exit ${event.payload.exitCode??'none'}`;if(event.type==='OWNER_MESSAGE_INGESTED')detail=`Owner -> ${event.subjectId?engine.repo.getAgent(event.subjectId)?.name??event.subjectId:'unknown'}`;console.log(`#${event.id}\tT${event.tick}\t${actor}\t${event.type}${detail?`\t${String(detail)}`:''}`);}}

try{
  if(['resume','tick','run','experiment'].includes(command))engine.repo.economy.requireModel();
  if(!readOnly&&!['resources','economy'].includes(command))await engine.initialize();
  if(live&&command!=='doctor'&&(!providerSelection.provider||!providerSelection.selected||!providerSelection.provider.configuration().configured))throw new Error(providerSelection.error??'Selected cognition provider configuration is incomplete');
  switch(command){
    case'resources':case'economy':console.log(JSON.stringify(economyCli(engine.repo,args),null,2));break;
    case'genesis':{const result=await engine.genesis();console.log(result.created?'Genesis initialized.':'Genesis already exists; no changes made.');for(const agent of result.agents)console.log(`${agent.name}: ${agent.id}`);break;}
    case'status':printStatus();break;
    case'agents':for(const agent of engine.repo.listAgents())console.log(`${agent.name}\t${agent.id}\tgeneration ${agent.generation}\t${agent.status}`);break;
    case'debug':{if(args[1]==='runner-lease')console.log(JSON.stringify(engine.repo.runnerLeaseDiagnostic(),null,2));else if(args[1]==='provider-cooldown')console.log(JSON.stringify(engine.repo.tickScheduleDiagnostic(),null,2));else if(args[1]==='descendant-proposals')console.log(JSON.stringify(engine.repo.descendantProposalAudit(),null,2));else if(args[1]==='lineage'){const agent=engine.repo.getAgent(args[2]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify({agent:{id:agent.id,name:agent.name,generation:agent.generation,status:agent.status},lineage:engine.repo.lineageFor(agent.id)},null,2));}else{const agent=engine.repo.getAgent(args[2]??'');if(!agent)throw new Error('Agent not found');if(args[1]==='inhabitants')console.log(JSON.stringify({inhabitants:engine.listPublicInhabitants(agent.id)},null,2));else if(args[1]==='cognition-context')console.log(JSON.stringify(await engine.cognitionContextDiagnostic(agent),null,2));else throw new Error('Usage: pnpm world debug inhabitants <name-or-id> | debug cognition-context <name-or-id> | debug descendant-proposals | debug lineage <name-or-id> | debug runner-lease | debug provider-cooldown');}break;}
    case'inspect':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify({...agent,messages:engine.repo.messagesFor(agent.id),memories:engine.repo.memoriesFor(agent.id),executions:engine.repo.executionsFor(agent.id)},null,2));break;}
    case'pause':engine.pause();console.log('World paused.');break;
    case'resume':engine.resume();console.log('World resumed.');break;
    case'tick':{const results=await engine.tick();if(engine.repo.getWorld()?.status==='paused')console.log('World is paused; no cycle performed.');else console.log(JSON.stringify(results,null,2));break;}
    case'run':{if(args.includes('--compute-ceiling')||args.includes('--max-compute'))throw new Error('Aggregate compute limits are deprecated; use --max-local-compute and --max-cognition-credits');
      if(args.includes('--continuous')){if(live&&(!providerSelection.provider||!providerSelection.selected||!providerSelection.provider.configuration().configured))throw new Error(providerSelection.error??'Selected cognition provider configuration is incomplete');const controller=new AbortController();process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());const runner=new ContinuousWorldRunner(engine);const result=await runner.run({tickMs:integerOption('--tick-ms',5_000),provider:live?providerSelection.selected!:'deterministic',...(live&&providerSelection.modelIdentifier?{modelIdentifier:providerSelection.modelIdentifier}:{}),...(option('--ticks')!==undefined?{maxTicks:integerOption('--ticks')}:{}),...(option('--max-local-compute')!==undefined?{maxLocalCompute:integerOption('--max-local-compute')}:{}),...(option('--max-cognition-credits')!==undefined?{maxCognitionCredits:integerOption('--max-cognition-credits')}:{}),...(option('--execution-limit')!==undefined?{executionLimit:integerOption('--execution-limit')}:{}),...(option('--wall-ms')!==undefined?{wallClockLimitMs:integerOption('--wall-ms')}:{}),signal:controller.signal});console.log(`Runner stopped: ${result.reason}; ${result.ticks} tick(s) completed. Run ID: ${result.runId}`);
      }else{const ticks=integerOption('--ticks',1);if(ticks<1||ticks>10_000)throw new Error('--ticks must be from 1 to 10000');const results=await engine.run(ticks);console.log(`Completed ${results.length} tick(s)${live?' using live cognition':''}.`);printStatus();}break;}
    case'events':console.log(JSON.stringify(engine.repo.listEvents(100),null,2));break;
    case'activity':activity(integerOption('--last',50));break;
    case'memories':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');const query=option('--query');console.log(JSON.stringify(query?engine.repo.relevantMemories(agent.id,query,engine.repo.getWorld()?.currentTick??0,100):engine.repo.memoriesFor(agent.id,100),null,2));break;}
    case'messages':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify(engine.repo.messagesFor(agent.id,100),null,2));break;}
    case'executions':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify(engine.repo.executionsFor(agent.id,100),null,2));break;}
    case'files':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log((await engine.files.list(agent.id,'.',args.includes('--shared')?'shared':'private')).join('\n'));break;}
    case'message':{const to=args[1],content=args.slice(2).join(' ');if(!to||!content)throw new Error('Usage: pnpm world message <agent> <content>');await engine.ownerMessage(to,content);console.log(`Owner message durably ingested for ${to}.`);break;}
    case'tools':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Usage: pnpm world tools <agent>');console.log(JSON.stringify(engine.repo.accessibleTools(agent.id),null,2));break;}
    case'tool':{if(args[1]!=='inspect')throw new Error('Usage: pnpm world tool inspect <agent> <version-id>');const agent=engine.repo.getAgent(args[2]??''),version=engine.repo.getToolVersion(args[3]??'');if(!agent||!version||!engine.repo.canAccessTool(agent.id,version))throw new Error('Tool not found or not authorized');console.log(JSON.stringify(version,null,2));break;}
    case'doctor':{if(args.includes('--integrity-only')){const errors=engine.repo.economy.integrity();console.log(JSON.stringify({sqliteIntegrity:engine.repo.databaseIntegrity(),resourceModelVersion:engine.repo.economy.version(),resourceEconomyIntegrity:errors.length?errors:'ok',world:engine.repo.getWorld(),agents:engine.repo.listAgents().map(({id,name,computeCredits,storageBytes,sleepingUntilTick})=>({id,name,...(engine.repo.economy.version()===2?engine.repo.economy.self(id):{legacyCompute:computeCredits}),storageBytes,sleepingUntilTick})),runnerLease:engine.repo.runnerLeaseDiagnostic(),pendingScheduler:engine.repo.tickScheduleDiagnostic()},null,2));if(engine.repo.databaseIntegrity()!=='ok'||errors.length)process.exitCode=2;}else if(live){const report=await new LiveReadinessDoctor(engine).verify({live:true,pull:args.includes('--pull')});for(const check of report.checks)console.log(`${check.passed?'PASS':check.required?'FAIL':'WARN'}  ${check.name}: ${check.detail}`);console.log(`\nLive experiment: ${report.readyForLiveExperiment?'READY':'NOT READY'}`);if(!report.readyForLiveExperiment)process.exitCode=2;}else{const report=await new SandboxDoctor().verify({pull:args.includes('--pull')}),leaseChecks=runnerLeaseDoctorChecks(engine.repo);for(const check of [...report.checks,...leaseChecks])console.log(`${check.passed?'PASS':'FAIL'}  ${check.name}: ${check.detail}`);const resourceFailures=engine.repo.economy.integrity();console.log(`Resource model v${engine.repo.economy.version()}: ${resourceFailures.length?resourceFailures.join('; '):'ledger and reservations consistent'}`);console.log(`SQLite integrity: ${engine.repo.databaseIntegrity()}`);const healthy=report.operationallyVerified&&leaseChecks.every((check)=>check.passed)&&resourceFailures.length===0&&engine.repo.databaseIntegrity()==='ok';console.log(`\nExecution sandbox and runner lease: ${healthy?'OPERATIONALLY VERIFIED':'NOT OPERATIONALLY VERIFIED'}`);if(!healthy)process.exitCode=2;}break;}
    case'experiment':{if(!live)throw new Error('Experiment requires explicit --live');if(!providerSelection.provider||!providerSelection.selected||!providerSelection.provider.configuration().configured)throw new Error(providerSelection.error??'Selected cognition provider configuration is incomplete');const limits=resolveExperimentCliLimits(args);if(engine.repo.getWorld()?.status!=='running')throw new Error('World is paused; run resume first');const label=option('--label');if(label&&!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/.test(label))throw new Error('--label must be 1-80 safe characters');console.log(formatExperimentLimits(limits));const controller=new AbortController();process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());const result=await new ContinuousWorldRunner(engine).run({tickMs:integerOption('--tick-ms',0),...(label?{label}:{}),maxTicks:limits.maxTicks,maxCognitionTurns:limits.maxCognitionTurns,maxInputTokens:limits.maxInputTokens,maxOutputTokens:limits.maxOutputTokens,provider:providerSelection.selected,modelIdentifier:providerSelection.modelIdentifier??'missing',maxLocalCompute:limits.maxLocalCompute,maxCognitionCredits:limits.maxCognitionCredits,executionLimit:limits.executionLimit,wallClockLimitMs:limits.wallClockLimitMs,...(limits.profile==='long'?{rateLimitSuspension:LONG_RATE_LIMIT_SUSPENSION}:{}),signal:controller.signal});console.log(JSON.stringify(result,null,2));break;}
    case'runs':console.log(JSON.stringify(engine.repo.listAutonomyRuns().map(run=>createRunReport(engine.repo,run.id)),null,2));break;
    case'run-report':console.log(JSON.stringify(createRunReport(engine.repo,args[1]??''),null,2));break;
    case'experiment-report':console.log(JSON.stringify(createExperimentReport(engine.repo,args[1]??''),null,2));break;
    case'checkpoint':{const service=new WorldCheckpointService(engine.config.dataDir,engine.repo);if(args[1]==='create'){const label=args[2];if(!label)throw new Error('Usage: pnpm world checkpoint create <label>');console.log(JSON.stringify(await service.create(label),null,2));}else if(args[1]==='list')console.log(JSON.stringify(engine.repo.listCheckpoints(),null,2));else throw new Error('Usage: pnpm world checkpoint create <label> | checkpoint list');break;}
    case'pending-provider':{if(args[1]==='show')console.log(JSON.stringify(engine.repo.pendingProviderDiagnostic(),null,2));else if(args[1]==='migrate'){const provider=option('--provider'),modelIdentifier=option('--model');if(!provider||!modelIdentifier)throw new Error('Usage: pnpm world pending-provider migrate --provider <provider> --model <model>');const result=await migratePendingProvider(engine.repo,{provider,modelIdentifier});console.log(JSON.stringify({changed:result.changed,...engine.repo.pendingProviderDiagnostic()},null,2));}else throw new Error('Usage: pnpm world pending-provider show | pending-provider migrate --provider <provider> --model <model>');break;}
    case'owner-outbox':console.log(JSON.stringify(engine.repo.listOutbox(),null,2));break;
    case'gateway':{if(args[1]==='dispatch'){const gateways=configuredOwnerGateways();if(args.includes('--console')&&!gateways.some((gateway)=>gateway.name==='console'))gateways.push(new ConsoleOwnerGateway());const result=await new OwnerGatewayDispatcher(engine.repo,gateways).dispatch();console.log(`Owner outbox: ${result.delivered} delivered, ${result.failed} failed.`);}else if(args[1]==='line-listen'){const secret=process.env.LINE_CHANNEL_SECRET,ownerSourceId=process.env.LINE_OWNER_SOURCE_ID;if(!secret||!ownerSourceId)throw new Error('LINE_CHANNEL_SECRET and LINE_OWNER_SOURCE_ID are required');const ingress=new LineWebhookIngress(engine.ownerIngress,engine.repo,{channelSecret:secret,ownerSourceId}),server=await createLineWebhookServer(ingress,integerOption('--port',8787)),controller=new AbortController();console.log(`LINE webhook listening on http://127.0.0.1:${integerOption('--port',8787)}/line/webhook; expose only through Owner-controlled HTTPS termination.`);process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());await new Promise<void>((resolve)=>controller.signal.addEventListener('abort',()=>resolve(),{once:true}));await ingress.drain();await new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}else throw new Error('Usage: pnpm world gateway dispatch [--console] | gateway line-listen [--port N]');break;}
    default:console.log('Commands: resources status|ledger|inject|transfer|requests|request|migration-status|migrate-legacy | economy status|ledger|invest|record-revenue|transfer | genesis | status | doctor [--live] [--pull] | agents | debug inhabitants <name-or-id> | debug cognition-context <name-or-id> | debug descendant-proposals | debug lineage <name-or-id> | debug runner-lease | debug provider-cooldown | pending-provider show | pending-provider migrate --provider <provider> --model <model> | inspect <name> | pause | resume | tick | run --ticks N | run --continuous [limits] | experiment --live --ticks N [--profile default|long] [limit overrides] | experiment --ticks N --profile default|long --show-limits | runs | run-report <id-or-label> | experiment-report <id-or-label> | checkpoint create <label> | checkpoint list | events | activity --last N | memories <name> [--query text] | messages <name> | executions <name> | files <name> [--shared] | tools <name> | tool inspect <name> <version-id> | message <name> <text> | owner-outbox | gateway dispatch [--console] | gateway line-listen [--port N]');
  }
}finally{engine.close();}
}
