#!/usr/bin/env node
import { OpenAICompatibleCognitionProvider } from '../../../packages/cognition/src/index.js';
import { configuredOwnerGateways,ConsoleOwnerGateway,OwnerGatewayDispatcher } from '../../../packages/messaging/src/index.js';
import { createLineWebhookServer,LineWebhookIngress } from '../../../packages/messaging/src/ingress.js';
import { SandboxDoctor } from '../../../packages/operations/src/doctor.js';
import { LiveReadinessDoctor } from '../../../packages/operations/src/live-doctor.js';
import { WorldCheckpointService } from '../../../packages/operations/src/checkpoint.js';
import { createExperimentReport } from '../../../packages/operations/src/experiment-report.js';
import { createRunReport } from '../../../packages/operations/src/run-report.js';
import { DockerExecutionSandbox } from '../../../packages/sandbox/src/docker.js';
import { WorldEngine,defaultConfig } from '../../../packages/world/src/engine.js';
import { ContinuousWorldRunner } from '../../../packages/world/src/runner.js';

try{process.loadEnvFile();}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
const args=process.argv.slice(2),command=args[0]??'help',live=args.includes('--live'),providerName=process.env.COGNITION_PROVIDER,liveProvider=new OpenAICompatibleCognitionProvider(),engine=new WorldEngine(defaultConfig(),live?liveProvider:undefined,new DockerExecutionSandbox());
const option=(name:string)=>{const index=args.indexOf(name);return index>=0?args[index+1]:undefined;};
const integerOption=(name:string,fallback?:number)=>{const raw=option(name);if(raw===undefined&&fallback!==undefined)return fallback;const value=Number(raw);if(!Number.isInteger(value)||value<0)throw new Error(`${name} must be a non-negative integer`);return value;};
const fmt=(n:number)=>n===0?'0 B':n<1024?`${n} B`:`${(n/1024).toFixed(1)} KB`;
function printStatus(){const world=engine.repo.getWorld();if(!world){console.log('No world. Run: pnpm world genesis');return;}const agents=engine.repo.listAgents();console.log(`AI WORLD\n\nWorld age: ${world.currentTick} ticks\nSimulated time: ${world.simulatedTime}\nStatus: ${world.status}\n\nPopulation: ${agents.length}\n\nAgents\n------------------------------------------------`);for(const agent of agents)console.log(`${agent.name.padEnd(9)} generation ${agent.generation}      ${agent.status}${agent.sleepingUntilTick>world.currentTick?` (waiting until ${agent.sleepingUntilTick})`:''}`);console.log('\nResources\n------------------------------------------------');for(const agent of agents)console.log(`${agent.name.padEnd(9)} compute: ${agent.computeCredits}     storage: ${fmt(agent.storageBytes)}`);console.log('\nRecent events\n------------------------------------------------');for(const event of engine.repo.listEvents(10))console.log(`#${event.id} [tick ${event.tick}] ${event.type} ${event.actorId??''}`);}
function activity(limit:number){for(const event of engine.repo.listEvents(limit).reverse()){const actor=event.actorId?engine.repo.getAgent(event.actorId)?.name??(event.actorId==='owner:external'?'Owner':event.actorId):'world';let detail=event.payload.name??event.payload.path??event.payload.entrypoint??event.payload.outboxId??event.payload.ingressId??event.payload.runId??'';if(event.type==='TOOL_VERSION_PUBLISHED')detail=`${event.payload.toolVersionId??''} v${event.payload.version??'?'}`;if(event.type==='TOOL_INSPECTED')detail=`${event.payload.name??''} v${event.payload.version??'?'}`;if(event.type==='TOOL_INVOCATION_COMPLETED'||event.type==='TOOL_INVOCATION_FAILED')detail=`${event.payload.name??''} v${event.payload.version??'?'} -> exit ${event.payload.exitCode??'none'}`;if(event.type==='OWNER_MESSAGE_INGESTED')detail=`Owner -> ${event.subjectId?engine.repo.getAgent(event.subjectId)?.name??event.subjectId:'unknown'}`;console.log(`#${event.id}\tT${event.tick}\t${actor}\t${event.type}${detail?`\t${String(detail)}`:''}`);}}

try{
  await engine.initialize();
  switch(command){
    case'genesis':{const result=await engine.genesis();console.log(result.created?'Genesis initialized.':'Genesis already exists; no changes made.');for(const agent of result.agents)console.log(`${agent.name}: ${agent.id}`);break;}
    case'status':printStatus();break;
    case'agents':for(const agent of engine.repo.listAgents())console.log(`${agent.name}\t${agent.id}\tgeneration ${agent.generation}\t${agent.status}`);break;
    case'inspect':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify({...agent,messages:engine.repo.messagesFor(agent.id),memories:engine.repo.memoriesFor(agent.id),executions:engine.repo.executionsFor(agent.id)},null,2));break;}
    case'pause':engine.pause();console.log('World paused.');break;
    case'resume':engine.resume();console.log('World resumed.');break;
    case'tick':{const results=await engine.tick();if(engine.repo.getWorld()?.status==='paused')console.log('World is paused; no cycle performed.');else console.log(JSON.stringify(results,null,2));break;}
    case'run':{
      if(args.includes('--continuous')){const controller=new AbortController();process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());const runner=new ContinuousWorldRunner(engine);const result=await runner.run({tickMs:integerOption('--tick-ms',5_000),provider:live?'openai-compatible':'deterministic',...(option('--ticks')!==undefined?{maxTicks:integerOption('--ticks')}:{}),...(option('--compute-ceiling')!==undefined?{computeCeiling:integerOption('--compute-ceiling')}:{}),...(option('--execution-limit')!==undefined?{executionLimit:integerOption('--execution-limit')}:{}),...(option('--wall-ms')!==undefined?{wallClockLimitMs:integerOption('--wall-ms')}:{}),signal:controller.signal});console.log(`Runner stopped: ${result.reason}; ${result.ticks} tick(s) completed. Run ID: ${result.runId}`);
      }else{const ticks=integerOption('--ticks',1);if(ticks<1||ticks>10_000)throw new Error('--ticks must be from 1 to 10000');const results=await engine.run(ticks);console.log(`Completed ${results.length} tick(s)${live?' using live cognition':''}.`);printStatus();}break;}
    case'events':console.log(JSON.stringify(engine.repo.listEvents(100),null,2));break;
    case'activity':activity(integerOption('--last',50));break;
    case'memories':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');const query=option('--query');console.log(JSON.stringify(query?engine.repo.relevantMemories(agent.id,query,engine.repo.getWorld()?.currentTick??0,100):engine.repo.memoriesFor(agent.id,100),null,2));break;}
    case'messages':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify(engine.repo.messagesFor(agent.id,100),null,2));break;}
    case'executions':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log(JSON.stringify(engine.repo.executionsFor(agent.id,100),null,2));break;}
    case'files':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Agent not found');console.log((await engine.files.list(agent.id,'.',args.includes('--shared')?'shared':'private')).join('\n'));break;}
    case'message':{const to=args[1],content=args.slice(2).join(' ');if(!to||!content)throw new Error('Usage: pnpm world message <agent> <content>');await engine.ownerMessage(to,content);console.log(`Owner message durably ingested for ${to}.`);break;}
    case'tools':{const agent=engine.repo.getAgent(args[1]??'');if(!agent)throw new Error('Usage: pnpm world tools <agent>');console.log(JSON.stringify(engine.repo.accessibleTools(agent.id),null,2));break;}
    case'tool':{if(args[1]!=='inspect')throw new Error('Usage: pnpm world tool inspect <agent> <version-id>');const agent=engine.repo.getAgent(args[2]??''),version=engine.repo.getToolVersion(args[3]??'');if(!agent||!version||!engine.repo.canAccessTool(agent.id,version))throw new Error('Tool not found or not authorized');console.log(JSON.stringify(version,null,2));break;}
    case'doctor':{if(live){const report=await new LiveReadinessDoctor(engine,undefined,liveProvider).verify({live:true,pull:args.includes('--pull')});for(const check of report.checks)console.log(`${check.passed?'PASS':check.required?'FAIL':'WARN'}  ${check.name}: ${check.detail}`);console.log(`\nLive experiment: ${report.readyForLiveExperiment?'READY':'NOT READY'}`);if(!report.readyForLiveExperiment)process.exitCode=2;}else{const report=await new SandboxDoctor().verify({pull:args.includes('--pull')});for(const check of report.checks)console.log(`${check.passed?'PASS':'FAIL'}  ${check.name}: ${check.detail}`);console.log(`\nExecution sandbox: ${report.operationallyVerified?'OPERATIONALLY VERIFIED':'NOT OPERATIONALLY VERIFIED'}`);if(!report.operationallyVerified)process.exitCode=2;}break;}
    case'experiment':{if(!live)throw new Error('Experiment requires explicit --live');if(providerName!=='openai')throw new Error('COGNITION_PROVIDER=openai is required');const ticks=integerOption('--ticks');if(ticks<1)throw new Error('--ticks must be at least 1');if(engine.repo.getWorld()?.status!=='running')throw new Error('World is paused; run resume first');const label=option('--label');if(label&&!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/.test(label))throw new Error('--label must be 1-80 safe characters');const controller=new AbortController();process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());const result=await new ContinuousWorldRunner(engine).run({tickMs:integerOption('--tick-ms',0),...(label?{label}:{}),maxTicks:ticks,maxCognitionTurns:integerOption('--max-cognition-turns',ticks*2),maxInputTokens:integerOption('--max-input-tokens',250_000),maxOutputTokens:integerOption('--max-output-tokens',50_000),provider:'openai-compatible',modelIdentifier:process.env.OPENAI_MODEL??'missing',computeCeiling:integerOption('--compute-ceiling',1_000),executionLimit:integerOption('--execution-limit',20),wallClockLimitMs:integerOption('--wall-ms',15*60_000),signal:controller.signal});console.log(JSON.stringify(result,null,2));break;}
    case'runs':console.log(JSON.stringify(engine.repo.listAutonomyRuns(),null,2));break;
    case'run-report':console.log(JSON.stringify(createRunReport(engine.repo,args[1]??''),null,2));break;
    case'experiment-report':console.log(JSON.stringify(createExperimentReport(engine.repo,args[1]??''),null,2));break;
    case'checkpoint':{const service=new WorldCheckpointService(engine.config.dataDir,engine.repo);if(args[1]==='create'){const label=args[2];if(!label)throw new Error('Usage: pnpm world checkpoint create <label>');console.log(JSON.stringify(await service.create(label),null,2));}else if(args[1]==='list')console.log(JSON.stringify(engine.repo.listCheckpoints(),null,2));else throw new Error('Usage: pnpm world checkpoint create <label> | checkpoint list');break;}
    case'owner-outbox':console.log(JSON.stringify(engine.repo.listOutbox(),null,2));break;
    case'gateway':{if(args[1]==='dispatch'){const gateways=configuredOwnerGateways();if(args.includes('--console')&&!gateways.some((gateway)=>gateway.name==='console'))gateways.push(new ConsoleOwnerGateway());const result=await new OwnerGatewayDispatcher(engine.repo,gateways).dispatch();console.log(`Owner outbox: ${result.delivered} delivered, ${result.failed} failed.`);}else if(args[1]==='line-listen'){const secret=process.env.LINE_CHANNEL_SECRET,ownerSourceId=process.env.LINE_OWNER_SOURCE_ID;if(!secret||!ownerSourceId)throw new Error('LINE_CHANNEL_SECRET and LINE_OWNER_SOURCE_ID are required');const ingress=new LineWebhookIngress(engine.ownerIngress,engine.repo,{channelSecret:secret,ownerSourceId}),server=await createLineWebhookServer(ingress,integerOption('--port',8787)),controller=new AbortController();console.log(`LINE webhook listening on http://127.0.0.1:${integerOption('--port',8787)}/line/webhook; expose only through Owner-controlled HTTPS termination.`);process.once('SIGINT',()=>controller.abort());process.once('SIGTERM',()=>controller.abort());await new Promise<void>((resolve)=>controller.signal.addEventListener('abort',()=>resolve(),{once:true}));await ingress.drain();await new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));}else throw new Error('Usage: pnpm world gateway dispatch [--console] | gateway line-listen [--port N]');break;}
    default:console.log('Commands: genesis | status | doctor [--live] [--pull] | agents | inspect <name> | pause | resume | tick | run --ticks N | run --continuous [limits] | experiment --live --label <name> --ticks N [token/compute/execution/wall limits] | runs | run-report <id-or-label> | experiment-report <id-or-label> | checkpoint create <label> | checkpoint list | events | activity --last N | memories <name> [--query text] | messages <name> | executions <name> | files <name> [--shared] | tools <name> | tool inspect <name> <version-id> | message <name> <text> | owner-outbox | gateway dispatch [--console] | gateway line-listen [--port N]');
  }
}finally{engine.close();}
