#!/usr/bin/env node
import { OpenAICompatibleCognitionProvider } from '../../../packages/cognition/src/index.js';
import { WorldEngine, defaultConfig } from '../../../packages/world/src/engine.js';

const args=process.argv.slice(2), command=args[0]??'help', live=args.includes('--live');
const engine=new WorldEngine(defaultConfig(),live?new OpenAICompatibleCognitionProvider():undefined);
const fmt=(n:number)=>n===0?'0 B':n<1024?`${n} B`:`${(n/1024).toFixed(1)} KB`;
const printStatus=()=>{const w=engine.repo.getWorld();if(!w){console.log('No world. Run: pnpm world genesis');return;}const agents=engine.repo.listAgents();console.log(`AI WORLD\n\nWorld age: ${w.currentTick} ticks\nSimulated time: ${w.simulatedTime}\nStatus: ${w.status}\n\nPopulation: ${agents.length}\n\nAgents\n------------------------------------------------`);for(const a of agents)console.log(`${a.name.padEnd(9)} generation ${a.generation}      ${a.status}`);console.log('\nResources\n------------------------------------------------');for(const a of agents)console.log(`${a.name.padEnd(9)} compute: ${a.computeCredits}     storage: ${fmt(a.storageBytes)}`);console.log('\nRecent events\n------------------------------------------------');for(const e of engine.repo.listEvents(10))console.log(`#${e.id} [tick ${e.tick}] ${e.type} ${e.actorId??''}`);};
try{switch(command){case'genesis':{const r=await engine.genesis();console.log(r.created?'Genesis initialized.':'Genesis already exists; no changes made.');for(const a of r.agents)console.log(`${a.name}: ${a.id}`);break;}case'status':printStatus();break;case'agents':for(const a of engine.repo.listAgents())console.log(`${a.name}\t${a.id}\tgeneration ${a.generation}\t${a.status}`);break;case'inspect':{const a=engine.repo.getAgent(args[1]??'');if(!a)throw new Error('Agent not found');console.log(JSON.stringify({...a,messages:engine.repo.messagesFor(a.id),memories:engine.repo.memoriesFor(a.id)},null,2));break;}case'tick':console.log(JSON.stringify(await engine.tick(),null,2));break;case'run':{const i=args.indexOf('--ticks'),ticks=Number(i>=0?args[i+1]:1);if(!Number.isInteger(ticks)||ticks<1||ticks>10_000)throw new Error('--ticks must be an integer from 1 to 10000');const results=await engine.run(ticks);console.log(`Completed ${results.length} tick(s)${live?' using live cognition':''}.`);printStatus();break;}case'events':console.log(JSON.stringify(engine.repo.listEvents(100),null,2));break;case'memories':{const a=engine.repo.getAgent(args[1]??'');if(!a)throw new Error('Agent not found');console.log(JSON.stringify(engine.repo.memoriesFor(a.id,100),null,2));break;}case'files':{const a=engine.repo.getAgent(args[1]??'');if(!a)throw new Error('Agent not found');console.log((await engine.files.list(a.id)).join('\n'));break;}case'message':{const to=args[1],content=args.slice(2).join(' ');if(!to||!content)throw new Error('Usage: pnpm world message <agent> <content>');engine.ownerMessage(to,content);console.log(`Owner message sent to ${to}.`);break;}default:console.log('Commands: genesis | status | agents | inspect <name> | tick | run --ticks N [--live] | events | memories <name> | files <name> | message <name> <text>');}}finally{engine.close();}
