import { createHash,randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { WorldRepository } from '../../persistence/src/repository.js';
import type { CheckpointRecord } from '../../shared/src/index.js';

const digestFile=async(file:string)=>createHash('sha256').update(await fs.readFile(file)).digest('hex');
export class WorldCheckpointService{
  constructor(private readonly dataDir:string,private readonly repo:WorldRepository){}
  async create(label:string):Promise<CheckpointRecord>{if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/.test(label))throw new Error('Checkpoint label must be 1-80 safe characters');const world=this.repo.getWorld();if(!world)throw new Error('World does not exist');if(world.status!=='paused')throw new Error('World must be paused before checkpoint creation');if(this.repo.runnerLeaseStatus().active)throw new Error('Cannot checkpoint while a runner lease is active');const id=randomUUID(),parent=path.resolve(`${this.dataDir}-checkpoints`),target=path.join(parent,`${new Date().toISOString().replaceAll(':','-')}-${label}-${id.slice(0,8)}`),staged=`${target}.staging`;await fs.mkdir(staged,{recursive:true});try{const databasePath=path.join(staged,'world.sqlite');await this.repo.backup(databasePath);for(const name of ['agents','shared','system'] as const){const source=path.join(this.dataDir,name);try{await this.copyTree(source,path.join(staged,name));}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}const databaseHash=await digestFile(databasePath),artifactHash=await this.treeHash(staged,new Set(['world.sqlite','metadata.json'])),createdAt=new Date().toISOString(),record:CheckpointRecord={id,label,createdAt,tick:world.currentTick,databaseHash,artifactHash,backupPath:target};await fs.writeFile(path.join(staged,'metadata.json'),JSON.stringify(record,null,2),{flag:'wx',mode:0o600});await fs.mkdir(parent,{recursive:true});await fs.rename(staged,target);this.repo.createCheckpoint(record);this.repo.addEvent('WORLD_CHECKPOINT_CREATED',world.currentTick,null,null,{checkpointId:id,label,databaseHash,artifactHash,backupPath:target});return record;}catch(error){await fs.rm(staged,{recursive:true,force:true}).catch(()=>undefined);throw error;}}
  private async copyTree(source:string,destination:string):Promise<void>{const stat=await fs.lstat(source);if(stat.isSymbolicLink()||!stat.isDirectory())throw new Error('Checkpoint source root must be a regular directory');await fs.mkdir(destination,{recursive:true});for(const entry of await fs.readdir(source,{withFileTypes:true})){const from=path.join(source,entry.name),to=path.join(destination,entry.name),entryStat=await fs.lstat(from);if(entryStat.isSymbolicLink())throw new Error('Checkpoint refuses links and reparse points');if(entryStat.isDirectory())await this.copyTree(from,to);else if(entryStat.isFile())await fs.copyFile(from,to);else throw new Error('Checkpoint refuses special filesystem entries');}}
  private async treeHash(root:string,excluded:Set<string>):Promise<string>{const digest=createHash('sha256'),files:string[]=[];const walk=async(directory:string):Promise<void>=>{for(const entry of await fs.readdir(directory,{withFileTypes:true})){const target=path.join(directory,entry.name),relative=path.relative(root,target).replaceAll('\\','/');if(excluded.has(relative))continue;if(entry.isDirectory())await walk(target);else if(entry.isFile())files.push(relative);else throw new Error('Checkpoint hash refuses special entries');}};await walk(root);for(const relative of files.sort()){digest.update(relative).update('\0').update(await fs.readFile(path.join(root,...relative.split('/')))).update('\0');}return digest.digest('hex');}
}
