import { mkdtemp,rm,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { DEFAULT_DOCKER_LIMITS,DockerExecutionSandbox,RUNTIME_POLICIES,executeDockerCommand,type DockerCommandResult,type DockerLimits } from '../../sandbox/src/docker.js';
import type { ExecutionSandbox } from '../../sandbox/src/filesystem.js';

export interface DoctorCheck{name:string;passed:boolean;detail:string;}
export interface SandboxDoctorReport{operationallyVerified:boolean;checks:DoctorCheck[];runtimeIdentity:{runtime:'node'|'python';tag:string;expectedDigest:string;resolvedDigest:string|null;verified:boolean}[];}
type Command=(args:string[],timeoutMs?:number)=>Promise<DockerCommandResult>;
type SandboxFactory=(limits:DockerLimits)=>ExecutionSandbox;

export class SandboxDoctor{
  constructor(private readonly command:Command=executeDockerCommand,private readonly sandboxFactory:SandboxFactory=(limits)=>new DockerExecutionSandbox(limits)){}
  async verify(options:{pull?:boolean}={}):Promise<SandboxDoctorReport>{const checks:DoctorCheck[]=[],runtimeIdentity:SandboxDoctorReport['runtimeIdentity']=[];const version=await this.command(['version','--format','{{.Server.Version}}'],3_000);checks.push({name:'Docker daemon',passed:version.exitCode===0,detail:version.exitCode===0?version.stdout.trim():(version.error??(version.stderr.trim()||'unavailable'))});if(version.exitCode!==0)return{operationallyVerified:false,checks:[{name:'Docker CLI',passed:version.exitCode!==null,detail:version.exitCode===null?'not installed':'installed'},...checks],runtimeIdentity};checks.unshift({name:'Docker CLI',passed:true,detail:'installed'});const os=await this.command(['info','--format','{{.OSType}}'],3_000);checks.push({name:'Linux container engine',passed:os.exitCode===0&&os.stdout.trim()==='linux',detail:os.stdout.trim()||os.stderr.trim()});
    for(const runtime of ['node','python'] as const){const policy=RUNTIME_POLICIES[runtime];if(options.pull)await this.command(['pull',policy.reference],120_000);const inspect=await this.command(['image','inspect','--format','{{join .RepoDigests "\\n"}}',policy.reference],5_000),resolved=inspect.exitCode===0?inspect.stdout.trim():null,verified=!!resolved?.includes(policy.digest);runtimeIdentity.push({runtime,tag:policy.tag,expectedDigest:policy.digest,resolvedDigest:resolved,verified});checks.push({name:`${runtime} image identity`,passed:verified,detail:verified?policy.digest:inspect.stderr.trim()||'missing or unexpected digest'});}
    if(checks.some((check)=>!check.passed))return{operationallyVerified:false,checks,runtimeIdentity};const workspace=await mkdtemp(path.join(tmpdir(),'automaticworld-doctor-'));try{await writeFile(path.join(workspace,'node.js'),'console.log(21 * 2);');await writeFile(path.join(workspace,'python.py'),'print(21 * 2)');await writeFile(path.join(workspace,'network.js'),"const net=require('net');let done=false;const blocked=()=>{if(!done){done=true;console.log('NETWORK_BLOCKED');process.exit(0)}};net.connect(80,'1.1.1.1').on('connect',()=>{console.log('NETWORK_REACHED');process.exit(2)}).on('error',blocked);setTimeout(blocked,500);");await writeFile(path.join(workspace,'forever.js'),'setInterval(() => {}, 1000);');await writeFile(path.join(workspace,'output.js'),"process.stdout.write('x'.repeat(100000));");await writeFile(path.join(workspace,'isolation.js'),"const fs=require('fs');console.log(['/root/.env','/world.sqlite','/other-agent'].some(fs.existsSync)?'HOST_VISIBLE':'ISOLATED');");const normal=this.sandboxFactory(DEFAULT_DOCKER_LIMITS),timeoutSandbox=this.sandboxFactory({...DEFAULT_DOCKER_LIMITS,timeoutMs:500,outputBytes:1024}),outputSandbox=this.sandboxFactory({...DEFAULT_DOCKER_LIMITS,timeoutMs:5_000,outputBytes:1024});const request=(runtime:'node'|'python',entrypoint:string)=>({runtime,workspacePath:workspace,entrypoint,args:[],stdin:''});const node=await normal.execute(request('node','node.js')),python=await normal.execute(request('python','python.py')),network=await normal.execute(request('node','network.js')),timeout=await timeoutSandbox.execute(request('node','forever.js')),output=await outputSandbox.execute(request('node','output.js')),isolation=await normal.execute(request('node','isolation.js'));checks.push({name:'Restricted container start / Node',passed:node.success&&node.stdout.trim()==='42',detail:node.error??node.stdout.trim()});checks.push({name:'Python execution',passed:python.success&&python.stdout.trim()==='42',detail:python.error??python.stdout.trim()});checks.push({name:'Network isolation',passed:network.success&&network.stdout.includes('NETWORK_BLOCKED'),detail:network.error??network.stdout.trim()});checks.push({name:'Timeout enforcement',passed:timeout.timedOut,detail:`timedOut=${timeout.timedOut}`});checks.push({name:'Output limiting',passed:output.truncated&&Buffer.byteLength(output.stdout+output.stderr)<=1024,detail:`truncated=${output.truncated}, timedOut=${output.timedOut}, bytes=${Buffer.byteLength(output.stdout+output.stderr)}${output.error?`, error=${output.error}`:''}`});checks.push({name:'Filesystem isolation',passed:isolation.success&&isolation.stdout.includes('ISOLATED'),detail:isolation.error??isolation.stdout.trim()});}finally{await rm(workspace,{recursive:true,force:true});}return{operationallyVerified:checks.every((check)=>check.passed),checks,runtimeIdentity};}
}
