import { createHash } from 'node:crypto';
import type { FilesystemOperation,WorldRepository } from '../../persistence/src/repository.js';
import type { AgentFilesystem,FileMutation } from '../../sandbox/src/filesystem.js';

export type MutationTransition='after-prepared'|'after-filesystem-commit'|'after-filesystem-journal'|'after-database-commit';
export interface MutationHooks{onTransition?(transition:MutationTransition,operation:FilesystemOperation):Promise<void>|void;}
export class InjectedCrash extends Error{}
const hash=(content:string)=>createHash('sha256').update(content).digest('hex');

export class FilesystemMutationCoordinator{
  constructor(private readonly repo:WorldRepository,private readonly files:AgentFilesystem,private readonly hooks:MutationHooks={}){}
  async mutate(input:{agentId:string;space:'private'|'shared';path:string;kind:'create'|'write'|'append';content:string;expectedHash?:string;tick:number;eventType:string}):Promise<{operationId:string;mutation:FileMutation;revision:number}>{const before=await this.files.inspectFile(input.agentId,input.path,input.space),finalContent=input.kind==='append'?(before?.content??'')+input.content:input.content,operation=this.repo.createFilesystemOperation({agentId:input.agentId,space:input.space,path:input.path,kind:input.kind,beforeBytes:before?.bytes??0,afterBytes:Buffer.byteLength(finalContent),beforeHash:before?.hash??null,afterHash:hash(finalContent),tick:input.tick,eventType:input.eventType});await this.hooks.onTransition?.('after-prepared',operation);let mutation:FileMutation;try{mutation=input.kind==='create'?await this.files.create(input.agentId,input.path,input.content,input.space):input.kind==='write'?await this.files.write(input.agentId,input.path,input.content,input.space,input.expectedHash):await this.files.append(input.agentId,input.path,input.content,input.space,input.expectedHash);}catch(error){if(error instanceof InjectedCrash)throw error;this.repo.updateFilesystemOperation(operation.id,'FAILED',error instanceof Error?error.message:'Filesystem mutation failed');throw error;}await this.hooks.onTransition?.('after-filesystem-commit',operation);this.repo.updateFilesystemOperation(operation.id,'FILESYSTEM_COMMITTED');await this.hooks.onTransition?.('after-filesystem-journal',operation);this.repo.commitFilesystemOperation(operation.id);await this.hooks.onTransition?.('after-database-commit',operation);this.repo.updateFilesystemOperation(operation.id,'COMPLETE');return{operationId:operation.id,mutation,revision:this.repo.getArtifactRevision(input.space,input.path)!.revision};}
  async reconcile(tick:number):Promise<{completed:number;failed:number;stagingRemoved:number}>{const operations=this.repo.incompleteFilesystemOperations();if(operations.length===0)return{completed:0,failed:0,stagingRemoved:await this.files.cleanupKernelStaging(this.repo.listAgents().map((agent)=>agent.id))};this.repo.addEvent('FILESYSTEM_RECONCILIATION_STARTED',tick,null,null,{operations:operations.length});let completed=0,failed=0;for(const operation of operations){try{if(operation.state==='PREPARED'||operation.state==='STAGED'){const current=await this.files.inspectFile(operation.agentId,operation.path,operation.space);if(current?.hash===operation.afterHash)this.repo.updateFilesystemOperation(operation.id,'FILESYSTEM_COMMITTED');else if(current?.hash===(operation.beforeHash??undefined)||(!current&&!operation.beforeHash)){this.repo.updateFilesystemOperation(operation.id,'FAILED','Filesystem was not committed before interruption');failed++;continue;}else{this.repo.updateFilesystemOperation(operation.id,'FAILED','Target state matches neither journal boundary');this.repo.addEvent('FILESYSTEM_RECONCILIATION_FAILED',tick,operation.agentId,null,{operationId:operation.id,error:'Unexpected target hash'});failed++;continue;}}const refreshed=this.repo.incompleteFilesystemOperations().find((item)=>item.id===operation.id);if(refreshed?.state==='FILESYSTEM_COMMITTED')this.repo.commitFilesystemOperation(operation.id);this.repo.updateFilesystemOperation(operation.id,'COMPLETE');completed++;}catch(error){this.repo.updateFilesystemOperation(operation.id,'FAILED',error instanceof Error?error.message:'Reconciliation failed');this.repo.addEvent('FILESYSTEM_RECONCILIATION_FAILED',tick,operation.agentId,null,{operationId:operation.id,error:error instanceof Error?error.message:'Reconciliation failed'});failed++;}}const stagingRemoved=await this.files.cleanupKernelStaging(this.repo.listAgents().map((agent)=>agent.id));this.repo.addEvent('FILESYSTEM_RECONCILIATION_COMPLETED',tick,null,null,{completed,failed,stagingRemoved});return{completed,failed,stagingRemoved};}
}
