import { createHash,createHmac,randomUUID,timingSafeEqual } from 'node:crypto';
import { createServer,type Server } from 'node:http';
import type { WorldRepository } from '../../persistence/src/repository.js';
import { OWNER_ID } from '../../shared/src/index.js';

export interface OwnerIngressInput{transport:string;externalEventId:string;sourceId:string;routeText:string;rawHash:string;}
export interface OwnerIngress{ingest(input:OwnerIngressInput):Promise<{id:string;duplicate:boolean;status:string}>;}
export class OwnerIngressService implements OwnerIngress{
  constructor(private readonly repo:WorldRepository){}
  async accept(input:OwnerIngressInput):Promise<{id:string;duplicate:boolean;status:string}>{const created=this.repo.createOwnerIngress(input),tick=this.repo.getWorld()?.currentTick??0;if(created.duplicate){this.repo.addEvent('OWNER_WEBHOOK_REDELIVERED',tick,OWNER_ID,null,{transport:input.transport,externalEventId:input.externalEventId,ingressId:created.record.id});return{id:created.record.id,duplicate:true,status:created.record.status};}this.repo.addEvent('OWNER_INGRESS_RECEIVED',tick,OWNER_ID,null,{transport:input.transport,externalEventId:input.externalEventId,ingressId:created.record.id});return{id:created.record.id,duplicate:false,status:'RECEIVED'};}
  async process(id:string):Promise<{id:string;duplicate:boolean;status:string}>{const record=this.repo.getOwnerIngress(id);if(!record)throw new Error('Owner ingress record not found');if(record.status!=='RECEIVED')return{id,duplicate:true,status:record.status};const route=/^(Mam|Toey):\s+([\s\S]{1,8000})$/i.exec(record.routeText.trim());const tick=this.repo.getWorld()?.currentTick??0;if(!route){this.repo.finishOwnerIngress(id,'REJECTED',null,null,'Expected routing syntax: Mam: message or Toey: message');this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{ingressId:id,error:'Unresolved recipient'});return{id,duplicate:false,status:'REJECTED'};}const agent=this.repo.getAgent(route[1]!);if(!agent){this.repo.finishOwnerIngress(id,'REJECTED',route[1]!,route[2]!, 'Recipient not found');this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{ingressId:id,error:'Recipient not found'});return{id,duplicate:false,status:'REJECTED'};}const message=this.repo.sendMessage(OWNER_ID,'owner',agent.id,tick,route[2]!);this.repo.finishOwnerIngress(id,'INGESTED',agent.name,route[2]!,null);this.repo.addEvent('OWNER_MESSAGE_INGESTED',tick,OWNER_ID,agent.id,{ingressId:id,messageId:message.id,transport:record.transport});return{id,duplicate:false,status:'INGESTED'};}
  async ingest(input:OwnerIngressInput):Promise<{id:string;duplicate:boolean;status:string}>{const accepted=await this.accept(input);return accepted.duplicate?accepted:this.process(accepted.id);}
  async ingestCli(recipient:string,content:string):Promise<{id:string;duplicate:boolean;status:string}>{const routeText=`${recipient}: ${content}`;return this.ingest({transport:'cli',externalEventId:randomUUID(),sourceId:'local-owner',routeText,rawHash:createHash('sha256').update(routeText).digest('hex')});}
  reject(input:OwnerIngressInput,error:string):void{const created=this.repo.createOwnerIngress(input),tick=this.repo.getWorld()?.currentTick??0;if(!created.duplicate){this.repo.finishOwnerIngress(created.record.id,'REJECTED',null,null,error);this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{ingressId:created.record.id,transport:input.transport,error});}else this.repo.addEvent('OWNER_WEBHOOK_REDELIVERED',tick,OWNER_ID,null,{ingressId:created.record.id,transport:input.transport});}
}

export interface LineIngressConfig{channelSecret:string;ownerSourceId:string;maxBodyBytes?:number;}
export interface LineWebhookResult{statusCode:number;accepted:number;rejected:number;duplicates:number;}
export class LineWebhookIngress{
  private readonly pending:Promise<unknown>[]=[];private readonly maxBodyBytes:number;
  constructor(private readonly service:OwnerIngressService,private readonly repo:WorldRepository,private readonly config:LineIngressConfig){this.maxBodyBytes=config.maxBodyBytes??256*1024;}
  verify(rawBody:Buffer,signature:string|undefined):boolean{if(!signature||rawBody.length>this.maxBodyBytes)return false;const expected=createHmac('sha256',this.config.channelSecret).update(rawBody).digest(),received=Buffer.from(signature,'base64');return received.length===expected.length&&timingSafeEqual(received,expected);}
  async handleRaw(rawBody:Buffer,signature:string|undefined):Promise<LineWebhookResult>{const tick=this.repo.getWorld()?.currentTick??0;if(rawBody.length>this.maxBodyBytes){this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{transport:'line',error:'Request body too large'});return{statusCode:413,accepted:0,rejected:1,duplicates:0};}if(!this.verify(rawBody,signature)){this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{transport:'line',error:'Invalid signature'});return{statusCode:401,accepted:0,rejected:1,duplicates:0};}let payload:any;try{payload=JSON.parse(rawBody.toString('utf8'));}catch{this.repo.addEvent('OWNER_INGRESS_REJECTED',tick,OWNER_ID,null,{transport:'line',error:'Malformed JSON'});return{statusCode:400,accepted:0,rejected:1,duplicates:0};}if(!Array.isArray(payload.events)||payload.events.length>100)return{statusCode:400,accepted:0,rejected:1,duplicates:0};let accepted=0,rejected=0,duplicates=0;const rawHash=createHash('sha256').update(rawBody).digest('hex');for(const event of payload.events){if(event?.type!=='message'||event?.message?.type!=='text')continue;const externalEventId=typeof event.webhookEventId==='string'?event.webhookEventId:createHash('sha256').update(JSON.stringify(event)).digest('hex'),sourceId=typeof event.source?.userId==='string'?event.source.userId:'unknown',routeText=typeof event.message.text==='string'?event.message.text:'';const input={transport:'line',externalEventId,sourceId,routeText,rawHash};if(sourceId!==this.config.ownerSourceId){this.service.reject(input,'LINE source is not the configured Owner');rejected++;continue;}const result=await this.service.accept(input);if(result.duplicate){duplicates++;continue;}accepted++;const work=this.service.process(result.id);this.pending.push(work);void work.finally(()=>{const index=this.pending.indexOf(work);if(index>=0)this.pending.splice(index,1);});}return{statusCode:200,accepted,rejected,duplicates};}
  async drain():Promise<void>{await Promise.all([...this.pending]);}
}

export function createLineWebhookServer(ingress:LineWebhookIngress,port:number):Promise<Server>{const server=createServer((request,response)=>{if(request.method!=='POST'||request.url!=='/line/webhook'){response.writeHead(404).end();return;}const chunks:Buffer[]=[];let bytes=0,tooLarge=false;request.on('data',(chunk:Buffer)=>{bytes+=chunk.length;if(bytes>256*1024){tooLarge=true;request.destroy();return;}chunks.push(chunk);});request.on('end',async()=>{if(tooLarge){response.writeHead(413).end();return;}const result=await ingress.handleRaw(Buffer.concat(chunks),request.headers['x-line-signature'] as string|undefined);response.writeHead(result.statusCode,{'content-type':'application/json'}).end(JSON.stringify(result));});});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',()=>resolve(server));});}
